/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.544453    
*/

/**
* @file myLLMModel_mod.cpp
* @brief Module Implementation for myLLMModel_mod
*
*/

#include "ECOA.hpp"
#include "myLLMModel_mod.hpp"


#include "ECOA.hpp"
#include "Common_lib.hpp"


namespace myLLMModel_mod
{

/* Entry points for lifecycle operations */

void Module::INITIALIZE__received(){
	/* @TODO TODO - To be implemented */
}

void Module::START__received(){
	/* @TODO TODO - To be implemented */
}

void Module::STOP__received(){
	/* @TODO TODO - To be implemented */
}

void Module::SHUTDOWN__received(){
	/* @TODO TODO - To be implemented */
}

void Module::voice_control__received(const Common_lib::voice_msg& voice_content){
	/* @TODO TODO - To be implemented */
}

void Module::voice_query__received(const Common_lib::voice_msg& voice_content){
	/* @TODO TODO - To be implemented */
}

void Module::query_versioned_json__response_received(const ECOA::uint32 ID, const ECOA::return_status status, const Common_lib::json_text& payload){
	/* @TODO TODO - To be implemented */
}

/* Fault Handling API , linked to another namespace (fault_handler_impl_name) */

extern "C" {

	Module* myLLMModel_mod__new_instance()
	{
		return new Module();
	}
}

} /* namespace myLLMModel_mod */
