/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:21.956131    
*
* WARNING: all changes made in this file will be lost
*/


/* Module Container Implementation Skeleton for myVoiceMgmt_mod */

/* @file myVoiceMgmt_mod_container.c
 * This is the Module Container for Module myVoiceMgmt_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

#include <assert.h>
#include "route.h"
#include "ldp_network.h"
#include "ldp_time_manager.h"
#include "ldp_VD.h"
#include "ldp_ELI_udp.h"
#include "ldp_mod_container_util.h"
#include "myVoiceMgmt_mod_container.h"
#include "component_mycompVoiceMgmt__properties.h"

#include "ECOA.h"
#include "ECOA_simple_types_serialization.h"
#include "Common_lib.h"
#include "Common_lib_serialization.h"

ECOA__return_status myVoiceMgmt_mod_container__query_versioned_json__response_send(myVoiceMgmt_mod__context* context, const ECOA__uint32 ID, const Common_lib__json_text* payload)
{
    ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
    ctx->req_resp.current_RR_number[0]--;
    ldp_node* node;
    uint32_t params_size = sizeof(ECOA__uint32)+sizeof(Common_lib__json_text);
    ldp_req_received* req=ldp_find_req_received(&ctx->req_resp,ID, &node);

    if (req != NULL){
        char* param_msg = ctx->msg_buffer;
        if(req->connection_type == LDP_REQUEST_EXTERNAL){
        uint32_t added_size = 0;
        uint32_t total_added_size = LDP_ELI_UDP_HEADER_SIZE + LDP_ELI_HEADER_SIZE + sizeof(ECOA__uint32);
        uint32_t max_size = params_size - sizeof(ECOA__uint32);
        serialize_Common_lib__json_text(payload, &param_msg[total_added_size], max_size ,&added_size);
        max_size -= added_size;
        total_added_size += added_size;

            ldp_mod_request_answer_send_external(ctx, param_msg, params_size, req);
        }else{
        memcpy(&param_msg[sizeof(ECOA__uint32)+sizeof(ECOA__uint32)+LDP_HEADER_TCP_SIZE], payload,sizeof(Common_lib__json_text));

            ldp_mod_request_answer_send_local(ctx, param_msg,params_size, req);
        }
        ldp_free_req_received(&ctx->req_resp,node);
    }else{
        ldp_log_PF_log(ECOA_LOG_ERROR_PF,"ERROR", ctx->logger_PF,"cant send RR answer: no client found");
        ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                         ECOA__error_type_UNAVAILABLE, 8);
        return ECOA__return_status_INVALID_IDENTIFIER;
    }
    return ECOA__return_status_OK;
}

ECOA__return_status myVoiceMgmt_mod_container__event_data_out__get_write_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__event_data_out_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_get_written_access(&ctx->VD_writter_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 12);
}

    return ret;
}

ECOA__return_status myVoiceMgmt_mod_container__event_data_out__cancel_write_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__event_data_out_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_cancel_written_access(&ctx->VD_writter_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 13);
}

return ret;

}

ECOA__return_status myVoiceMgmt_mod_container__event_data_out__publish_write_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__event_data_out_handle* data_handle)
{
  
ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_publish_written_access(ctx, &ctx->VD_writter_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 14);
}

return ret;

}

ECOA__return_status myVoiceMgmt_mod_container__versioned_data_in__get_read_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__versioned_data_in_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_get_read_access(&ctx->VD_reader_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 15);
}

return ret;
}

ECOA__return_status myVoiceMgmt_mod_container__versioned_data_in__release_read_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__versioned_data_in_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_release_read_access(&ctx->VD_reader_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 16);
}

return ret;

}

/* Properties API */


/* PINFO API */

/* Logging services API call specifications */
void myVoiceMgmt_mod_container__log_trace(myVoiceMgmt_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_TRACE, "TRACE", ctx->logger,  log.data, &timestamp);
}
void myVoiceMgmt_mod_container__log_debug(myVoiceMgmt_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_DEBUG, "DEBUG", ctx->logger, log.data, &timestamp);
}
void myVoiceMgmt_mod_container__log_info(myVoiceMgmt_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_INFO, "INFO", ctx->logger, log.data, &timestamp);
}
void myVoiceMgmt_mod_container__log_warning(myVoiceMgmt_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_WARN, "WARNING", ctx->logger, log.data, &timestamp);
}
void myVoiceMgmt_mod_container__raise_error(myVoiceMgmt_mod__context* context, const ECOA__log log, const ECOA__error_code error_code){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_ERROR, 1);
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_ERROR, "ERROR", ctx->logger, log.data, &timestamp);
}
void myVoiceMgmt_mod_container__raise_fatal_error(myVoiceMgmt_mod__context* context, const ECOA__log log, const ECOA__error_code error_code){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   find_dest_mod_by_comp_and_send(ctx->component_ctx, ctx->component_name, LDP_ID_SHUTDOWN_life);
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_FATAL_ERROR, 1);
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_FATAL, "FATAL", ctx->logger, log.data, &timestamp);
}

/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myVoiceMgmt_mod_container__get_relative_local_time(myVoiceMgmt_mod__context* context, ECOA__hr_time *relative_local_time){
    ldp_get_ecoa_relative_time(NULL, (ldp__timestamp*) relative_local_time);
    UNUSED(context);
}
ECOA__return_status myVoiceMgmt_mod_container__get_UTC_time(myVoiceMgmt_mod__context* context, ECOA__global_time *utc_time){
    ldp_get_ecoa_utc_time((ldp__timestamp *) utc_time);
    UNUSED(context);
    return ECOA__return_status_OK;
}

ECOA__return_status myVoiceMgmt_mod_container__get_absolute_system_time(myVoiceMgmt_mod__context* context, ECOA__global_time *absolute_system_time){
    ldp_get_ecoa_absolute_time((ldp__timestamp *) absolute_system_time);
    UNUSED(context);
    return ECOA__return_status_OK;
}


void myVoiceMgmt_mod_container__get_relative_local_time_resolution(myVoiceMgmt_mod__context* context, ECOA__duration *relative_local_time_resolution)
{
  ldp_get_ecoa_relative_timeres((ldp__timestamp *)relative_local_time_resolution);

UNUSED(context);
}

void myVoiceMgmt_mod_container__get_UTC_time_resolution(myVoiceMgmt_mod__context* context, ECOA__duration *utc_time_resolution)
{
  ldp_get_ecoa_utc_timeres((ldp__timestamp *)utc_time_resolution);

UNUSED(context);
}

void myVoiceMgmt_mod_container__get_absolute_system_time_resolution(myVoiceMgmt_mod__context* context, ECOA__duration *absolute_system_time_resolution)
{
  ldp_get_ecoa_absolute_timeres((ldp__timestamp *)absolute_system_time_resolution);

UNUSED(context);
}


