/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.531360    
*
* WARNING: all changes made in this file will be lost
*/

/*
* Container Types for Module myXXXDevice_mod
* Generated automatically from specification;
*/

#if !defined(_MYXXXDEVICE_MOD_CONTAINER_TYPES_HPP)
#define _MYXXXDEVICE_MOD_CONTAINER_TYPES_HPP

#define ECOA_VERSIONED_DATA_HANDLE_PRIVATE_SIZE 32

#include <ECOA.hpp>
namespace myXXXDevice_mod {
   
}
#endif /* _MYXXXDEVICE_MOD_CONTAINER_TYPES_HPP */