/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.577893    
*/

/**
* @file myXXXDevice_mod.cpp
* @brief Module Implementation for myXXXDevice_mod
*
*/

#include "ECOA.hpp"
#include "myXXXDevice_mod.hpp"


#include "ECOA.hpp"
#include "Common_lib.hpp"


namespace myXXXDevice_mod
{

/* Entry points for lifecycle operations */

void Module::INITIALIZE__received(){
	/* @TODO TODO - To be implemented */
}

void Module::START__received(){
	/* @TODO TODO - To be implemented */
}

void Module::STOP__received(){
	/* @TODO TODO - To be implemented */
}

void Module::SHUTDOWN__received(){
	/* @TODO TODO - To be implemented */
}

void Module::trigger_voice__received(){
	/* @TODO TODO - To be implemented */
}

/* Fault Handling API , linked to another namespace (fault_handler_impl_name) */

extern "C" {

	Module* myXXXDevice_mod__new_instance()
	{
		return new Module();
	}
}

} /* namespace myXXXDevice_mod */
