/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.276316    
*
* WARNING: all changes made in this file will be lost
*/

#include "ldp_network.h"
#include "ECOA.h"
#include "ECOA_simple_types_serialization.h"
#include "Common_lib.h"
#include "Common_lib_serialization.h"
uint32_t deserialized_svc_event_data_event_data(char* dest, char* src){
    uint32_t index_dest = 0;
    uint32_t index_src = 0;
    uint32_t dest_length = ECOA__UINT32_MAX; // max buffer size
    deserialize_Common_lib__event_data((void*) &dest[index_dest], &src[index_src], dest_length);
    index_src += size_of_Common_lib__event_data();
    dest_length -= size_of_Common_lib__event_data();
    index_dest += sizeof(Common_lib__event_data);
    return index_dest; 
}
uint32_t serialized_svc_event_data_event_data(char* dest, char* src){
    uint32_t added_size;
    serialize_Common_lib__event_data((Common_lib__event_data*) &src[0], &dest[0], ECOA__UINT32_MAX, &added_size);
    return added_size;
}
uint32_t params_size_svc_event_data_event_data(void){
    return 0+sizeof(Common_lib__event_data);
}
uint32_t min_buffer_size_svc_event_data(void){
    uint32_t max = 0;
    uint32_t tmp = 0;
    tmp = params_size_svc_event_data_event_data();
    max = ( tmp < max ) ? max : tmp;
    return max+LDP_ELI_HEADER_SIZE+LDP_ELI_UDP_HEADER_SIZE;
}

