/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.276049    
*
* WARNING: all changes made in this file will be lost
*/

#include "ldp_network.h"
#include "ECOA.h"
#include "ECOA_simple_types_serialization.h"
#include "Common_lib.h"
#include "Common_lib_serialization.h"
uint32_t deserialized_svc_voice_msg_voice_control(char* dest, char* src){
    uint32_t index_dest = 0;
    uint32_t index_src = 0;
    uint32_t dest_length = ECOA__UINT32_MAX; // max buffer size
    deserialize_Common_lib__voice_msg((void*) &dest[index_dest], &src[index_src], dest_length);
    index_src += current_size_of_Common_lib__voice_msg((Common_lib__voice_msg*)&dest[index_dest]);
    dest_length -= current_size_of_Common_lib__voice_msg((Common_lib__voice_msg*)&dest[index_dest]);
    index_dest += sizeof(Common_lib__voice_msg);
    return index_dest; 
}
uint32_t deserialized_svc_voice_msg_voice_query(char* dest, char* src){
    uint32_t index_dest = 0;
    uint32_t index_src = 0;
    uint32_t dest_length = ECOA__UINT32_MAX; // max buffer size
    deserialize_Common_lib__voice_msg((void*) &dest[index_dest], &src[index_src], dest_length);
    index_src += current_size_of_Common_lib__voice_msg((Common_lib__voice_msg*)&dest[index_dest]);
    dest_length -= current_size_of_Common_lib__voice_msg((Common_lib__voice_msg*)&dest[index_dest]);
    index_dest += sizeof(Common_lib__voice_msg);
    return index_dest; 
}
uint32_t params_size_svc_voice_msg_voice_control(void){
    return 0+sizeof(Common_lib__voice_msg);
}
uint32_t params_size_svc_voice_msg_voice_query(void){
    return 0+sizeof(Common_lib__voice_msg);
}
uint32_t min_buffer_size_svc_voice_msg(void){
    uint32_t max = 0;
    uint32_t tmp = 0;
    tmp = params_size_svc_voice_msg_voice_control();
    max = ( tmp < max ) ? max : tmp;
    tmp = params_size_svc_voice_msg_voice_query();
    max = ( tmp < max ) ? max : tmp;
    return max+LDP_ELI_HEADER_SIZE+LDP_ELI_UDP_HEADER_SIZE;
}

