/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.276193    
*
* WARNING: all changes made in this file will be lost
*/

#include "ECOA.h"
#include "Common_lib.h"
uint32_t deserialized_svc_event_data_event_data(char* dest, char* src);
uint32_t serialized_svc_event_data_event_data(char* dest, char* src);
uint32_t params_size_svc_event_data_event_data(void);
uint32_t min_buffer_size_svc_event_data(void);

