/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.661114    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _COMPONENT_MYCOMPYYYDEVICE_H 
#define _COMPONENT_MYCOMPYYYDEVICE_H 

#include <apr_thread_proc.h>
#include "ldp_structures.h"

void* start_module_compYYYDevice_myYYYDevice_mod_inst(apr_thread_t* t, void* args);
 extern ldp_PDomain_ctx* compYYYDevice_ctx;
ldp_PDomain_ctx* init_comp_compYYYDevice(void);

#endif  /* _COMPONENT_MYCOMPYYYDEVICE_H */
