/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.550562    
*
* WARNING: all changes made in this file will be lost
*/

/**
* @file myLLMModel_mod.hpp
* @brief Module Header for myLLMModel_mod
*
*/

#if !defined(_myLLMModel_mod_HPP)
#define _myLLMModel_mod_HPP


#include "ECOA.hpp"
#include "myLLMModel_mod_container.hpp"
#include "myLLMModel_mod_container_types.hpp"
#include "myLLMModel_mod_user_context.hpp"
#include "ECOA.hpp"
#include "Common_lib.hpp"

namespace myLLMModel_mod
{

class Module
{
	public:

		/* Entry points for lifecycle operations */

		void INITIALIZE__received();

		void START__received();

		void STOP__received();

		void SHUTDOWN__received();

		warm_start_context warm_start;

		void voice_control__received(const Common_lib::voice_msg& voice_content);
		void voice_query__received(const Common_lib::voice_msg& voice_content);
		void query_versioned_json__response_received(const ECOA::uint32 ID, const ECOA::return_status status, const Common_lib::json_text& payload);

		Container* container;

		user_context user;

}; /* Class Module */

extern "C" {
	Module* myLLMModel_mod__new_instance();
}

} /* namespace myLLMModel_mod */

#endif  /* _MYLLMMODEL_MOD_HPP */