/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.587951    
*
* WARNING: all changes made in this file will be lost
*/


/*
 * @file Common_lib_serialization.c
 * This is data-type declaration file
 */
#include <string.h>
#include <stdint.h>
#include <arpa/inet.h>
#include <ECOA.h>
#include <ECOA_simple_types_serialization.h>
#include "Common_lib.h"
#include "Common_lib_serialization.h"


/* Type Common_lib__event_data */
void serialize_Common_lib__event_data(const Common_lib__event_data *data, void *buffer, uint32_t max_size, uint32_t *added_size)
{
    void *index = buffer;
    uint32_t max_field_size = 0;
    uint32_t added_field_size = 0;
    if(max_size >= size_of_Common_lib__event_data()) {
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->topic_id), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_0), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_1), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_2), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_3), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_4), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_5), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_6), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->status_word_7), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->flag_0), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->flag_1), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->flag_2), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->flag_3), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;

        *added_size = size_of_Common_lib__event_data();
    }
}

void deserialize_Common_lib__event_data(Common_lib__event_data *data, void *buffer, uint32_t length)
{
    void *index = buffer;
    uint32_t field_size = 0;
    if(length >= size_of_Common_lib__event_data()) {
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->topic_id), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_0), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_1), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_2), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_3), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_4), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_5), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_6), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->status_word_7), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->flag_0), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->flag_1), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->flag_2), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->flag_3), index, field_size);
        index = index + sizeof(ECOA__uint8);

    }
}

uint32_t size_of_Common_lib__event_data(void)
{
    uint32_t size = 0;
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);

    return size;
}


/* Type Common_lib__versioned_data */
void serialize_Common_lib__versioned_data(const Common_lib__versioned_data *data, void *buffer, uint32_t max_size, uint32_t *added_size)
{
    void *index = buffer;
    uint32_t max_field_size = 0;
    uint32_t added_field_size = 0;
    if(max_size >= size_of_Common_lib__versioned_data()) {
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->version), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->sample_0), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->sample_1), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->sample_2), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint16);
        serialize_ECOA__uint16((data->sample_3), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_0), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_1), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_2), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_3), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_4), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_5), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_6), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_7), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;
        max_field_size = sizeof(ECOA__uint8);
        serialize_ECOA__uint8((data->channel_8), index, max_field_size, &added_field_size);
        index = index + added_field_size;
        added_field_size = 0;

        *added_size = size_of_Common_lib__versioned_data();
    }
}

void deserialize_Common_lib__versioned_data(Common_lib__versioned_data *data, void *buffer, uint32_t length)
{
    void *index = buffer;
    uint32_t field_size = 0;
    if(length >= size_of_Common_lib__versioned_data()) {
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->version), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->sample_0), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->sample_1), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->sample_2), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint16);
        deserialize_ECOA__uint16(&(data->sample_3), index, field_size);
        index = index + sizeof(ECOA__uint16);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_0), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_1), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_2), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_3), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_4), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_5), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_6), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_7), index, field_size);
        index = index + sizeof(ECOA__uint8);
        field_size = sizeof(ECOA__uint8);
        deserialize_ECOA__uint8(&(data->channel_8), index, field_size);
        index = index + sizeof(ECOA__uint8);

    }
}

uint32_t size_of_Common_lib__versioned_data(void)
{
    uint32_t size = 0;
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint16);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);
    size = size + sizeof(ECOA__uint8);

    return size;
}


/* Type Common_lib__json_text */
void serialize_Common_lib__json_text(const Common_lib__json_text *data, void *buffer, uint32_t max_size, uint32_t *added_size)
{
    uint32_t i = 0;
    uint32_t item_added_size = 0;
    void *index = buffer;
    uint32_t item_size = 0;
    if(max_size >= current_size_of_Common_lib__json_text(data)) {
        serialize_ECOA__uint32(data->current_size, index, sizeof(ECOA__uint32), &item_added_size);
        index = index + item_added_size;
        item_size = sizeof(ECOA__char8);
        for(i = 0; i < data->current_size; i++) {
            serialize_ECOA__char8((*data).data[i], index, item_size, &item_added_size);
            index = index + item_added_size;
            item_added_size = 0;
        }
        *added_size = current_size_of_Common_lib__json_text(data);
    }
}

void deserialize_Common_lib__json_text(Common_lib__json_text *data, void *buffer, uint32_t length)
{
    uint32_t i = 0;
    void *index = buffer;
    uint32_t item_size = 0;
    if(length >= max_size_of_Common_lib__json_text()) {
        deserialize_ECOA__uint32(&data->current_size, index, sizeof(ECOA__uint32));
        if(data->current_size > Common_lib__json_text_MAXSIZE) {
            data->current_size = Common_lib__json_text_MAXSIZE;
        }
        index = index + sizeof(ECOA__uint32);
        item_size = sizeof(ECOA__char8);
        for(i = 0; i < data->current_size; i++) {
            deserialize_ECOA__char8(&(*data).data[i], index, item_size);
            index = index + sizeof(ECOA__char8);
        }
    }
}

uint32_t max_size_of_Common_lib__json_text(void)
{
    uint32_t size = 0;
    size = sizeof(ECOA__char8) * Common_lib__json_text_MAXSIZE + sizeof(ECOA__uint32);
    return size;
}

uint32_t current_size_of_Common_lib__json_text(const Common_lib__json_text*data)
{
    uint32_t size = 0;
    size = sizeof(ECOA__char8) * data->current_size + sizeof(ECOA__uint32);
    return size;
}



/* Type Common_lib__voice_msg */
void serialize_Common_lib__voice_msg(const Common_lib__voice_msg *data, void *buffer, uint32_t max_size, uint32_t *added_size)
{
    uint32_t i = 0;
    uint32_t item_added_size = 0;
    void *index = buffer;
    uint32_t item_size = 0;
    if(max_size >= current_size_of_Common_lib__voice_msg(data)) {
        serialize_ECOA__uint32(data->current_size, index, sizeof(ECOA__uint32), &item_added_size);
        index = index + item_added_size;
        item_size = sizeof(ECOA__char8);
        for(i = 0; i < data->current_size; i++) {
            serialize_ECOA__char8((*data).data[i], index, item_size, &item_added_size);
            index = index + item_added_size;
            item_added_size = 0;
        }
        *added_size = current_size_of_Common_lib__voice_msg(data);
    }
}

void deserialize_Common_lib__voice_msg(Common_lib__voice_msg *data, void *buffer, uint32_t length)
{
    uint32_t i = 0;
    void *index = buffer;
    uint32_t item_size = 0;
    if(length >= max_size_of_Common_lib__voice_msg()) {
        deserialize_ECOA__uint32(&data->current_size, index, sizeof(ECOA__uint32));
        if(data->current_size > Common_lib__voice_msg_MAXSIZE) {
            data->current_size = Common_lib__voice_msg_MAXSIZE;
        }
        index = index + sizeof(ECOA__uint32);
        item_size = sizeof(ECOA__char8);
        for(i = 0; i < data->current_size; i++) {
            deserialize_ECOA__char8(&(*data).data[i], index, item_size);
            index = index + sizeof(ECOA__char8);
        }
    }
}

uint32_t max_size_of_Common_lib__voice_msg(void)
{
    uint32_t size = 0;
    size = sizeof(ECOA__char8) * Common_lib__voice_msg_MAXSIZE + sizeof(ECOA__uint32);
    return size;
}

uint32_t current_size_of_Common_lib__voice_msg(const Common_lib__voice_msg*data)
{
    uint32_t size = 0;
    size = sizeof(ECOA__char8) * data->current_size + sizeof(ECOA__uint32);
    return size;
}


