/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.663341    
*
* WARNING: all changes made in this file will be lost
*/

#include "stdbool.h"
#include "ECOA.h"
#include "LDP__ECOA_types_zeroise.h"
#include "ECOA.h"
#include "LDP__ECOA_types_zeroise.h"
void LDP_ECOA__boolean8_zeroise(ECOA__boolean8 *data){
    *data = ECOA__FALSE;
}
void LDP_ECOA__int8_zeroise(ECOA__int8 *data){
    *data = ECOA__INT8_MIN;
}
void LDP_ECOA__int16_zeroise(ECOA__int16 *data){
    *data = ECOA__INT16_MIN;
}
void LDP_ECOA__int32_zeroise(ECOA__int32 *data){
    *data = ECOA__INT32_MIN;
}
#if defined(ECOA_64BIT_SUPPORT)
void LDP_ECOA__int64_zeroise(ECOA__int64 *data){
    *data = ECOA__INT64_MIN;
}
#endif /* ECOA_64BIT_SUPPORT */
void LDP_ECOA__uint8_zeroise(ECOA__uint8 *data){
    *data = ECOA__UINT8_MIN;
}
void LDP_ECOA__uint16_zeroise(ECOA__uint16 *data){
    *data = ECOA__UINT16_MIN;
}
void LDP_ECOA__uint32_zeroise(ECOA__uint32 *data){
    *data = ECOA__UINT32_MIN;
}
#if defined(ECOA_64BIT_SUPPORT)
void LDP_ECOA__uint64_zeroise(ECOA__uint64 *data){
    *data = ECOA__UINT64_MIN;
}
#endif /* ECOA_64BIT_SUPPORT */
void LDP_ECOA__char8_zeroise(ECOA__char8 *data){
    *data = ECOA__CHAR8_MIN;
}
void LDP_ECOA__byte_zeroise(ECOA__byte *data){
    *data = ECOA__BYTE_MIN;
}
void LDP_ECOA__float32_zeroise(ECOA__float32 *data){
    *data = ECOA__FLOAT32_MIN;
}
#if defined(ECOA_64BIT_SUPPORT)
void LDP_ECOA__double64_zeroise(ECOA__double64 *data){
    *data = ECOA__DOUBLE64_MIN;
}
#endif /* ECOA_64BIT_SUPPORT */
void LDP_ECOA__duration_zeroise(ECOA__duration *data){
    LDP_ECOA__uint32_zeroise(&data->seconds);
    LDP_ECOA__uint32_zeroise(&data->nanoseconds);
}
void LDP_ECOA__global_time_zeroise(ECOA__global_time *data){
    LDP_ECOA__uint32_zeroise(&data->seconds);
    LDP_ECOA__uint32_zeroise(&data->nanoseconds);
}
void LDP_ECOA__hr_time_zeroise(ECOA__hr_time *data){
    LDP_ECOA__uint32_zeroise(&data->seconds);
    LDP_ECOA__uint32_zeroise(&data->nanoseconds);
}
void LDP_ECOA__pinfo_filename_zeroise(ECOA__pinfo_filename *data){
    int i;
    data->current_size = 0;
    for(i=0; i<ECOA__PINFO_FILENAME_MAXSIZE; i++){
        LDP_ECOA__char8_zeroise(&data->data[i]);
    }
}
void LDP_ECOA__log_zeroise(ECOA__log *data){
    int i;
    data->current_size = 0;
    for(i=0; i<ECOA__LOG_MAXSIZE; i++){
        LDP_ECOA__char8_zeroise(&data->data[i]);
    }
}

