/**
* @file LDP_myVoiceMgmt_mod.h
* @brief This is the header of the DA encapsulation library for ECOA
*\n\
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* This file is generated by the DA ECOA tools and shall not be modified
*/

#if !defined(_LDP_myVoiceMgmt_mod_H)
#define _LDP_myVoiceMgmt_mod_H
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include "myVoiceMgmt_mod_container.h"


/* User tool functions */
/******************************************************************************/
void LDP_myVoiceMgmt_mod__concat(myVoiceMgmt_mod__context *context,ECOA__log *log, char *str);

/******************************************************************************/

/* Request/Response API */
/******************************************************************************/
ECOA__return_status LDP_myVoiceMgmt_mod__response_send__query_versioned_json(
        myVoiceMgmt_mod__context *context,
        const ECOA__uint32 ID , const Common_lib__json_text* payload);

/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/* Versioned data */
/******************************************************************************/
// versioned_data_in
ECOA__return_status LDP_myVoiceMgmt_mod__get_read_access__versioned_data_in(
        myVoiceMgmt_mod__context *context,
        myVoiceMgmt_mod_container__versioned_data_in_handle* data_handle);

ECOA__return_status LDP_myVoiceMgmt_mod__release_read_access__versioned_data_in(
        myVoiceMgmt_mod__context *context,
        myVoiceMgmt_mod_container__versioned_data_in_handle* data_handle);

ECOA__return_status LDP_myVoiceMgmt_mod__read__versioned_data_in(
        myVoiceMgmt_mod__context *context,
        Common_lib__versioned_data *data);


/******************************************************************************/
// event_data_out
ECOA__return_status LDP_myVoiceMgmt_mod__get_write_access__event_data_out(
        myVoiceMgmt_mod__context *context,
        myVoiceMgmt_mod_container__event_data_out_handle* data_handle);

ECOA__return_status LDP_myVoiceMgmt_mod__cancel_write_access__event_data_out(
        myVoiceMgmt_mod__context *context,
        myVoiceMgmt_mod_container__event_data_out_handle* data_handle);

ECOA__return_status LDP_myVoiceMgmt_mod__publish_write_access__event_data_out(
        myVoiceMgmt_mod__context *context,
        myVoiceMgmt_mod_container__event_data_out_handle* data_handle);

ECOA__return_status LDP_myVoiceMgmt_mod__write__event_data_out(
        myVoiceMgmt_mod__context *context,
        Common_lib__event_data *data);


/******************************************************************************/

/* Event */
/******************************************************************************/

/******************************************************************************/

/* Property */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/
/* log API */
void LDP_myVoiceMgmt_mod__log_trace(
      myVoiceMgmt_mod__context *context,
      char *log);
void LDP_myVoiceMgmt_mod__log_debug(
      myVoiceMgmt_mod__context *context,
      char *log);
void LDP_myVoiceMgmt_mod__log_info(
      myVoiceMgmt_mod__context *context,
      char *log);
void LDP_myVoiceMgmt_mod__log_warning(
      myVoiceMgmt_mod__context *context,
      char *log);
void LDP_myVoiceMgmt_mod__raise_error(
      myVoiceMgmt_mod__context *context,
      char *log,
      const ECOA__error_code error_code);
void LDP_myVoiceMgmt_mod__raise_fatal_error(
      myVoiceMgmt_mod__context *context,
      char *log,
      const ECOA__error_code error_code);

/* Time API */
ECOA__return_status LDP_myVoiceMgmt_mod__get_relative_local_time(
        myVoiceMgmt_mod__context *context,
        ECOA__hr_time *relative_local_time);
ECOA__return_status LDP_myVoiceMgmt_mod__get_UTC_time(
        myVoiceMgmt_mod__context *context,
        ECOA__global_time *utc_time);
ECOA__return_status LDP_myVoiceMgmt_mod__get_absolute_system_time(
        myVoiceMgmt_mod__context *context,
        ECOA__global_time *absolute_system_time);
ECOA__return_status LDP_myVoiceMgmt_mod__get_relative_local_time_resolution(
        myVoiceMgmt_mod__context *context,
        ECOA__duration *relative_local_time_resolution);
ECOA__return_status LDP_myVoiceMgmt_mod__get_UTC_time_resolution(
        myVoiceMgmt_mod__context *context,
        ECOA__duration *utc_time_resolution);
ECOA__return_status LDP_myVoiceMgmt_mod__get_absolute_system_time_resolution(
        myVoiceMgmt_mod__context *context,
        ECOA__duration *absolute_system_time_resolution);
/******************************************************************************/

/* PINFO API */
/******************************************************************************/

/******************************************************************************/


#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _LDP_myVoiceMgmt_mod_H */

