/*******************************************************************************
 * Copyright (c) 2024 Dassault Aviation.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Dassault Aviation - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.web.edt.importexport;

import java.io.IOException;
import java.util.Map;
import java.util.Objects;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.eclipse.sirius.web.application.project.services.api.IProjectExportParticipant;
import org.eclipse.sirius.web.domain.boundedcontexts.project.Project;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/**
 * Embeds a complete ECOA XML bundle inside the Sirius Web project ZIP under
 * {@code {projectName}/ecoa-steps-bundle.zip}.
 *
 * <p>On import via {@link EdtImportSiriusWebZipEventHandler}, this bundle is detected and used
 * directly with {@link EdtEcoaImportService#parseZipToSteps(byte[])} to rebuild the EDT model from
 * scratch — bypassing the Sirius Web JSON round-trip entirely.  This guarantees that service
 * connections (DataLink / EventLink / RequestLink) are always correctly restored, on any machine,
 * regardless of whether {@code ServiceDefinition.operations} survived JSON serialisation.
 *
 * <p>The embedded ECOA XML is generated by {@link EdtEcoaExportService#exportToZip}, which uses the
 * {@link EcoaInterfaceXmlCache} as a fallback when the in-memory model has lost service-definition
 * operations.
 */
@Service
public class EcoaXmlProjectExportParticipant implements IProjectExportParticipant {

    /** Entry name (relative to the project folder) of the embedded ECOA ZIP. */
    public static final String ECOA_BUNDLE_ENTRY = "ecoa-steps-bundle.zip";

    private static final Logger LOGGER = LoggerFactory.getLogger(EcoaXmlProjectExportParticipant.class);

    private final EdtEcoaExportService ecoaExportService;

    public EcoaXmlProjectExportParticipant(EdtEcoaExportService ecoaExportService) {
        this.ecoaExportService = Objects.requireNonNull(ecoaExportService);
    }

    @Override
    public Map<String, Object> exportData(Project project, String editingContextId, ZipOutputStream outputStream) {
        var ecoaZipOpt = this.ecoaExportService.exportToZip(editingContextId, project.getName());
        if (ecoaZipOpt.isEmpty()) {
            LOGGER.warn("EcoaXmlProjectExportParticipant: ECOA export produced no bytes for editing context {} - skipping bundle", editingContextId);
            return Map.of();
        }
        byte[] ecoaZipBytes = ecoaZipOpt.get();
        String zipPath = project.getName() + "/" + ECOA_BUNDLE_ENTRY;
        try {
            outputStream.putNextEntry(new ZipEntry(zipPath));
            outputStream.write(ecoaZipBytes);
            outputStream.closeEntry();
            LOGGER.info("EcoaXmlProjectExportParticipant: embedded {} bytes of ECOA XML as '{}' for editing context {}",
                    ecoaZipBytes.length, zipPath, editingContextId);
        } catch (IOException e) {
            LOGGER.warn("EcoaXmlProjectExportParticipant: failed to write '{}': {}", zipPath, e.getMessage());
        }
        return Map.of();
    }
}
