/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:26:45.115193    
*/


/* Fault Handler Implementation for Platform_XXX */
#include "ldp_network.h"
#include "Platform_XXX_fault_handler.h"

void Platform_XXX__initialize_user_context(Platform_XXX_user_context * context) {
  /* @TODO TODO - To be implemented */
}

void Platform_XXX__error_notification (
  ldp_fault_handler_context* context, 
  ECOA__error_id error_id,
  ECOA__global_time timestamp,
  ECOA__asset_id asset_id,
  ECOA__asset_type asset_type,
  ECOA__error_type error_type,
  ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}
