/* Module Helpers Implementation for myXXXDevice_mod */

/* @file myXXXDevice_mod_helpers.c
 * This is the Module Test Container for Module myXXXDevice_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by LDP */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myXXXDevice_mod_container.h"
#include "myXXXDevice_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"


const char* MYXXXDEVICE_MOD = "MYXXXDEVICE_MOD: ";

void myXXXDevice_mod_log_info(myXXXDevice_mod__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYXXXDEVICE_MOD, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYXXXDEVICE_MOD, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myXXXDevice_mod_container__log_info(context, log);
}

void myXXXDevice_mod_log(myXXXDevice_mod__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYXXXDEVICE_MOD, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYXXXDEVICE_MOD, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myXXXDevice_mod_container__log_debug(context, log);
}



