/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.022852    
*
* WARNING: all changes made in this file will be lost
*/

#include "ECOA.h"
#include "Common_lib.h"
uint32_t deserialized_svc_vd_query_query_versioned_json_answer(char* dest, char* src);
uint32_t deserialized_svc_vd_query_query_versioned_json_request(char* dest, char* src);
uint32_t params_size_svc_vd_query_query_versioned_json_answer(void);
uint32_t params_size_svc_vd_query_query_versioned_json_request(void);
uint32_t min_buffer_size_svc_vd_query(void);

