/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.024006    
*
* WARNING: all changes made in this file will be lost
*/

#include "ECOA.h"
#include "Common_lib.h"
uint32_t deserialized_svc_json_cmd_json_control(char* dest, char* src);
uint32_t params_size_svc_json_cmd_json_control(void);
uint32_t min_buffer_size_svc_json_cmd(void);

