/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.023160    
*
* WARNING: all changes made in this file will be lost
*/

#include "ECOA.h"
#include "Common_lib.h"
uint32_t deserialized_svc_versioned_data_versioned_data(char* dest, char* src);
uint32_t serialized_svc_versioned_data_versioned_data(char* dest, char* src);
uint32_t params_size_svc_versioned_data_versioned_data(void);
uint32_t min_buffer_size_svc_versioned_data(void);

