/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.023014    
*
* WARNING: all changes made in this file will be lost
*/

#include "ldp_network.h"
#include "ECOA.h"
#include "ECOA_simple_types_serialization.h"
#include "Common_lib.h"
#include "Common_lib_serialization.h"
uint32_t deserialized_svc_vd_query_query_versioned_json_answer(char* dest, char* src){
    memcpy(&dest[0], src, sizeof(ECOA__uint32)); // copie ID
    uint32_t index_dest = sizeof(ECOA__uint32);
    uint32_t index_src = sizeof(ECOA__uint32);
    uint32_t dest_length = ECOA__UINT32_MAX; // max buffer size
    deserialize_Common_lib__json_text((void*) &dest[index_dest], &src[index_src], dest_length);
    index_src += current_size_of_Common_lib__json_text((Common_lib__json_text*)&dest[index_dest]);
    dest_length -= current_size_of_Common_lib__json_text((Common_lib__json_text*)&dest[index_dest]);
    index_dest += sizeof(Common_lib__json_text);
    return index_dest; 
}
uint32_t deserialized_svc_vd_query_query_versioned_json_request(char* dest, char* src){
    memcpy(&dest[0], src, sizeof(ECOA__uint32)); // TODO: what to do for 32bit OS?
    return sizeof(ECOA__uint32);
}
uint32_t params_size_svc_vd_query_query_versioned_json_request(void){
    return 0;
}
uint32_t params_size_svc_vd_query_query_versioned_json_answer(void){
    return 0+sizeof(Common_lib__json_text);
}
uint32_t min_buffer_size_svc_vd_query(void){
    uint32_t max = 0;
    uint32_t tmp = 0;
    tmp = params_size_svc_vd_query_query_versioned_json_request();
    max = ( tmp < max ) ? max : tmp;
    tmp = params_size_svc_vd_query_query_versioned_json_answer();
    max = ( tmp < max ) ? max : tmp;
    return max+LDP_ELI_HEADER_SIZE+LDP_ELI_UDP_HEADER_SIZE;
}

