/* Module Helpers Implementation for myLLMModel_mod */

/* @file myLLMModel_mod_helpers.c
 * This is the Module Test Container for Module myLLMModel_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by LDP */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myLLMModel_mod_container.h"
#include "myLLMModel_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"


const char* MYLLMMODEL_MOD = "MYLLMMODEL_MOD: ";

void myLLMModel_mod_log_info(myLLMModel_mod__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYLLMMODEL_MOD, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYLLMMODEL_MOD, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myLLMModel_mod_container__log_info(context, log);
}

void myLLMModel_mod_log(myLLMModel_mod__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYLLMMODEL_MOD, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYLLMMODEL_MOD, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myLLMModel_mod_container__log_debug(context, log);
}



