/* Generated by LDP */
/* Tests of the Module Implementation myLLMModel_mod */

#include "ECOA.h"
#include "myLLMModel_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myLLMModel_mod__context context;
	ECOA__uint32 ID;
	myLLMModel_mod__INITIALIZE__received(&context);
	myLLMModel_mod__START__received(&context);
	myLLMModel_mod__STOP__received(&context);
	myLLMModel_mod__SHUTDOWN__received(&context);

	Common_lib__voice_msg voice_content;
	myLLMModel_mod__voice_control__received(&context, voice_content);

	myLLMModel_mod__voice_query__received(&context, voice_content);

    return 0;
}
