/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:26:45.114613    
*
* WARNING: all changes made in this file will be lost
*/


/* Fault Handler Container Skeleton for  Platform_XXX */

/* @file Platform_XXX_container.c
 * This is the Fault Handler Container for Fault Handler
 * This file is generated by the ECOA tools and shall not be modified
 */

#include <assert.h>
#include <apr_thread_proc.h>
#include "ldp_network.h"
#include "Platform_XXX_container.h"

ECOA__return_status Platform_XXX_container__recovery_action (ldp_fault_handler_context* context, 
                                                          ECOA__recovery_action_type recovery_action, 
                                                          ECOA__asset_id asset_id,
                                                          ECOA__asset_type asset_type){

    if (asset_type != ECOA__asset_type_PROTECTION_DOMAIN) {
        return ECOA__return_status_OPERATION_NOT_AVAILABLE;
    }

    ldp_Main_ctx* ctx=(ldp_Main_ctx*) context->platform_hook;
    ECOA__log log;
    int l_process_idx=-1;
    for(int i=0; i<ctx->PD_number; ++i) {
        if(ctx->pd_processes_array[i].proc.pid == asset_id) {
            l_process_idx = i;
            break;
        }
    }
    if (l_process_idx == -1) {
        return ECOA__return_status_INVALID_IDENTIFIER;
    }
    if (ctx->pd_processes_array[l_process_idx].pending_action == true) {
        return ECOA__return_status_OPERATION_ALREADY_PENDING;
    }

    ECOA__return_status retval = ECOA__return_status_OK;
    ctx->pd_processes_array[l_process_idx].pending_action = true;
    switch(recovery_action){
        case ECOA__recovery_action_type_SHUTDOWN:
            {
                // if process stopped no need to shutdown
                if (ctx->pd_processes_array[l_process_idx].state == PROCESS_RUNNING) {
                    log.current_size = snprintf ((char*)log.data, ECOA__LOG_MAXSIZE,
                                                 "[MAIN] Fault Handler RECOVERY: === Shutdown Protection Domain %s (pid=%d)",
                                                 ctx->pd_processes_array[l_process_idx].prog_names,
                                                 ctx->pd_processes_array[l_process_idx].proc.pid);
                    Platform_XXX_container__log_info(context, log);
                    write_msg(ctx->logger_PF, &ctx->interface_ctx_array[l_process_idx], LDP_ID_SHUTDOWN);
                }
            }
            break;
        case ECOA__recovery_action_type_COLD_RESTART:
            {
                if (ctx->pd_processes_array[l_process_idx].state == PROCESS_RUNNING) {
                    write_msg(ctx->logger_PF, &ctx->interface_ctx_array[l_process_idx], LDP_ID_SHUTDOWN);
                    write_msg(ctx->logger_PF, &ctx->interface_ctx_array[l_process_idx], LDP_ID_INIT_MOD);
                }else{
                    ldp_status_t ret;
                    ret=apr_proc_create(&ctx->pd_processes_array[l_process_idx].proc,
                                        ctx->pd_processes_array[l_process_idx].prog_names,
                                        (const char**)ctx->pd_processes_array[l_process_idx].prog_argv,
                                        NULL,
                                        ctx->pd_processes_array[l_process_idx].procattr,
                                        ctx->mem_pool);
                    assert( ret== APR_SUCCESS);
                    ctx->pd_processes_array[l_process_idx].state = PROCESS_RUNNING;
                }
                log.current_size = snprintf ((char*)log.data, ECOA__LOG_MAXSIZE,
                                             "[MAIN] Fault Handler RECOVERY: === Restarting process %s (pid=%d)",
                                             ctx->pd_processes_array[l_process_idx].prog_names,
                                             ctx->pd_processes_array[l_process_idx].proc.pid);
                Platform_XXX_container__log_info(context, log);
            }
            break;
        default:
            retval = ECOA__return_status_OPERATION_NOT_AVAILABLE;
            break;
    }
    ctx->pd_processes_array[l_process_idx].pending_action = false;
    return retval;
}
/* Logging services API call specifications */
void Platform_XXX_container__log_trace(ldp_fault_handler_context* context, const ECOA__log log){
   ldp_Main_ctx* ctx=(ldp_Main_ctx*) context->platform_hook;
   ldp_log_PF_log(ECOA_LOG_TRACE_PF, "TRACE", ctx->logger_PF,  log.data);
}
void Platform_XXX_container__log_debug(ldp_fault_handler_context* context, const ECOA__log log){
   ldp_Main_ctx* ctx=(ldp_Main_ctx*) context->platform_hook;
   ldp_log_PF_log(ECOA_LOG_DEBUG_PF, "DEBUG", ctx->logger_PF, log.data);
}
void Platform_XXX_container__log_info(ldp_fault_handler_context* context, const ECOA__log log){
   ldp_Main_ctx* ctx=(ldp_Main_ctx*) context->platform_hook;
   ldp_log_PF_log(ECOA_LOG_INFO_PF, "INFO", ctx->logger_PF, log.data);
}
void Platform_XXX_container__log_error(ldp_fault_handler_context* context, const ECOA__log log){
   ldp_Main_ctx* ctx=(ldp_Main_ctx*) context->platform_hook;
   ldp_log_PF_log(ECOA_LOG_ERROR_PF, "ERROR", ctx->logger_PF, log.data);
}
void Platform_XXX_container__log_warning(ldp_fault_handler_context* context, const ECOA__log log){
   ldp_Main_ctx* ctx=(ldp_Main_ctx*) context->platform_hook;
   ldp_log_PF_log(ECOA_LOG_WARN_PF, "WARNING", ctx->logger_PF, log.data);
}
