/* Generated by LDP */
/* Helpers for the Module Implementation myXXXDevice_mod */

#include "ECOA.h"
#include "myXXXDevice_mod.h"
#include "myXXXDevice_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myXXXDevice_mod__context context;

    return 0;
}
