/* Generated by LDP */
/* Tests of the Module Implementation myXXXDevice_mod */

#include "ECOA.h"
#include "myXXXDevice_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myXXXDevice_mod__context context;
	ECOA__uint32 ID;
	myXXXDevice_mod__INITIALIZE__received(&context);
	myXXXDevice_mod__START__received(&context);
	myXXXDevice_mod__STOP__received(&context);
	myXXXDevice_mod__SHUTDOWN__received(&context);

	myXXXDevice_mod__trigger_voice__received(&context);

    return 0;
}
