/* Module Test Container Implementation Skeleton for myXXXDevice_mod */

/* @file myXXXDevice_mod_test_container.c
 * This is the Module Test Container for Module myXXXDevice_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by LDP */

#include <stdlib.h>

#include "ECOA.h"
#include "myXXXDevice_mod_container.h"

#include "ECOA.h"
#include "Common_lib.h"

void myXXXDevice_mod_container__voice_control__send(myXXXDevice_mod__context* context, const Common_lib__voice_msg* voice_content)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__voice_query__send(myXXXDevice_mod__context* context, const Common_lib__voice_msg* voice_content)
{
  /* @TODO TODO - To be implemented */
}

/* Properties API */

/* Logging services API call specifications */
void myXXXDevice_mod_container__log_trace(myXXXDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__log_debug(myXXXDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__log_info(myXXXDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__log_warning(myXXXDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__raise_error(myXXXDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__raise_fatal_error(myXXXDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}


/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myXXXDevice_mod_container__get_relative_local_time(myXXXDevice_mod__context* context, ECOA__hr_time *relative_local_time)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myXXXDevice_mod_container__get_UTC_time(myXXXDevice_mod__context* context, ECOA__global_time *utc_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myXXXDevice_mod_container__get_absolute_system_time(myXXXDevice_mod__context* context, ECOA__global_time *absolute_system_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

void myXXXDevice_mod_container__get_relative_local_time_resolution(myXXXDevice_mod__context* context, ECOA__duration *relative_local_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__get_UTC_time_resolution(myXXXDevice_mod__context* context, ECOA__duration *utc_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myXXXDevice_mod_container__get_absolute_system_time_resolution(myXXXDevice_mod__context* context, ECOA__duration *absolute_system_time_resolution)
{
  /* @TODO TODO - To be implemented */
}


