/* Generated by LDP */
/* Helpers for the Module Implementation myXXXDevice_mod */

#if !defined(MYXXXDEVICE_MOD_HELPERS)
#define MYXXXDEVICE_MOD_HELPERS
#include "ECOA.h"
#include "myXXXDevice_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYXXXDEVICE_MOD;

void myXXXDevice_mod_log_info(myXXXDevice_mod__context* context, char *msg, ...);
void myXXXDevice_mod_log(myXXXDevice_mod__context* context, char *msg, ...);



#if defined(__cplusplus)
}
#endif
#endif /* MYXXXDEVICE_MOD_HELPERS */
