/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.584378    
*
* WARNING: all changes made in this file will be lost
*/


/* Module Header myYYYDevice_mod */

#if !defined(_MYYYYDEVICE_MOD_H)
#define _MYYYYDEVICE_MOD_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "ECOA.h"
#include "ECOA.h"
#include "Common_lib.h"
#include "myYYYDevice_mod_container.h"

/* Entry points for lifecycle operations */
void myYYYDevice_mod__INITIALIZE__received(myYYYDevice_mod__context* context);

void myYYYDevice_mod__START__received(myYYYDevice_mod__context* context);

void myYYYDevice_mod__STOP__received(myYYYDevice_mod__context* context);

void myYYYDevice_mod__SHUTDOWN__received(myYYYDevice_mod__context* context);

void myYYYDevice_mod__trigger_publish__received(myYYYDevice_mod__context* context);

void myYYYDevice_mod__event_data_in__updated(myYYYDevice_mod__context* context);


#if defined(__cplusplus)
} 
#endif

#endif  /* _MYYYYDEVICE_MOD_H */
