/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.584727    
*
* WARNING: all changes made in this file will be lost
*/


/* @file myYYYDevice_mod_container.h
 * This is the Module Container header for Module myYYYDevice_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

#if !defined(_MYYYYDEVICE_MOD_CONTAINER_H)
#define _MYYYYDEVICE_MOD_CONTAINER_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "ECOA.h"
#include "ECOA.h"
#include "Common_lib.h"
#include "myYYYDevice_mod_container_types.h"
#include "myYYYDevice_mod_user_context.h"

#define ECOA_VERSIONED_DATA_HANDLE_PRIVATE_SIZE 32

/* Incomplete definition of the technical (platform-dependent) part of the context
 * (it will be defined privately by the container)
 */
struct myYYYDevice_mod__platform_hook;


/* Module Context structure declaration */
typedef struct
{
  /*
   * Other container technical data will accessible through the pointer defined here
   */
  struct myYYYDevice_mod__platform_hook *platform_hook;

  /* the type myYYYDevice_mod_user_context shall be defined by the user
   * in the myYYYDevice_mod_user_context.h file to carry the module
   * implementation private data
   */
  myYYYDevice_mod_user_context user;

  /*
   * When the optional warm start context is used, the type
   * myYYYDevice_mod_warm_start_context shall be defined by the
   * user in the myYYYDevice_mod_user_context.h file to carry the module
   * implementation warm start private data and the attribute
   * myYYYDevice_mod_warm_start_context user shall be declared as follows:
   */
  myYYYDevice_mod_warm_start_context warm_start;
} myYYYDevice_mod__context;

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__get_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle);
ECOA__return_status myYYYDevice_mod_container__versioned_data_out__cancel_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle);
ECOA__return_status myYYYDevice_mod_container__versioned_data_out__publish_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle);

ECOA__return_status myYYYDevice_mod_container__event_data_in__get_read_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__event_data_in_handle* data_handle);
ECOA__return_status myYYYDevice_mod_container__event_data_in__release_read_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__event_data_in_handle* data_handle);

/* Properties API */

/* PINFO API */

/* Logging services API call specifications */
void myYYYDevice_mod_container__log_trace(myYYYDevice_mod__context* context, const ECOA__log log);
void myYYYDevice_mod_container__log_debug(myYYYDevice_mod__context* context, const ECOA__log log);
void myYYYDevice_mod_container__log_info(myYYYDevice_mod__context* context, const ECOA__log log);
void myYYYDevice_mod_container__log_warning(myYYYDevice_mod__context* context, const ECOA__log log);
void myYYYDevice_mod_container__raise_error(myYYYDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code);
void myYYYDevice_mod_container__raise_fatal_error(myYYYDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code);

/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myYYYDevice_mod_container__get_relative_local_time(myYYYDevice_mod__context* context, ECOA__hr_time *relative_local_time);
ECOA__return_status myYYYDevice_mod_container__get_UTC_time(myYYYDevice_mod__context* context, ECOA__global_time *utc_time);
ECOA__return_status myYYYDevice_mod_container__get_absolute_system_time(myYYYDevice_mod__context* context, ECOA__global_time *absolute_system_time);
void myYYYDevice_mod_container__get_relative_local_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *relative_local_time_resolution);
void myYYYDevice_mod_container__get_UTC_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *utc_time_resolution);
void myYYYDevice_mod_container__get_absolute_system_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *absolute_system_time_resolution);

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYYYYDEVICE_MOD_CONTAINER_H */
