/* Generated by LDP */
/* Tests of the Module Implementation myVoiceMgmt_mod */

#include "ECOA.h"
#include "myVoiceMgmt_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myVoiceMgmt_mod__context context;
	ECOA__uint32 ID;
	myVoiceMgmt_mod__INITIALIZE__received(&context);
	myVoiceMgmt_mod__START__received(&context);
	myVoiceMgmt_mod__STOP__received(&context);
	myVoiceMgmt_mod__SHUTDOWN__received(&context);

	ECOA__uint16 topic_id;
	Common_lib__json_text payload;
	myVoiceMgmt_mod__json_control__received(&context, topic_id, payload);

	myVoiceMgmt_mod__query_versioned_json__request_received(&context, ID);

    return 0;
}
