/* Generated by LDP */
/* Helpers for the Module Implementation myVoiceMgmt_mod */

#if !defined(MYVOICEMGMT_MOD_HELPERS)
#define MYVOICEMGMT_MOD_HELPERS
#include "ECOA.h"
#include "myVoiceMgmt_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYVOICEMGMT_MOD;

void myVoiceMgmt_mod_log_info(myVoiceMgmt_mod__context* context, char *msg, ...);
void myVoiceMgmt_mod_log(myVoiceMgmt_mod__context* context, char *msg, ...);


void myVoiceMgmt_mod__set_event_data_out(myVoiceMgmt_mod__context* context, Common_lib__event_data* data);
void myVoiceMgmt_mod__get_versioned_data_in(myVoiceMgmt_mod__context* context, Common_lib__versioned_data* data);

#if defined(__cplusplus)
}
#endif
#endif /* MYVOICEMGMT_MOD_HELPERS */
