/* Generated by LDP */
/* Helpers for the Module Implementation myVoiceMgmt_mod */

#include "ECOA.h"
#include "myVoiceMgmt_mod.h"
#include "myVoiceMgmt_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myVoiceMgmt_mod__context context;

Common_lib__event_data Common_lib__event_data_data;
myVoiceMgmt_mod__set_event_data_out(&context, &Common_lib__event_data_data);

    return 0;
}
