/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.578733    
*/

#if !defined(MYXXXDEVICE_MOD_USER_CONTEXT_HPP)
#define MYXXXDEVICE_MOD_USER_CONTEXT_HPP

/*Standaard types*/
#include <ECOA.hpp>

/*Additionnaly created types*/
#include "ECOA.hpp"
#include "Common_lib.hpp"

/*Container types*/
#include "myXXXDevice_mod_container_types.hpp"

namespace myXXXDevice_mod
{

	typedef struct
	{

	} user_context;

	//Warm start Module Context structure example
	typedef struct
	{
		/* declare the Warm Start Module Context data here */

	} warm_start_context;

} /* myXXXDevice_mod */

#endif /* MYXXXDEVICE_MOD_USER_CONTEXT_HPP */