/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.596482    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _MAIN_TOOLS_H
#define _MAIN_TOOLS_H
#include "ldp_structures.h"

static ldp_id_descriptor descriptor0={"YYY_PD","compYYYDevice","myYYYDevice_mod_inst",1};
static ldp_id_descriptor descriptor1={"YYY_PD","compYYYDevice","publish_timer",2};

static ldp_id_descriptor* descriptors_array[2] = {
                                             &descriptor0,
                                             &descriptor1,
                                            };

static ldp_id_identifier_struct my_id_identifier_val = {2, descriptors_array};

static supervision_struct supervision_tools_h = {
.ldp_id_identifier = &my_id_identifier_val,
.path_to_launcher_t = "./launcher.txt"
};

#endif /* _MAIN_TOOLS_H */

