/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.596075    
*
* WARNING: all changes made in this file will be lost
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <inttypes.h>

#include <apr.h>
#include <apr_network_io.h>
#include <apr_errno.h>
#include <apr_strings.h>
#include <apr_poll.h>
#include <apr_thread_proc.h>
#include <apr_signal.h>

#include "ldp_network.h"
#include "route.h"
#include "ldp_time_manager.h"
#include "ldp_log_platform.h"
#include "ldp_fine_grain_deployment.h"
#include "main_tools.h"
#include "Platform_YYY_fault_handler.h"

static apr_pool_t* mem_pool = NULL;
static ldp_logger_platform platform_logger;
static ldp_fault_handler_context fault_handler_context;
static ldp_Main_ctx* Main_ctx = NULL;
static ldp_process_infos PD_processes[1] = {{ .proc = {0},
                                                .prog_names = 0,
                                                .proc_exit_infos = {0}}};

void sigproc(int sig){
        char log_msg[1024];
        for (int i=0;i<Main_ctx->PD_number;i++) {
            snprintf(log_msg, sizeof(log_msg),
                     "=== Process %s (pid=%d) is dead (exitcode=%d exitwhy=KILL BY SIGNAL(%d))",
                     PD_processes[i].prog_names, PD_processes[i].proc.pid, sig, sig);
            ldp_log_PF_log(ECOA_LOG_INFO_PF, "INFO", &platform_logger, log_msg);
        }
        kill(getpid(),SIGTERM);
    }
    
void check_ended_process(int exitcode, apr_exit_why_e exitwhy, apr_proc_t p){
    for(int i=0; i<Main_ctx->PD_number; ++i) {
        if(PD_processes[i].proc.pid == p.pid) {
            PD_processes[i].proc.pid = -1;
            PD_processes[i].proc_exit_infos.pid = p.pid;
            PD_processes[i].proc_exit_infos.exitwhy = exitwhy;
            PD_processes[i].proc_exit_infos.exitcode = exitcode;
            break;
        }
    }
}

#ifdef SIGCHLD
void sigchild_handler(int sig)
{
    UNUSED(sig);
	int exitcode;
	apr_exit_why_e exitwhy;
	apr_proc_t p;
	if(apr_proc_wait_all_procs(&p, &exitcode, &exitwhy, APR_NOWAIT, mem_pool) == APR_CHILD_DONE) {
        if (exitwhy != APR_PROC_EXIT) {
 	      ECOA__asset_id    l_asset_id   = p.pid;
	      ECOA__asset_type  l_asset_type = ECOA__asset_type_PROTECTION_DOMAIN;
	      ECOA__error_type  l_error_type = ECOA__UINT32_MAX;
	      ECOA__uint32      l_error_code = 1;
          for(int i=0; i<Main_ctx->PD_number; ++i) {
            if(PD_processes[i].proc.pid == p.pid) {
               PD_processes[i].state = PROCESS_STOPPED;
               break;
            }
          }
  	      switch(exitcode){
		    case SIGSEGV:
              l_error_type = ECOA__error_type_MEMORY_VIOLATION;
              break;
		    case  SIGFPE:
              l_error_type = ECOA__error_type_NUMERICAL_ERROR;
              break;
		    case SIGILL:
              l_error_type = ECOA__error_type_ILLEGAL_INSTRUCTION;
              break;
		    case SIGBUS:
              l_error_type = ECOA__error_type_STACK_OVERFLOW;
              break;
            default:
              // signal not handled by fault handler
              check_ended_process(exitcode, exitwhy, p);
              return;
	      }
          ldp_fault_error_notification(Main_ctx, l_asset_id, l_asset_type, l_error_type, l_error_code);
        }
        check_ended_process(exitcode, exitwhy, p);
    }
	apr_signal(SIGCHLD, sigchild_handler);
}
#endif

int log_process_exit_status(void) {
	char log_msg[1024];
    int ret=0;
	for (int i=0;i<Main_ctx->PD_number;i++) {
			ldp_process_exit_infos infos = PD_processes[i].proc_exit_infos;
			if (infos.pid > 0){
					const char* strwhy = "???";
					if(infos.exitwhy==APR_PROC_SIGNAL) {
							strwhy="KILL BY SIGNAL";
							ret=-1;
					} else if(infos.exitwhy==APR_PROC_EXIT) {
							strwhy="NO ERROR";
					} else if (infos.exitwhy==(APR_PROC_SIGNAL|APR_PROC_SIGNAL_CORE)) {
							strwhy="CORE DUMP";
							ret=-1;
					}
					snprintf(log_msg, sizeof(log_msg), "=== Process %s (pid=%d) is dead (exitcode=%d exitwhy=%s(%d))",
					PD_processes[i].prog_names, infos.pid, infos.exitcode, strwhy, infos.exitwhy);
					ldp_log_PF_log(ECOA_LOG_INFO_PF, "INFO", &platform_logger, log_msg);
			}
	}
    return ret;
}


int main(void){
    supervision_struct superv_tools = supervision_tools_h;
   ldp_status_t ret;
   // logger
   platform_logger.config_filename = "log_main_PF.properties";
   ldp_log_init((ldp_logger*)(&platform_logger));
   ldp_log_PF_initialize(&platform_logger, "main_PF");
   platform_logger.pd_name = "main_PD";
   platform_logger.node_name = "main_node";
   platform_logger.level_mask=0xffff;
   char log_msg[1024];
   snprintf(log_msg, 1024,"=== main started");
   ldp_log_PF_log(ECOA_LOG_INFO_PF,"INFO", &platform_logger,log_msg);

    /* chose every cores on the node */
    /* No need tyo set affinity: every cores are enable by default */
    cpu_mask ldp_create_cpu_mask_full(void);
    log_thread_deployment_properties(&platform_logger);

	ret=apr_initialize();
	assert(ret==APR_SUCCESS);
	apr_pool_create(&mem_pool,NULL);

	apr_signal(SIGINT,sigproc);
#ifdef SIGCHLD
	apr_signal(SIGCHLD, sigchild_handler);
#endif

    ldp_Main_ctx ctx = {.mem_pool = mem_pool,
                      .PD_number = 1,
                      .logger_PF = &platform_logger,
                      .fault_handler_context = &fault_handler_context,
                      .fault_handler_function_ptr = &Platform_YYY__error_notification,
                      .fault_handler_error_id = 0,
                      .superv_tools = & superv_tools,
                      .nb_init_clients = 0,
                      .nb_ready_clients = 0,
                      .ELI_platform_ID = ELI_PF_Platform_YYY
                     };
    Main_ctx = &ctx;

	// prepare arguments for each process
	// arguments : [program name, component's name, NULL]
	for(int i=0;i<Main_ctx->PD_number;i++){
		PD_processes[i].prog_argv=calloc(2,sizeof(char*));
		PD_processes[i].prog_argv[1] = NULL;
		PD_processes[i].state = PROCESS_STOPPED;
		PD_processes[i].pending_action = false;
		ret = apr_procattr_create(&PD_processes[i].procattr, mem_pool);
		if (ret != APR_SUCCESS) {
           ldp_fault_error_notification(Main_ctx, i, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 11);
        }
		assert(ret== APR_SUCCESS);
	}

    Platform_YYY__initialize_user_context(&(ctx.fault_handler_context)->user);
    ctx.fault_handler_context->platform_hook = (struct Platform_YYY__platform_hook *)&ctx;
    ctx.pd_processes_array = (ldp_process_infos *)PD_processes;
    PD_processes[0].prog_names="./PD_YYY_PD";
    ctx.interface_ctx_array = calloc(1, sizeof(ldp_interface_ctx));
    ctx.interface_ctx_array[0].info_r= (ldp_tcp_info){YYY_PD_port,YYY_PD_addr, 1, false};
    ctx.mcast_reader_interface_num = 0; 
    ctx.mcast_sender_interface_num = 0;
    // connected platform information
    ctx.connected_platform_num = 0;


	for(int i=0;i<Main_ctx->PD_number;i++){
		PD_processes[i].prog_argv[0]=PD_processes[i].prog_names;
		ret=apr_procattr_cmdtype_set (PD_processes[i].procattr,APR_PROGRAM_ENV);
		if (ret != APR_SUCCESS) {
           ldp_fault_error_notification(Main_ctx, i, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 12);
        }
		assert( ret == APR_SUCCESS);
		ret=apr_proc_create(&PD_processes[i].proc, PD_processes[i].prog_names, (const char**)PD_processes[i].prog_argv,NULL, PD_processes[i].procattr, mem_pool);
		if (ret != APR_SUCCESS) {
           ldp_fault_error_notification(Main_ctx, i, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 13);
        }
		assert( ret== APR_SUCCESS);
		PD_processes[i].state = PROCESS_RUNNING;
		snprintf(log_msg, 1024,"=== Create process %s (pid=%d)", PD_processes[i].prog_names, PD_processes[i].proc.pid);
		ldp_log_PF_log(ECOA_LOG_INFO_PF,"INFO", &platform_logger,log_msg);
	}

    ldp_start_father_server(&ctx, ctx.interface_ctx_array, 0);
    for(int i=0; i< Main_ctx->PD_number; i++){
        if(PD_processes[i].proc.pid>0) {
            int exitcode;
            apr_exit_why_e exitwhy;
            if(apr_proc_wait(&PD_processes[i].proc, &exitcode, &exitwhy, APR_WAIT) == APR_CHILD_DONE) {
                PD_processes[i].state = PROCESS_STOPPED;
                check_ended_process(exitcode, exitwhy, PD_processes[i].proc);
            }
        }
    }
    int ret_status=log_process_exit_status();
    // clean
    ldp_log_PF_deinitialize(&platform_logger);
    for (int i=0;i<Main_ctx->PD_number;i++){
        free(PD_processes[i].prog_argv);
    }
    free(ctx.interface_ctx_array);
    apr_terminate();
    UNUSED(ret);
    return ret_status;
}

