/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.660781    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _ROUTE_H 
#define _ROUTE_H 

#define ID_INITIALIZE_event "INITIALIZE" 
#define ID_START_event "START" 
#define ID_STOP_event "STOP" 
#define MODULE_BASE_PORT (20000+0)
#define COMPONENT_BASE_PORT (MODULE_BASE_PORT + 10000)

// ELI Platform IDs
#define ELI_PF_Platform_YYY (1)

// Platform links

// local-node IP connections with master process
#define YYY_PD_addr "0.0.0.0" 
#define YYY_PD_port (COMPONENT_BASE_PORT+0) 


// local-node IP connections between PD


// wire service IDs



// module op ID

 /// YYY_PD
// myYYYDevice_mod_inst compYYYDevice
#define compYYYDevice__myYYYDevice_mod_inst__trigger_publish 200//
#define compYYYDevice__myYYYDevice_mod_inst__event_data_in 201//
// publish_timer compYYYDevice
#define compYYYDevice__publish_timer__5 202//


#endif /* _ROUTE_H */
