/* Module Test Container Implementation Skeleton for myVoiceMgmt_mod */

/* @file myVoiceMgmt_mod_test_container.c
 * This is the Module Test Container for Module myVoiceMgmt_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by LDP */

#include <stdlib.h>

#include "ECOA.h"
#include "myVoiceMgmt_mod_container.h"

#include "ECOA.h"
#include "Common_lib.h"

ECOA__return_status myVoiceMgmt_mod_container__query_versioned_json__response_send(myVoiceMgmt_mod__context* context, const ECOA__uint32 ID, Common_lib__json_text* payload)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;  return return_status;}

ECOA__return_status myVoiceMgmt_mod_container__event_data_out__get_write_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__event_data_out_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  data_handle->data = malloc(sizeof(Common_lib__event_data));
  return return_status;
}

ECOA__return_status myVoiceMgmt_mod_container__event_data_out__cancel_write_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__event_data_out_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myVoiceMgmt_mod_container__event_data_out__publish_write_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__event_data_out_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  free(data_handle->data);
  return return_status;
}


ECOA__return_status myVoiceMgmt_mod_container__versioned_data_in__get_read_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__versioned_data_in_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_INVALID_HANDLE;
  return return_status;
}

ECOA__return_status myVoiceMgmt_mod_container__versioned_data_in__release_read_access(myVoiceMgmt_mod__context* context, myVoiceMgmt_mod_container__versioned_data_in_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_INVALID_HANDLE;
  return return_status;
}


/* Properties API */

/* Logging services API call specifications */
void myVoiceMgmt_mod_container__log_trace(myVoiceMgmt_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__log_debug(myVoiceMgmt_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__log_info(myVoiceMgmt_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__log_warning(myVoiceMgmt_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__raise_error(myVoiceMgmt_mod__context* context, const ECOA__log log, const ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__raise_fatal_error(myVoiceMgmt_mod__context* context, const ECOA__log log, const ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}


/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myVoiceMgmt_mod_container__get_relative_local_time(myVoiceMgmt_mod__context* context, ECOA__hr_time *relative_local_time)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myVoiceMgmt_mod_container__get_UTC_time(myVoiceMgmt_mod__context* context, ECOA__global_time *utc_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myVoiceMgmt_mod_container__get_absolute_system_time(myVoiceMgmt_mod__context* context, ECOA__global_time *absolute_system_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

void myVoiceMgmt_mod_container__get_relative_local_time_resolution(myVoiceMgmt_mod__context* context, ECOA__duration *relative_local_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__get_UTC_time_resolution(myVoiceMgmt_mod__context* context, ECOA__duration *utc_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod_container__get_absolute_system_time_resolution(myVoiceMgmt_mod__context* context, ECOA__duration *absolute_system_time_resolution)
{
  /* @TODO TODO - To be implemented */
}


