/* Module Helpers Implementation for myVoiceMgmt_mod */

/* @file myVoiceMgmt_mod_helpers.c
 * This is the Module Test Container for Module myVoiceMgmt_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by LDP */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myVoiceMgmt_mod_container.h"
#include "myVoiceMgmt_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"


const char* MYVOICEMGMT_MOD = "MYVOICEMGMT_MOD: ";

void myVoiceMgmt_mod_log_info(myVoiceMgmt_mod__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYVOICEMGMT_MOD, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYVOICEMGMT_MOD, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myVoiceMgmt_mod_container__log_info(context, log);
}

void myVoiceMgmt_mod_log(myVoiceMgmt_mod__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYVOICEMGMT_MOD, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYVOICEMGMT_MOD, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myVoiceMgmt_mod_container__log_debug(context, log);
}



void myVoiceMgmt_mod__set_event_data_out(myVoiceMgmt_mod__context *context,
        Common_lib__event_data* data) {
    myVoiceMgmt_mod_container__event_data_out_handle handle;

    ECOA__return_status return_status;

    return_status =
            myVoiceMgmt_mod_container__event_data_out__get_write_access(
                    context, &handle);

    if (return_status == ECOA__return_status_OK
            || return_status == ECOA__return_status_DATA_NOT_INITIALIZED) {

        *(handle.data) = *data;

        return_status =
                myVoiceMgmt_mod_container__event_data_out__publish_write_access(
                        context, &handle);

        if (return_status != ECOA__return_status_OK) {
            myVoiceMgmt_mod_log(context,
                    "event_data_out: publish_write_access FAILED / error = %d", return_status);
        }
    } else {
        myVoiceMgmt_mod_log(context,
                "event_data_out: get_write_access FAILED / error = %d", return_status);
    }
}



void myVoiceMgmt_mod__get_versioned_data_in(myVoiceMgmt_mod__context* context,
        Common_lib__versioned_data* data) {
    /* assert: data != NULL */

    myVoiceMgmt_mod_container__versioned_data_in_handle handle;
    ECOA__return_status return_status = !ECOA__return_status_OK;

    return_status = myVoiceMgmt_mod_container__versioned_data_in__get_read_access(context,
            &handle);
    if (return_status == ECOA__return_status_OK) {

        *data = *(handle.data);

        return_status = myVoiceMgmt_mod_container__versioned_data_in__release_read_access(context,
                &handle);
        if (return_status != ECOA__return_status_OK) {
            myVoiceMgmt_mod_log(context, "versioned_data_in: Fail on release_read_access / error = %d",
                    return_status);
        }
    } else {
        if (return_status != ECOA__return_status_NO_DATA) {
            myVoiceMgmt_mod_log(context, "versioned_data_in: Fail on get_read_access / error = %d",
                    return_status);
        }
    }
}



