/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:21.911975    
*
* WARNING: all changes made in this file will be lost
*/


#include <ECOA.h>
#include "Common_lib.h"
#include "Common_lib_serialization.h"

int main(int argc, char **argv)
{
  return 0;
}
