################################################################################
# Copyright (c) 2025 Obeo.
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Obeo - initial API and implementation
################################################################################
CORE_PROPERTIES=Core Properties

# Step0 - Types
TYPES=Types
BASIC_TYPES=Basic Types
ECOA_PREDEFINED_TYPES=ECOA Predefined Types
LIBRARIES=Libraries

# Step1 - Services
SERVICES=Services
SERVICE_DEFINITIONS=Service Definitions

# Step2 - Component Definitions
COMPONENT_DEFINITIONS=Component Definitions
ALL_COMPONENT_DEFINITIONS=All Component Definitions

# Step3 - Initial Assembly
INITIAL_ASSEMBLY=Initial Assembly
COMPOSITE=Composite

# Step4 - Component Implementations
COMPONENT_IMPLEMENTATIONS=Component Implementations
ALL_COMPONENT_IMPLEMENTATIONS=All Component Implementations
COMPONENT_DEFINITION=Component Definition
USED_LIBRARIES=Used Libraries

# Step5 - Integration
INTEGRATION=Integration
LOGICAL_SYSTEM=Logical System
DEPLOYMENT=Deployment

# Logical Computing Node
PROTECTION_DOMAIN_LINKS=Protection Domain Links
