/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:35.728631    
*
* WARNING: all changes made in this file will be lost
*/


#include "ECOA.h"
#include "Common_lib.h"
// property struct
typedef struct myLLMModel_mod_t__properties {
} myLLMModel_mod_t__properties;

// component properties
typedef struct LLMModel__properties{
} LLMModel__properties;

