/*******************************************************/
/*                                                     */
/* @file myVoiceMgmt_mod_container_types.h             */
/* @date 2026-08-06                                    */
/* @time 02:29:27.520264                               */
/*                                                     */
/* Generated by : MSCIGT 1.1.0                         */
/*                Copyright (c) 2023 Dassault Aviation */
/*                                                     */
/* Container Types header for Module myVoiceMgmt_mod   */
/* Warning : This file shall not be modified           */
/*                                                     */
/*******************************************************/

#if !defined(MYVOICEMGMT_MOD_CONTAINER_TYPES_H)
#define MYVOICEMGMT_MOD_CONTAINER_TYPES_H

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include "Common_lib.h"

#include <ECOA.h>

#define ECOA_VERSIONED_DATA_HANDLE_PRIVATE_SIZE 32

/* The following describes the data types generated with regard to APIs:
 * For any Versioned Data Read Access: data_handle
 * For any Versioned Data Write Access: data_handle
 */

/*
 * The following is the data handle structure associated to the data operation
 * called event_data_out of data-type Common_lib:event_data
 */
typedef struct {
   /* pointer to the local copy of the data */
   Common_lib__event_data* data;
   /* stamp updated each time the data value is updated locally for that */
   /* reader */
   ECOA__uint32 stamp;
   /* technical info associated with the data (opaque for the user, reserved */
   /* for the infrastructure) */
   ECOA__byte platform_hook[ECOA_VERSIONED_DATA_HANDLE_PRIVATE_SIZE];
} myVoiceMgmt_mod_container__event_data_out_handle;

/*
 * The following is the data handle structure associated to the data operation
 * called versioned_data_in of data-type Common_lib:versioned_data
 */
typedef struct {
   /* pointer to the local copy of the data */
   Common_lib__versioned_data* data;
   /* stamp updated each time the data value is updated locally for that */
   /* reader */
   ECOA__uint32 stamp;
   /* technical info associated with the data (opaque for the user, reserved */
   /* for the infrastructure) */
   ECOA__byte platform_hook[ECOA_VERSIONED_DATA_HANDLE_PRIVATE_SIZE];
} myVoiceMgmt_mod_container__versioned_data_in_handle;

#if defined(__cplusplus)
}
#endif  /* __cplusplus */

#endif /* MYVOICEMGMT_MOD_CONTAINER_TYPES_H */
