/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.573890    
*
* WARNING: all changes made in this file will be lost
*/


/* Module Header myVoiceMgmt_mod */

#if !defined(_MYVOICEMGMT_MOD_H)
#define _MYVOICEMGMT_MOD_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "ECOA.h"
#include "ECOA.h"
#include "Common_lib.h"
#include "myVoiceMgmt_mod_container.h"

/* Entry points for lifecycle operations */
void myVoiceMgmt_mod__INITIALIZE__received(myVoiceMgmt_mod__context* context);

void myVoiceMgmt_mod__START__received(myVoiceMgmt_mod__context* context);

void myVoiceMgmt_mod__STOP__received(myVoiceMgmt_mod__context* context);

void myVoiceMgmt_mod__SHUTDOWN__received(myVoiceMgmt_mod__context* context);

void myVoiceMgmt_mod__json_control__received(myVoiceMgmt_mod__context* context, const ECOA__uint16 topic_id, const Common_lib__json_text* payload);

void myVoiceMgmt_mod__query_versioned_json__request_received(myVoiceMgmt_mod__context* context, const ECOA__uint32 ID);

void myVoiceMgmt_mod__versioned_data_in__updated(myVoiceMgmt_mod__context* context);


#if defined(__cplusplus)
} 
#endif

#endif  /* _MYVOICEMGMT_MOD_H */
