/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.316976    
*
* WARNING: all changes made in this file will be lost
*/

#include <stdio.h> 
#include <stdlib.h>  
#include <string.h> 
#include <assert.h> 

#include <apr.h>
#include <apr_thread_cond.h>
#include <apr_network_io.h>
#include <apr_time.h>
#include <apr_thread_proc.h>

#include "ldp_thread.h"
#include "ldp_structures.h"
#include "route.h"
#include "ldp_network.h"
#include "ldp_comp_util.h"
#include "ldp_trigger.h"
#include "ldp_dynamic_trigger.h"

#include "ldp_log.h"
#include "ldp_log_platform.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_mod_container_util.h"
#include "ldp_mod_lifecycle.h"
#include "ldp_fifo_manager.h"
#include "ldp_VD.h"
#include "component_mycompYYYDevice.h"
#include "component_mycompYYYDevice__properties.h"
#include "myYYYDevice_mod_container.h" 
#include "myYYYDevice_mod.h" 



 void * start_module_compYYYDevice_myYYYDevice_mod_inst(apr_thread_t* t, void* args){
   ldp_module_context* ctx = (ldp_module_context*) args;
   myYYYDevice_mod__context module_impl;
   module_impl.platform_hook = (struct myYYYDevice_mod__platform_hook*)ctx;

   ctx->mem_pool = apr_thread_pool_get(t);
   ldp_init_pinfo_manager(&ctx->pinfo_manager, ctx->logger_PF);
   ldp_init_mod_VD_managers(ctx);
   ldp_element* elt;
    bool is_running = true;
    while(is_running){
       ldp_fifo_manager_pop_elt(ctx->fifo_manager, &elt);
       switch (elt->op_ID){
       case LDP_ID_INITIALIZE_life:
           if(ctx->state == IDLE){
               myYYYDevice_mod__INITIALIZE__received(&module_impl);
                ldp_mod_lifecycle_initialize(ctx);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myYYYDevice_mod_inst]: received INIT. Invalid state");
               ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 5);
           }
           break;
       case LDP_ID_START_life:
           if(ctx->state == READY){
               ldp_mod_lifecycle_start(ctx);
               myYYYDevice_mod__START__received(&module_impl);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myYYYDevice_mod_inst]: received START. Invalid state");
               ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id,ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 6);
           }
           break;
       case LDP_ID_STOP_life:
           if(ctx->state == RUNNING){
               myYYYDevice_mod__STOP__received(&module_impl);
               ldp_mod_lifecycle_stop(ctx);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myYYYDevice_mod_inst]: received STOP. Invalid state");
           }
           break;
       case LDP_ID_SHUTDOWN_life:
           if (ctx->state == RUNNING || ctx->state == READY){
               myYYYDevice_mod__SHUTDOWN__received(&module_impl);
                ldp_mod_lifecycle_shutdown(ctx, NULL);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myYYYDevice_mod_inst]: received SHUTDOWN. Invalid state");
           }
           break;
       case LDP_ID_KILL_life:
           myYYYDevice_mod__SHUTDOWN__received(&module_impl);
           ldp_mod_lifecycle_kill(ctx, NULL);
           is_running = false;
           break;
       default:
            if(ctx->state != RUNNING){
                ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[                myYYYDevice_mod_inst] Module is not in RUNNING state. Erase msg %u",elt->op_ID);
                ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 2);
            }else if( elt->op_ID == compYYYDevice__myYYYDevice_mod_inst__trigger_publish){ //event_5:publish_timer_myYYYDevice_mod_inst_trigger_publish
                myYYYDevice_mod__trigger_publish__received(&module_impl);
            }else if( elt->op_ID == compYYYDevice__myYYYDevice_mod_inst__event_data_in){ //data_event_data:svc_event_data_myYYYDevice_mod_inst_event_data_in
                // notification
                myYYYDevice_mod__event_data_in__updated(&module_impl);
            }else{
               ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[myYYYDevice_mod_inst] unknow msg %u",elt->op_ID);assert(0);
               ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id,ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 3);
           }
		}
           ldp_fifo_manager_release_elt(ctx->fifo_manager, elt);
	}
   ldp_destroy_pinfo_manager(&ctx->pinfo_manager);
return NULL;
}


