/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:34.318858    
*
* WARNING: all changes made in this file will be lost
*/


#include "ECOA.h"
#include "Common_lib.h"
// property struct
typedef struct myXXXDevice_mod_t__properties {
} myXXXDevice_mod_t__properties;

// component properties
typedef struct XXXDevice__properties{
} XXXDevice__properties;

