/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:34.317296    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _COMPONENT_MYCOMPXXXDEVICE_HPP
#define _COMPONENT_MYCOMPXXXDEVICE_HPP

#include <apr_thread_proc.h>
#include "ldp_structures.h"

#ifdef __cplusplus
extern "C"
{
#endif

void* start_module_compXXXDevice_myXXXDevice_mod_inst(apr_thread_t* t, void* args);

extern ldp_PDomain_ctx* compXXXDevice_ctx;
ldp_PDomain_ctx* init_comp_compXXXDevice(void);

#ifdef __cplusplus
}
#endif

#endif  /* _COMPONENT_MYCOMPXXXDEVICE_HPP */