/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.059599    
*
* WARNING: all changes made in this file will be lost
*/

#include "stdbool.h"
#include "ECOA.h"
#include "LDP__ECOA_types_compare.h"
#include "ECOA.h"
#include "LDP__ECOA_types_compare.h"
#include <math.h>

bool LDP_ECOA__boolean8_compare(const ECOA__boolean8 *data1, const ECOA__boolean8 *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__int8_compare(const ECOA__int8 *data1, const ECOA__int8 *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__int16_compare(const ECOA__int16 *data1, const ECOA__int16 *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__int32_compare(const ECOA__int32 *data1, const ECOA__int32 *data2){
    return (*data1 == *data2);
}

#if defined(ECOA_64BIT_SUPPORT)
bool LDP_ECOA__int64_compare(const ECOA__int64 *data1, const ECOA__int64 *data2){
    return (*data1 == *data2);
}

#endif /* ECOA_64BIT_SUPPORT */
bool LDP_ECOA__uint8_compare(const ECOA__uint8 *data1, const ECOA__uint8 *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__uint16_compare(const ECOA__uint16 *data1, const ECOA__uint16 *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__uint32_compare(const ECOA__uint32 *data1, const ECOA__uint32 *data2){
    return (*data1 == *data2);
}

#if defined(ECOA_64BIT_SUPPORT)
bool LDP_ECOA__uint64_compare(const ECOA__uint64 *data1, const ECOA__uint64 *data2){
    return (*data1 == *data2);
}

#endif /* ECOA_64BIT_SUPPORT */
bool LDP_ECOA__char8_compare(const ECOA__char8 *data1, const ECOA__char8 *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__byte_compare(const ECOA__byte *data1, const ECOA__byte *data2){
    return (*data1 == *data2);
}

bool LDP_ECOA__float32_compare(const ECOA__float32 *data1, const ECOA__float32 *data2){
    if ((fabs(*data1) <= 0.0) || (fabs(*data2) <= 0.0)){
        return fabs(*data1 - *data2) <= 0.0;
    }else{
        return (fabs(*data1 - *data2) <= 0.0 * fabs(*data1));
    }
}

#if defined(ECOA_64BIT_SUPPORT)
bool LDP_ECOA__double64_compare(const ECOA__double64 *data1, const ECOA__double64 *data2){
    if ((fabs(*data1) <= 0.0) || (fabs(*data2) <= 0.0)){
        return fabs(*data1 - *data2) <= 0.0;
    }else{
        return (fabs(*data1 - *data2) <= 0.0 * fabs(*data1));
    }
}

#endif /* ECOA_64BIT_SUPPORT */
bool LDP_ECOA__duration_compare(const ECOA__duration *data1, const ECOA__duration *data2){
    if(data1->seconds != data2->seconds)
        {
                return false;
        }
    if(data1->nanoseconds != data2->nanoseconds)
        {
                return false;
        }
    return true;
}

bool LDP_ECOA__global_time_compare(const ECOA__global_time *data1, const ECOA__global_time *data2){
    if(data1->seconds != data2->seconds)
        {
                return false;
        }
    if(data1->nanoseconds != data2->nanoseconds)
        {
                return false;
        }
    return true;
}

bool LDP_ECOA__hr_time_compare(const ECOA__hr_time *data1, const ECOA__hr_time *data2){
    if(data1->seconds != data2->seconds)
        {
                return false;
        }
    if(data1->nanoseconds != data2->nanoseconds)
        {
                return false;
        }
    return true;
}

bool LDP_ECOA__pinfo_filename_compare(const ECOA__pinfo_filename *data1, const ECOA__pinfo_filename *data2){
    bool retvalue = true;
    unsigned int i = 0;
    if(data1->current_size != data2->current_size){
        return false;
    }

    for (i=0; i<data1->current_size; i++){
        if(data1->data[i] != data2->data[i])
        {
            retvalue = false;
            break;
        }
    }
    return retvalue;
}

bool LDP_ECOA__log_compare(const ECOA__log *data1, const ECOA__log *data2){
    bool retvalue = true;
    unsigned int i = 0;
    if(data1->current_size != data2->current_size){
        return false;
    }

    for (i=0; i<data1->current_size; i++){
        if(data1->data[i] != data2->data[i])
        {
            retvalue = false;
            break;
        }
    }
    return retvalue;
}


