/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.060871    
*
* WARNING: all changes made in this file will be lost
*/

#include "stdbool.h"
#include "ECOA.h"
#include "LDP__ECOA_types_compare.h"
#include "Common_lib.h"
#include "LDP__Common_lib_types_compare.h"
#include <math.h>

bool LDP_Common_lib__event_data_compare(const Common_lib__event_data *data1, const Common_lib__event_data *data2){
    if(data1->topic_id != data2->topic_id)
        {
                return false;
        }
    if(data1->status_word_0 != data2->status_word_0)
        {
                return false;
        }
    if(data1->status_word_1 != data2->status_word_1)
        {
                return false;
        }
    if(data1->status_word_2 != data2->status_word_2)
        {
                return false;
        }
    if(data1->status_word_3 != data2->status_word_3)
        {
                return false;
        }
    if(data1->status_word_4 != data2->status_word_4)
        {
                return false;
        }
    if(data1->status_word_5 != data2->status_word_5)
        {
                return false;
        }
    if(data1->status_word_6 != data2->status_word_6)
        {
                return false;
        }
    if(data1->status_word_7 != data2->status_word_7)
        {
                return false;
        }
    if(data1->flag_0 != data2->flag_0)
        {
                return false;
        }
    if(data1->flag_1 != data2->flag_1)
        {
                return false;
        }
    if(data1->flag_2 != data2->flag_2)
        {
                return false;
        }
    if(data1->flag_3 != data2->flag_3)
        {
                return false;
        }
    return true;
}

bool LDP_Common_lib__versioned_data_compare(const Common_lib__versioned_data *data1, const Common_lib__versioned_data *data2){
    if(data1->version != data2->version)
        {
                return false;
        }
    if(data1->sample_0 != data2->sample_0)
        {
                return false;
        }
    if(data1->sample_1 != data2->sample_1)
        {
                return false;
        }
    if(data1->sample_2 != data2->sample_2)
        {
                return false;
        }
    if(data1->sample_3 != data2->sample_3)
        {
                return false;
        }
    if(data1->channel_0 != data2->channel_0)
        {
                return false;
        }
    if(data1->channel_1 != data2->channel_1)
        {
                return false;
        }
    if(data1->channel_2 != data2->channel_2)
        {
                return false;
        }
    if(data1->channel_3 != data2->channel_3)
        {
                return false;
        }
    if(data1->channel_4 != data2->channel_4)
        {
                return false;
        }
    if(data1->channel_5 != data2->channel_5)
        {
                return false;
        }
    if(data1->channel_6 != data2->channel_6)
        {
                return false;
        }
    if(data1->channel_7 != data2->channel_7)
        {
                return false;
        }
    if(data1->channel_8 != data2->channel_8)
        {
                return false;
        }
    return true;
}

bool LDP_Common_lib__json_text_compare(const Common_lib__json_text *data1, const Common_lib__json_text *data2){
    bool retvalue = true;
    unsigned int i = 0;
    if(data1->current_size != data2->current_size){
        return false;
    }

    for (i=0; i<data1->current_size; i++){
        if(data1->data[i] != data2->data[i])
        {
            retvalue = false;
            break;
        }
    }
    return retvalue;
}

bool LDP_Common_lib__voice_msg_compare(const Common_lib__voice_msg *data1, const Common_lib__voice_msg *data2){
    bool retvalue = true;
    unsigned int i = 0;
    if(data1->current_size != data2->current_size){
        return false;
    }

    for (i=0; i<data1->current_size; i++){
        if(data1->data[i] != data2->data[i])
        {
            retvalue = false;
            break;
        }
    }
    return retvalue;
}


