/* Generated by LDP */
/* Tests of the Module Implementation myYYYDevice_mod */

#include "ECOA.h"
#include "myYYYDevice_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myYYYDevice_mod__context context;
	ECOA__uint32 ID;
	myYYYDevice_mod__INITIALIZE__received(&context);
	myYYYDevice_mod__START__received(&context);
	myYYYDevice_mod__STOP__received(&context);
	myYYYDevice_mod__SHUTDOWN__received(&context);

	myYYYDevice_mod__trigger_publish__received(&context);

    return 0;
}
