/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.572785    
*/


/* Module Implementation myVoiceMgmt_mod */

#include "ECOA.h"
#include "myVoiceMgmt_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

/* Entry points for lifecycle operations */
void myVoiceMgmt_mod__INITIALIZE__received(myVoiceMgmt_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod__START__received(myVoiceMgmt_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod__STOP__received(myVoiceMgmt_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod__SHUTDOWN__received(myVoiceMgmt_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod__json_control__received(myVoiceMgmt_mod__context* context, const ECOA__uint16 topic_id, const Common_lib__json_text* payload)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod__query_versioned_json__request_received(myVoiceMgmt_mod__context* context, const ECOA__uint32 ID)
{
  /* @TODO TODO - To be implemented */
}

void myVoiceMgmt_mod__versioned_data_in__updated(myVoiceMgmt_mod__context* context){
  /* @TODO TODO - To be implemented */
}

