/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.596902    
*
* WARNING: all changes made in this file will be lost
*/


/* @file Platform_YYY_container.h
 * This is the Fault Handler Container header for Fault Handler
 * This file is generated by the ECOA tools and shall not be modified
 */

#if !defined(_PLATFORM_YYY_CONTAINER_H)
#define _PLATFORM_YYY_CONTAINER_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "ldp_time_manager.h"
#include "ECOA.h"
#include "Platform_YYY_user_context.h"

/* Incomplete definition of the technical (platform-dependent) part of the context
 * (it will be defined privately by the container)
 */
struct Platform_YYY__platform_hook;


/*
 * Fault Handler Context structure declaration
 */
typedef struct ldp_fault_handler_context_t
{
  /*
   * Other container technical data will accessible through the pointer defined here
   */
  struct Platform_YYY__platform_hook *platform_hook;

  /* the type Platform_YYY_user_context shall be defined by the user
   * in the Platform_YYY_user_context.h file to carry the module
   * implementation private data
   */
  Platform_YYY_user_context user;

} ldp_fault_handler_context;

ECOA__return_status Platform_YYY_container__recovery_action (ldp_fault_handler_context* context, 
                                                          ECOA__recovery_action_type recovery_action, 
                                                          ECOA__asset_id asset_id,
                                                          ECOA__asset_type asset_type);

/* Logging services API call specifications */
void Platform_YYY_container__log_trace(ldp_fault_handler_context* context, const ECOA__log log);
void Platform_YYY_container__log_debug(ldp_fault_handler_context* context, const ECOA__log log);
void Platform_YYY_container__log_info(ldp_fault_handler_context* context, const ECOA__log log);
void Platform_YYY_container__log_error(ldp_fault_handler_context* context, const ECOA__log log);
void Platform_YYY_container__log_warning(ldp_fault_handler_context* context, const ECOA__log log);

#if defined(__cplusplus)
} 
#endif

#endif  /* _PLATFORM_YYY_CONTAINER_H */
