/**
* @file LDP_myXXXDevice_mod.h
* @brief This is the header of the DA encapsulation library for ECOA
*\n\
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* This file is generated by the DA ECOA tools and shall not be modified
*/

#if !defined(_LDP_myXXXDevice_mod_H)
#define _LDP_myXXXDevice_mod_H
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include "myXXXDevice_mod_container.h"


/* User tool functions */
/******************************************************************************/
void LDP_myXXXDevice_mod__concat(myXXXDevice_mod__context *context,ECOA__log *log, char *str);

/******************************************************************************/

/* Request/Response API */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/* Versioned data */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/* Event */
/******************************************************************************/
void LDP_myXXXDevice_mod__send__voice_control(
        myXXXDevice_mod__context *context , const Common_lib__voice_msg* voice_content);
void LDP_myXXXDevice_mod__send__voice_query(
        myXXXDevice_mod__context *context , const Common_lib__voice_msg* voice_content);

/******************************************************************************/

/* Property */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/
/* log API */
void LDP_myXXXDevice_mod__log_trace(
      myXXXDevice_mod__context *context,
      char *log);
void LDP_myXXXDevice_mod__log_debug(
      myXXXDevice_mod__context *context,
      char *log);
void LDP_myXXXDevice_mod__log_info(
      myXXXDevice_mod__context *context,
      char *log);
void LDP_myXXXDevice_mod__log_warning(
      myXXXDevice_mod__context *context,
      char *log);
void LDP_myXXXDevice_mod__raise_error(
      myXXXDevice_mod__context *context,
      char *log,
      const ECOA__error_code error_code);
void LDP_myXXXDevice_mod__raise_fatal_error(
      myXXXDevice_mod__context *context,
      char *log,
      const ECOA__error_code error_code);

/* Time API */
ECOA__return_status LDP_myXXXDevice_mod__get_relative_local_time(
        myXXXDevice_mod__context *context,
        ECOA__hr_time *relative_local_time);
ECOA__return_status LDP_myXXXDevice_mod__get_UTC_time(
        myXXXDevice_mod__context *context,
        ECOA__global_time *utc_time);
ECOA__return_status LDP_myXXXDevice_mod__get_absolute_system_time(
        myXXXDevice_mod__context *context,
        ECOA__global_time *absolute_system_time);
ECOA__return_status LDP_myXXXDevice_mod__get_relative_local_time_resolution(
        myXXXDevice_mod__context *context,
        ECOA__duration *relative_local_time_resolution);
ECOA__return_status LDP_myXXXDevice_mod__get_UTC_time_resolution(
        myXXXDevice_mod__context *context,
        ECOA__duration *utc_time_resolution);
ECOA__return_status LDP_myXXXDevice_mod__get_absolute_system_time_resolution(
        myXXXDevice_mod__context *context,
        ECOA__duration *absolute_system_time_resolution);
/******************************************************************************/

/* PINFO API */
/******************************************************************************/

/******************************************************************************/


#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _LDP_myXXXDevice_mod_H */

