/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.579022    
*
* WARNING: all changes made in this file will be lost
*/

/**
* @file myXXXDevice_mod.hpp
* @brief Module Header for myXXXDevice_mod
*
*/

#if !defined(_myXXXDevice_mod_HPP)
#define _myXXXDevice_mod_HPP


#include "ECOA.hpp"
#include "myXXXDevice_mod_container.hpp"
#include "myXXXDevice_mod_container_types.hpp"
#include "myXXXDevice_mod_user_context.hpp"
#include "ECOA.hpp"
#include "Common_lib.hpp"

namespace myXXXDevice_mod
{

class Module
{
	public:

		/* Entry points for lifecycle operations */

		void INITIALIZE__received();

		void START__received();

		void STOP__received();

		void SHUTDOWN__received();

		warm_start_context warm_start;

		void trigger_voice__received();

		Container* container;

		user_context user;

}; /* Class Module */

extern "C" {
	Module* myXXXDevice_mod__new_instance();
}

} /* namespace myXXXDevice_mod */

#endif  /* _MYXXXDEVICE_MOD_HPP */