/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:26:45.115435    
*/


/* Fault Handler Header for Platform_XXX */
#if !defined(_PLATFORM_XXX_H)
#define _PLATFORM_XXX_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "Platform_XXX_container.h"

void Platform_XXX__initialize_user_context(Platform_XXX_user_context * context);

void Platform_XXX__error_notification (
  ldp_fault_handler_context* context, 
  ECOA__error_id error_id,
  ECOA__global_time timestamp,
  ECOA__asset_id asset_id,
  ECOA__asset_type asset_type,
  ECOA__error_type error_type,
  ECOA__error_code error_code);

#if defined(__cplusplus)
} 
#endif

#endif  /* _PLATFORM_XXX_H */
