/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:34.309133    
*
* WARNING: all changes made in this file will be lost
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include <apr.h>
#include <apr_thread_cond.h>
#include <apr_network_io.h>
#include <apr_time.h>
#include <apr_thread_proc.h>

#include "ldp_thread.h"
#include "ldp_structures.h"
#include "route.h"
#include "ldp_network.h"
#include "ldp_comp_util.h"
#include "ldp_trigger.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_log.h"
#include "ldp_log_platform.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_mod_container_util.h"
#include "ldp_mod_lifecycle.h"
#include "ldp_fifo_manager.h"
#include "ldp_VD.h"

#include "component_mycompLLMModel.hpp"
#include "component_mycompLLMModel__properties.h"

#include "myLLMModel_mod_container.hpp"
#include "myLLMModel_mod.hpp"

#include "ECOA.hpp"
#include "ECOA.h"
#include "Common_lib.hpp"
#include "Common_lib.h"


void* start_module_compLLMModel_myLLMModel_mod_inst(apr_thread_t* t, void* args){

    ldp_module_context* ctx = (ldp_module_context*) args;
    myLLMModel_mod::Container* mod_c = new myLLMModel_mod::Container((myLLMModel_mod::Container::platform_hook*)ctx);
    myLLMModel_mod::Module* module_impl = new myLLMModel_mod::Module();
    module_impl->container = mod_c;

    ctx->mem_pool = apr_thread_pool_get(t);
    ldp_init_pinfo_manager(&ctx->pinfo_manager, ctx->logger_PF);
    //init_mod_VD_manager(ctx->VD_manager);
    apr_thread_t* RR_dyn_trigger_thread;
    ldp_mod_start_RR_trigger( ctx, &RR_dyn_trigger_thread);
    ldp_element* elt;

    bool is_running = true;
    while(is_running){
        ldp_fifo_manager_pop_elt(ctx->fifo_manager, &elt);

        switch (elt->op_ID){
            case LDP_ID_INITIALIZE_life:
                if(ctx->state == IDLE){
                    module_impl->myLLMModel_mod::Module::INITIALIZE__received();
                    ldp_mod_lifecycle_initialize(ctx);
                }
                else{
                    ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myLLMModel_mod_inst]: received INIT. Invalid state");
                }
                break;
            case LDP_ID_START_life:
                if(ctx->state == READY){
                   ldp_mod_lifecycle_start(ctx);
                    module_impl->myLLMModel_mod::Module::START__received();
                }
                else{
                   ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myLLMModel_mod_inst]: received START. Invalid state");
                }
                break;
            case LDP_ID_STOP_life:
               if(ctx->state == RUNNING){
                    module_impl->myLLMModel_mod::Module::STOP__received();
                   ldp_mod_lifecycle_stop(ctx);
                }
                else{
                   ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myLLMModel_mod_inst]: received STOP. Invalid state");
                }
                break;
            case LDP_ID_SHUTDOWN_life:
                if (ctx->state == RUNNING || ctx->state == READY){
                    module_impl->myLLMModel_mod::Module::SHUTDOWN__received();
                    ldp_mod_lifecycle_shutdown(ctx, RR_dyn_trigger_thread);
                }
                else{
                    ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myLLMModel_mod_inst]: received SHUTDOWN. Invalid state");
                }
                break;
            case LDP_ID_KILL_life:
                module_impl->myLLMModel_mod::Module::SHUTDOWN__received();
                ldp_mod_lifecycle_kill(ctx, RR_dyn_trigger_thread);
                is_running = false;
                break;
            default:
                if(ctx->state != RUNNING){
                    ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 2);
                    ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[myLLMModel_mod_inst] Module is not in RUNNING state. Erase msg %u",elt->op_ID);
                }

                else if( elt->op_ID == compLLMModel__myLLMModel_mod_inst__voice_control){
                    Common_lib::voice_msg* voice_content = ((Common_lib::voice_msg*) &elt->parameters[0]);
                    module_impl->myLLMModel_mod::Module::voice_control__received( *voice_content);
                }

                else if( elt->op_ID == compLLMModel__myLLMModel_mod_inst__voice_query){
                    Common_lib::voice_msg* voice_content = ((Common_lib::voice_msg*) &elt->parameters[0]);
                    module_impl->myLLMModel_mod::Module::voice_query__received( *voice_content);
                }

                else if( elt->op_ID == compLLMModel__myLLMModel_mod_inst__query_versioned_json){
                    ECOA::uint32 ID;
                    memcpy(&ID, &elt->parameters[0],sizeof(ECOA::uint32));
                    ctx->req_resp.current_RR_number[0]--;
                    Common_lib::json_text* payload = ((Common_lib::json_text*) &elt->parameters[sizeof(ECOA__uint32)]);


                    if(ID != ECOA::UINT32_MAX){
                        ldp_node* node;
                        if(ldp_find_req_sent(&ctx->req_resp,ID, &node) != NULL){
                           ldp_free_req_sent(&ctx->req_resp,node);
                           ECOA::return_status retOk = ECOA::return_status::OK;
                           module_impl->myLLMModel_mod::Module::query_versioned_json__response_received(ID,retOk,*payload);
                        }
                        else{
                            ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF, "In comp mycompLLMModel and module myLLMModel_mod_inst: sent RR not found");
                            ID = ECOA::UINT32_MAX;
                        }
                    }

                    if(ID == ECOA::UINT32_MAX){
                        memset(payload, 0, sizeof(Common_lib::json_text));
                        ECOA::return_status retNoResponse = ECOA::return_status::NO_RESPONSE;
                        module_impl->myLLMModel_mod::Module::query_versioned_json__response_received(ID,retNoResponse,*payload);
                    }
                }
                else{
                    ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 3);
                    ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[myLLMModel_mod_inst] unknow msg %u",elt->op_ID);
                }
        }
        ldp_fifo_manager_release_elt(ctx->fifo_manager, elt);
    }

    ldp_destroy_pinfo_manager(&ctx->pinfo_manager);
    //destroy_mod_VD_manager(&ctx->VD_manager);
    delete module_impl;
    delete mod_c;
    return NULL;

}
 
  extern "C" 

{
}
