/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.597241    
*/


/* Fault Handler Header for Platform_YYY */
#if !defined(_PLATFORM_YYY_H)
#define _PLATFORM_YYY_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "Platform_YYY_container.h"

void Platform_YYY__initialize_user_context(Platform_YYY_user_context * context);

void Platform_YYY__error_notification (
  ldp_fault_handler_context* context, 
  ECOA__error_id error_id,
  ECOA__global_time timestamp,
  ECOA__asset_id asset_id,
  ECOA__asset_type asset_type,
  ECOA__error_type error_type,
  ECOA__error_code error_code);

#if defined(__cplusplus)
} 
#endif

#endif  /* _PLATFORM_YYY_H */
