/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.597366    
*/


/* Fault Handler User Context Header for Platform_YYY */
#if !defined(PLATFORM_YYY_USER_CONTEXT_H)
#define PLATFORM_YYY_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/*
 * @file PLATFORM_YYY_user_context.h
 */
/* Fault Handler User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    /*********** START USER-WRITTEN USER ***********/
} Platform_YYY_user_context;

#if defined(__cplusplus)
} 
#endif /* __cplusplus */

#endif  /* PLATFORM_YYY_USER_CONTEXT_H */
