/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.319944    
*
* WARNING: all changes made in this file will be lost
*/

#include "ldp_fine_grain_deployment.h" // Need to be first to define _GNU_SOURCE
#include <stdio.h>
#include <inttypes.h>
#include <assert.h>
#include <apr.h>
#include <apr_time.h>
#include "ldp_thread.h"
#include "ldp_structures.h"

#include "ldp_log.h"
#include "route.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_trigger.h"
#include "ldp_comp_util.h"
#include "ldp_network.h"
#include "ldp_mod_container_util.h"
#include "ldp_ELI_udp.h"
#include "ldp_fifo_manager.h"
#include "svc_svc_event_data_deserial.h"
#include "svc_svc_json_cmd_deserial.h"
#include "svc_svc_vd_query_deserial.h"
#include "svc_svc_versioned_data_deserial.h"
#include "svc_svc_voice_msg_deserial.h"
#include "component_mycompLLMModel.hpp"
#include "component_mycompLLMModel__properties.h"
ldp_PDomain_ctx* compLLMModel_ctx = NULL;
static void router_socket_msg_LLMModel_PD(ldp_PDomain_ctx* ctx, uint32_t operation_id, char* params,
                                        int params_size, ldp_interface_ctx* socket_sender, int port_nb, uint32_t ELI_sequence_num, ECOA__uint32 sender_PF_ID){

    uint32_t mod_op_id = 0;
    //char* msg_buffer = params;
    
    if (port_nb == ctx->interface_ctx_array[ctx->nb_client + 2].info_r.port){
        switch (operation_id){
        case compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query__query_versioned_json:{
            // response of RR query_versioned_json
            mod_op_id = compLLMModel__myLLMModel_mod_inst__query_versioned_json;
            memcpy(&ELI_sequence_num, params, sizeof(ECOA__uint32));
            ldp_comp_received_answer_request(ctx,
                                               &params[sizeof(ECOA__uint32)], // only parameters + ID
                                               params_size - sizeof(ECOA__uint32),// parameters : without ELI_sequence_num
                                               ELI_sequence_num, mod_op_id);
            break;
        }
        default:
            ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,
            "[PD %s] wrong operation ID %i on port number %i, from PF id %i",
             ctx->name, operation_id, port_nb, sender_PF_ID);
        }
    }else if ((port_nb == link_XXX_to_EW_read_port) && (
      (sender_PF_ID == link_XXX_to_EW_read_PF_ID) )){
        switch (operation_id){
        // ========= link : link_XXX_to_EW
        // input operations for syntax svc_voice_msg
            case compXXXDevice_svc_voice_msg__compLLMModel_svc_voice_msg__voice_control:
            // wire compXXXDevice_svc_voice_msg__compLLMModel_svc_voice_msg
        {
            // need to write parameters as a local TCP message
            params_size = deserialized_svc_voice_msg_voice_control(ctx->msg_buffer, params);
            mod_op_id = compLLMModel__myLLMModel_mod_inst__voice_control;
            // event for module myLLMModel_mod_inst
            ldp_comp_received_event(ctx, false, ctx->msg_buffer, params_size,
                                      &ctx->worker_context[0], 1, true, mod_op_id);
            break;
        }
            case compXXXDevice_svc_voice_msg__compLLMModel_svc_voice_msg__voice_query:
            // wire compXXXDevice_svc_voice_msg__compLLMModel_svc_voice_msg
        {
            // need to write parameters as a local TCP message
            params_size = deserialized_svc_voice_msg_voice_query(ctx->msg_buffer, params);
            mod_op_id = compLLMModel__myLLMModel_mod_inst__voice_query;
            // event for module myLLMModel_mod_inst
            ldp_comp_received_event(ctx, false, ctx->msg_buffer, params_size,
                                      &ctx->worker_context[0], 2, true, mod_op_id);
            break;
        }
        default:
            ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,
            "[PD %s] wrong operation ID %i on port number %i, from PF id %i",
             ctx->name, operation_id, port_nb, sender_PF_ID);
        }
    }else     {
        ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,
                            "[PD %s] wrong port number %i, op: %i, PF id: %i",
                            ctx->name, port_nb, operation_id, sender_PF_ID);
    }

    UNUSED(mod_op_id);
    UNUSED(params);
    UNUSED(params_size);
    UNUSED(socket_sender);
}

static int LLMModel_PD_compute_buffer_size(void){
int size_of_buffer = -1;
int tmp;
tmp = 12+sizeof(Common_lib__json_text);
size_of_buffer = ( tmp < size_of_buffer ) ? size_of_buffer : tmp;
tmp = sizeof(Common_lib__voice_msg);
size_of_buffer = ( tmp < size_of_buffer ) ? size_of_buffer : tmp;
tmp = sizeof(ECOA__uint16)+sizeof(Common_lib__json_text);
size_of_buffer = ( tmp < size_of_buffer ) ? size_of_buffer : tmp;

   return size_of_buffer+LDP_ELI_HEADER_SIZE+28;
}

int main(void){
    apr_initialize();
    apr_pool_t* mem_pool;
    apr_pool_create(&mem_pool,NULL);

    /// Initialisation of protection domain context LLMModel_PD
    ldp_status_t ret;
    ldp_PDomain_ctx* ctx = malloc(sizeof(ldp_PDomain_ctx));
    compLLMModel_ctx = ctx;
    ctx->name = "LLMModel_PD"; 
    ctx->mem_pool = mem_pool;
    ctx->route_function_ptr = &router_socket_msg_LLMModel_PD;
    ctx->sched_policy = LDP_SCHED_OTHER;
    ctx->ELI_platform_ID = ELI_PF_Platform_EW;
    // loggers
    ctx->logger = malloc(sizeof(ldp_logger));
    ctx->logger->config_filename = "log_LLMModel_PD.properties";
    ldp_log_init(ctx->logger);
    ldp_log_initialize(ctx->logger,ctx->name);

    ctx->logger_PF = malloc(sizeof(ldp_logger_platform));
    ctx->logger_PF->config_filename = "log_LLMModel_PD_PF.properties";
    ldp_log_PF_initialize(ctx->logger_PF,"LLMModel_PD_PF");
    ctx->logger_PF->pd_name = "LLMModel_PD";
    ctx->logger_PF->node_name = "_";
    ctx->logger_PF->level_mask=0xffff;

    // technical thread affinity
    /* chose every cores on the node */
    /* No need tyo set affinity: every cores are enable by default */
    ctx->technical_cpu_mask = ldp_create_cpu_mask_full();
    log_thread_deployment_properties(ctx->logger_PF);


    ctx->msg_buffer_size = LLMModel_PD_compute_buffer_size();
    ctx->nb_client = 0; 
    ctx->nb_server = 4; 
    ctx->interface_ctx_array = calloc(ctx->nb_client+ctx->nb_server, sizeof(ldp_interface_ctx));
    ctx->interface_ctx_array[0].type = LDP_LOCAL_IP;
    ctx->interface_ctx_array[0].info_r = (ldp_tcp_info) {LLMModel_PD_port, LLMModel_PD_addr, 1, true}; // socket with main process. Does not match with a wire
    ctx->interface_ctx_array[ctx->nb_client+1].type = LDP_LOCAL_IP;
    ctx->interface_ctx_array[ctx->nb_client+1].info_r = (ldp_tcp_info) {compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd_port,
                                            compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd_addr,
                                            1, true};
    ctx->interface_ctx_array[ctx->nb_client+2].type = LDP_LOCAL_IP;
    ctx->interface_ctx_array[ctx->nb_client+2].info_r = (ldp_tcp_info) {compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query_port,
                                            compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query_addr,
                                            1, true};
    ctx->interface_ctx_array[ctx->nb_client+3].type = LDP_ELI_MCAST;
    ctx->interface_ctx_array[ctx->nb_client+3].info_r = (ldp_tcp_info) {link_XXX_to_EW_sent_port,
                                            link_XXX_to_EW_sent_addr,
                                            0, false};
    ctx->interface_ctx_array[ctx->nb_client+3].inter.mcast.UDP_current_PF_ID = link_XXX_to_EW_sent_PF_ID;
    ctx->interface_ctx_array[ctx->nb_client+3].inter.mcast.link_num = 1;
    ctx->interface_ctx_array[ctx->nb_client+3].inter.mcast.PF_links_ctx = calloc(1, sizeof(ldp_PF_link));
    ctx->interface_ctx_array[ctx->nb_client+3].inter.mcast.PF_links_ctx[0] = (ldp_PF_link){
        {ELI_PF_Platform_XXX, link_XXX_to_EW_read_PF_ID, 1, 0,
        (ldp_ELI_UDP_channel[1]){}},NULL};
    ctx->mcast_read_interface_num = 1; 
    ctx->mcast_read_interface = calloc(1, sizeof(ldp_interface_ctx));
    ctx->mcast_read_interface[0].type = LDP_ELI_MCAST;
    ctx->mcast_read_interface[0].info_r = (ldp_tcp_info) {link_XXX_to_EW_read_port,
                                            link_XXX_to_EW_read_addr,
                                            0, false};
    ctx->mcast_read_interface[0].inter.mcast.link_num = 1;
    ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx = calloc(1, sizeof(ldp_PF_link));
    ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx[0] = (ldp_PF_link){
        {ELI_PF_Platform_XXX, link_XXX_to_EW_read_PF_ID, 256, 0, NULL},
        &ctx->interface_ctx_array[ctx->nb_client+3]};
    ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx[0].link_ctx.buffer_size = min_buffer_size_svc_voice_msg();
    ldp_initialized_PF_link(&ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx[0].link_ctx);

    //init module instances context 
    ctx->nb_module = 1;
    apr_threadattr_t* mod_attr[ctx->nb_module];
    apr_thread_t* mod_thread[ctx->nb_module];
    ctx->worker_context = calloc(ctx->nb_module, sizeof(ldp_module_context));

    //init trigger instances context 
    ctx->nb_trigger = 0;

    //init dynamic trigger instances context 
    ctx->nb_dyn_trigger = 0;
    ctx->num_VD_repo = 0;
    ctx->VD_repo_array = NULL;


    // context for module myLLMModel_mod_inst
    ctx->worker_context[0].name = "myLLMModel_mod_inst";
    ctx->worker_context[0].mod_id = 7;
    ctx->worker_context[0].network_write_data = malloc(sizeof(net_data_w));
    ctx->worker_context[0].network_write_data->module_id = 5;
    ctx->worker_context[0].network_write_data->msg_id = 100;
    ctx->worker_context[0].component_name = "compLLMModel";
    ctx->worker_context[0].mem_pool = mem_pool;
    ctx->worker_context[0].state = IDLE;
    ctx->worker_context[0].msg_buffer_size = LLMModel_PD_compute_buffer_size();
    ctx->worker_context[0].msg_buffer = NULL;
    ctx->worker_context[0].component_ctx = ctx ;
    ctx->worker_context[0].logger_PF = ctx->logger_PF ;
    ctx->worker_context[0].priority = 1;// ??
    // CPU mask
    ctx->worker_context[0].cpu_affinity_mask = ldp_create_cpu_mask_full();
    ctx->worker_context[0].logger = malloc(sizeof(ldp_logger));
    *(    ctx->worker_context[0].logger) = (ldp_logger) {
       ctx->logger->initializer,
       ctx->logger->config_filename,
       ctx->logger->name,
       "compLLMModel",
       "myLLMModel_mod_inst",
ECOA_LOG_FATAL|ECOA_LOG_ERROR|ECOA_LOG_DEBUG|ECOA_LOG_WARN|ECOA_LOG_INFO|ECOA_LOG_TRACE   };

    // Fifo manager
    ctx->worker_context[0].fifo_manager = malloc(sizeof(ldp_fifo_manager));
    ctx->worker_context[0].fifo_manager->fifo = malloc(sizeof(ldp_fifo));
    ctx->worker_context[0].fifo_manager->fifo->size = 28;
    ctx->worker_context[0].fifo_manager->op_pool_num = 4;
    ctx->worker_context[0].fifo_manager->op_element_pools = calloc(4, sizeof(ldp_element_pool));
    ctx->worker_context[0].fifo_manager->op_element_pools[0].element_num = 8; // lifecycle operations
    ctx->worker_context[0].fifo_manager->op_element_pools[0].parameter_size = 0; // no parameters
    ctx->worker_context[0].fifo_manager->op_element_pools[1].element_num = 8; // voice_control
    ctx->worker_context[0].fifo_manager->op_element_pools[1].parameter_size = sizeof(Common_lib__voice_msg);
    ctx->worker_context[0].fifo_manager->op_element_pools[2].element_num = 8; // voice_query
    ctx->worker_context[0].fifo_manager->op_element_pools[2].parameter_size = sizeof(Common_lib__voice_msg);
    ctx->worker_context[0].fifo_manager->op_element_pools[3].element_num = 8; // query_versioned_json
    ctx->worker_context[0].fifo_manager->op_element_pools[3].parameter_size = 2*sizeof(ECOA__uint32)+sizeof(Common_lib__json_text);
    // Pinfo manager
    ctx->worker_context[0].pinfo_manager.pinfo_num = 0;
    ctx->worker_context[0].num_reader_mng = 0; 
    ctx->worker_context[0].num_writter_mng = 0;
    ctx->worker_context[0].VD_reader_managers = NULL;
    ctx->worker_context[0].VD_writter_managers = NULL;

    // Properties for module myLLMModel_mod_inst
    // output operation map
    ctx->worker_context[0].operation_num = 2;
    ctx->worker_context[0].operation_map = calloc(2, sizeof(ldp_mod_operation_map));

    // operation json_control:
    ctx->worker_context[0].operation_map[0].op_name = "json_control";
    ctx->worker_context[0].operation_map[0].nb_module = 0;
    ctx->worker_context[0].operation_map[0].nb_local_socket = 1;
    ctx->worker_context[0].operation_map[0].nb_ext_socket = 0;

    ctx->worker_context[0].operation_map[0].module_operations = NULL;
    ctx->worker_context[0].operation_map[0].local_socket_operations = calloc(1, sizeof(ldp_socket_operation));
    ctx->worker_context[0].operation_map[0].external_socket_operations = NULL;
    // socket to component: svc_json_cmd
    ctx->worker_context[0].operation_map[0].local_socket_operations[0].interface = &ctx->interface_ctx_array[ctx->nb_client+1];
    ctx->worker_context[0].operation_map[0].local_socket_operations[0].op_id = compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd__json_control;
    ctx->worker_context[0].operation_map[0].local_socket_operations[0].RR_answer_op_activating = false; // not a RR
    ctx->worker_context[0].operation_map[0].local_socket_operations[0].RR_answer_op_index = 0; // not a RR

    // operation query_versioned_json:
    ctx->worker_context[0].operation_map[1].op_name = "query_versioned_json";
    ctx->worker_context[0].operation_map[1].nb_module = 0;
    ctx->worker_context[0].operation_map[1].nb_local_socket = 1;
    ctx->worker_context[0].operation_map[1].nb_ext_socket = 0;

    ctx->worker_context[0].operation_map[1].module_operations = NULL;
    ctx->worker_context[0].operation_map[1].local_socket_operations = calloc(1, sizeof(ldp_socket_operation));
    ctx->worker_context[0].operation_map[1].external_socket_operations = NULL;
    // socket to component: svc_vd_query
    ctx->worker_context[0].operation_map[1].local_socket_operations[0].interface = &ctx->interface_ctx_array[ctx->nb_client+2];
    ctx->worker_context[0].operation_map[1].local_socket_operations[0].op_id = compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query__query_versioned_json;
    ctx->worker_context[0].operation_map[1].local_socket_operations[0].RR_answer_op_activating = true; // RR answer property
    ctx->worker_context[0].operation_map[1].local_socket_operations[0].RR_answer_op_index = 3; // in fifo_manager, operation query_versioned_json

   ldp_init_request_response(&ctx->worker_context[0].req_resp,1,10,1, ctx->mem_pool);

    ldp_comp_init_state(ctx);
    ldp_init_VD_repositories(ctx);
    ldp_comp_prepare_module_threads(ctx, mod_attr, NULL, NULL);
    ldp_thread_properties prop = {.policy=ctx->sched_policy, .logger=ctx->logger_PF};
    prop.priority = ctx->worker_context[0].priority;
    prop.thread_name = ctx->worker_context[0].name;
    prop.cpu_affinity_mask = ctx->worker_context[0].cpu_affinity_mask;
    ret=ldp_thread_create(&mod_thread[0],mod_attr[0],start_module_compLLMModel_myLLMModel_mod_inst, (void*) &ctx->worker_context[0], &prop,ctx->mem_pool);
    if (ret != APR_SUCCESS) {
        ldp_send_fault_error_to_father(ctx, ctx->worker_context[0].mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 4);
    }
    assert(ret==APR_SUCCESS);


    ldp_start_comp_server(ctx);
    ldp_wait_modules(ctx, mod_thread, NULL, NULL);
    UNUSED(ret);
    ldp_destroy_component(ctx);
    apr_pool_destroy(mem_pool);
    ldp_log_shutdown();
    apr_terminate();
}

