/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.318513    
*
* WARNING: all changes made in this file will be lost
*/

#include "ldp_fine_grain_deployment.h" // Need to be first to define _GNU_SOURCE
#include <stdio.h>
#include <inttypes.h>
#include <assert.h>
#include <apr.h>
#include <apr_time.h>
#include "ldp_thread.h"
#include "ldp_structures.h"

#include "ldp_log.h"
#include "route.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_trigger.h"
#include "ldp_comp_util.h"
#include "ldp_network.h"
#include "ldp_mod_container_util.h"
#include "ldp_ELI_udp.h"
#include "ldp_fifo_manager.h"
#include "svc_svc_event_data_deserial.h"
#include "svc_svc_json_cmd_deserial.h"
#include "svc_svc_vd_query_deserial.h"
#include "svc_svc_versioned_data_deserial.h"
#include "svc_svc_voice_msg_deserial.h"
#include "component_mycompYYYDevice.h"
#include "component_mycompYYYDevice__properties.h"
ldp_PDomain_ctx* compYYYDevice_ctx = NULL;
static void router_socket_msg_YYY_PD(ldp_PDomain_ctx* ctx, uint32_t operation_id, char* params,
                                        int params_size, ldp_interface_ctx* socket_sender, int port_nb, uint32_t ELI_sequence_num, ECOA__uint32 sender_PF_ID){

    uint32_t mod_op_id = 0;
    //char* msg_buffer = params;
    
    if ((port_nb == link_EW_to_YYY_read_port) && (
      (sender_PF_ID == link_EW_to_YYY_read_PF_ID) )){
        switch (operation_id){
        // ========= link : link_EW_to_YYY
        // input operations for syntax svc_versioned_data
            case compVoiceMgmt_svc_versioned_data__compYYYDevice_svc_versioned_data__versioned_data:
            // wire compVoiceMgmt_svc_versioned_data__compYYYDevice_svc_versioned_data
        {
            ldp_repository_VD* repo;UNUSED(repo);
            ECOA__return_status ret;UNUSED(ret);
            if (params_size != 0){
            // need to write parameters as a local TCP message
            params_size = deserialized_svc_versioned_data_versioned_data(ctx->msg_buffer, params);

            // no writter 
            }
            break;
        }
        // input operations for syntax svc_event_data
            case compYYYDevice_svc_event_data__compVoiceMgmt_svc_event_data__event_data:
            // wire compYYYDevice_svc_event_data__compVoiceMgmt_svc_event_data
        {
            ldp_repository_VD* repo;UNUSED(repo);
            ECOA__return_status ret;UNUSED(ret);
            if (params_size != 0){
            // need to write parameters as a local TCP message
            params_size = deserialized_svc_event_data_event_data(ctx->msg_buffer, params);

            // Update a VD repository;
            repo = &ctx->VD_repo_array[1];
            ret = ldp_update_repository(repo, (unsigned char*) ctx->msg_buffer);
            if (ret != ECOA__return_status_OK){
                ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,
                    "[PD %s] impossible to update a repository: index 1, error : %i", ctx->name, ret);
            }
            // notify readers module
            ldp_notify_local_readers(ctx, repo);

            }
            break;
        }
        default:
            ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,
            "[PD %s] wrong operation ID %i on port number %i, from PF id %i",
             ctx->name, operation_id, port_nb, sender_PF_ID);
        }
    }else     {
        ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,
                            "[PD %s] wrong port number %i, op: %i, PF id: %i",
                            ctx->name, port_nb, operation_id, sender_PF_ID);
    }

    UNUSED(mod_op_id);
    UNUSED(params);
    UNUSED(params_size);
    UNUSED(socket_sender);
}

static int YYY_PD_compute_buffer_size(void){
int size_of_buffer = -1;
int tmp;
tmp = sizeof(Common_lib__event_data);
size_of_buffer = ( tmp < size_of_buffer ) ? size_of_buffer : tmp;
tmp = sizeof(Common_lib__versioned_data);
size_of_buffer = ( tmp < size_of_buffer ) ? size_of_buffer : tmp;

   return size_of_buffer+LDP_ELI_HEADER_SIZE+28;
}

int main(void){
    apr_initialize();
    apr_pool_t* mem_pool;
    apr_pool_create(&mem_pool,NULL);

    /// Initialisation of protection domain context YYY_PD
    ldp_status_t ret;
    ldp_PDomain_ctx* ctx = malloc(sizeof(ldp_PDomain_ctx));
    compYYYDevice_ctx = ctx;
    ctx->name = "YYY_PD"; 
    ctx->mem_pool = mem_pool;
    ctx->route_function_ptr = &router_socket_msg_YYY_PD;
    ctx->sched_policy = LDP_SCHED_OTHER;
    ctx->ELI_platform_ID = ELI_PF_Platform_EW;
    // loggers
    ctx->logger = malloc(sizeof(ldp_logger));
    ctx->logger->config_filename = "log_YYY_PD.properties";
    ldp_log_init(ctx->logger);
    ldp_log_initialize(ctx->logger,ctx->name);

    ctx->logger_PF = malloc(sizeof(ldp_logger_platform));
    ctx->logger_PF->config_filename = "log_YYY_PD_PF.properties";
    ldp_log_PF_initialize(ctx->logger_PF,"YYY_PD_PF");
    ctx->logger_PF->pd_name = "YYY_PD";
    ctx->logger_PF->node_name = "_";
    ctx->logger_PF->level_mask=0xffff;

    // technical thread affinity
    /* chose every cores on the node */
    /* No need tyo set affinity: every cores are enable by default */
    ctx->technical_cpu_mask = ldp_create_cpu_mask_full();
    log_thread_deployment_properties(ctx->logger_PF);


    ctx->msg_buffer_size = YYY_PD_compute_buffer_size();
    ctx->nb_client = 0; 
    ctx->nb_server = 2; 
    ctx->interface_ctx_array = calloc(ctx->nb_client+ctx->nb_server, sizeof(ldp_interface_ctx));
    ctx->interface_ctx_array[0].type = LDP_LOCAL_IP;
    ctx->interface_ctx_array[0].info_r = (ldp_tcp_info) {YYY_PD_port, YYY_PD_addr, 1, true}; // socket with main process. Does not match with a wire
    ctx->interface_ctx_array[ctx->nb_client+1].type = LDP_ELI_MCAST;
    ctx->interface_ctx_array[ctx->nb_client+1].info_r = (ldp_tcp_info) {link_EW_to_YYY_sent_port,
                                            link_EW_to_YYY_sent_addr,
                                            0, false};
    ctx->interface_ctx_array[ctx->nb_client+1].inter.mcast.UDP_current_PF_ID = link_EW_to_YYY_sent_PF_ID;
    ctx->interface_ctx_array[ctx->nb_client+1].inter.mcast.link_num = 1;
    ctx->interface_ctx_array[ctx->nb_client+1].inter.mcast.PF_links_ctx = calloc(1, sizeof(ldp_PF_link));
    ctx->interface_ctx_array[ctx->nb_client+1].inter.mcast.PF_links_ctx[0] = (ldp_PF_link){
        {ELI_PF_Platform_YYY, link_EW_to_YYY_read_PF_ID, 1, 0,
        (ldp_ELI_UDP_channel[1]){}},NULL};
    ctx->mcast_read_interface_num = 1; 
    ctx->mcast_read_interface = calloc(1, sizeof(ldp_interface_ctx));
    ctx->mcast_read_interface[0].type = LDP_ELI_MCAST;
    ctx->mcast_read_interface[0].info_r = (ldp_tcp_info) {link_EW_to_YYY_read_port,
                                            link_EW_to_YYY_read_addr,
                                            0, false};
    ctx->mcast_read_interface[0].inter.mcast.link_num = 1;
    ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx = calloc(1, sizeof(ldp_PF_link));
    ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx[0] = (ldp_PF_link){
        {ELI_PF_Platform_YYY, link_EW_to_YYY_read_PF_ID, 256, 0, NULL},
        &ctx->interface_ctx_array[ctx->nb_client+1]};
    ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx[0].link_ctx.buffer_size = ldp_max(min_buffer_size_svc_event_data(),min_buffer_size_svc_versioned_data());
    ldp_initialized_PF_link(&ctx->mcast_read_interface[0].inter.mcast.PF_links_ctx[0].link_ctx);

    //init module instances context 
    ctx->nb_module = 1;
    apr_threadattr_t* mod_attr[ctx->nb_module];
    apr_thread_t* mod_thread[ctx->nb_module];
    ctx->worker_context = calloc(ctx->nb_module, sizeof(ldp_module_context));

    //init trigger instances context 
    ctx->nb_trigger = 1;
    apr_threadattr_t* trig_attr[ctx->nb_trigger];
    apr_thread_t* trig_thread[ctx->nb_trigger];
    ctx->trigger_context = calloc(ctx->nb_trigger, sizeof(ldp_trigger_context));

    //init dynamic trigger instances context 
    ctx->nb_dyn_trigger = 0;
    // VD repositories
    ctx->num_VD_repo = 2;
    ctx->VD_repo_array = calloc(2,sizeof(ldp_repository_VD));
    ldp_create_repository(&ctx->VD_repo_array[0], 1, 3,  sizeof(Common_lib__versioned_data), CONTROLLED, mem_pool);
ctx->VD_repo_array[0].serial_data_fct = serialized_svc_versioned_data_versioned_data;
    ldp_create_repository(&ctx->VD_repo_array[1], 1, 2,  sizeof(Common_lib__event_data), CONTROLLED, mem_pool);
ctx->VD_repo_array[1].serial_data_fct = NULL;


    // context for module myYYYDevice_mod_inst
    ctx->worker_context[0].name = "myYYYDevice_mod_inst";
    ctx->worker_context[0].mod_id = 4;
    ctx->worker_context[0].network_write_data = malloc(sizeof(net_data_w));
    ctx->worker_context[0].network_write_data->module_id = 2;
    ctx->worker_context[0].network_write_data->msg_id = 100;
    ctx->worker_context[0].component_name = "compYYYDevice";
    ctx->worker_context[0].mem_pool = mem_pool;
    ctx->worker_context[0].state = IDLE;
    ctx->worker_context[0].msg_buffer_size = YYY_PD_compute_buffer_size();
    ctx->worker_context[0].msg_buffer = NULL;
    ctx->worker_context[0].component_ctx = ctx ;
    ctx->worker_context[0].logger_PF = ctx->logger_PF ;
    ctx->worker_context[0].priority = 2;// ??
    // CPU mask
    ctx->worker_context[0].cpu_affinity_mask = ldp_create_cpu_mask_full();
    ctx->worker_context[0].logger = malloc(sizeof(ldp_logger));
    *(    ctx->worker_context[0].logger) = (ldp_logger) {
       ctx->logger->initializer,
       ctx->logger->config_filename,
       ctx->logger->name,
       "compYYYDevice",
       "myYYYDevice_mod_inst",
ECOA_LOG_FATAL|ECOA_LOG_ERROR|ECOA_LOG_DEBUG|ECOA_LOG_WARN|ECOA_LOG_INFO|ECOA_LOG_TRACE   };

    // Fifo manager
    ctx->worker_context[0].fifo_manager = malloc(sizeof(ldp_fifo_manager));
    ctx->worker_context[0].fifo_manager->fifo = malloc(sizeof(ldp_fifo));
    ctx->worker_context[0].fifo_manager->fifo->size = 18;
    ctx->worker_context[0].fifo_manager->op_pool_num = 3;
    ctx->worker_context[0].fifo_manager->op_element_pools = calloc(3, sizeof(ldp_element_pool));
    ctx->worker_context[0].fifo_manager->op_element_pools[0].element_num = 8; // lifecycle operations
    ctx->worker_context[0].fifo_manager->op_element_pools[0].parameter_size = 0; // no parameters
    ctx->worker_context[0].fifo_manager->op_element_pools[1].element_num = 8; // event_data_in
    ctx->worker_context[0].fifo_manager->op_element_pools[1].parameter_size = sizeof(Common_lib__event_data);
    ctx->worker_context[0].fifo_manager->op_element_pools[2].element_num = 8; // trigger_publish
    ctx->worker_context[0].fifo_manager->op_element_pools[2].parameter_size = 0;
    // Pinfo manager
    ctx->worker_context[0].pinfo_manager.pinfo_num = 0;
    ctx->worker_context[0].num_reader_mng = 1; 
    ctx->worker_context[0].num_writter_mng = 1;
    ctx->worker_context[0].VD_reader_managers = calloc(1, sizeof(ldp_VD_reader_mng));
    ctx->worker_context[0].VD_writter_managers = calloc(1, sizeof(ldp_VD_writter_mng));
ldp_create_reader_mng(&    ctx->worker_context[0].VD_reader_managers[0], &ctx->VD_repo_array[1], 1);//event_data_in
ldp_create_writter_mng(&    ctx->worker_context[0].VD_writter_managers[0], &ctx->VD_repo_array[0], 1, READ_WRITE);//versioned_data_out

    // Properties for module myYYYDevice_mod_inst
    // output operation map
    ctx->worker_context[0].operation_num = 0;
    ctx->worker_context[0].operation_map = calloc(0, sizeof(ldp_mod_operation_map));
   ldp_init_request_response(&ctx->worker_context[0].req_resp, 0, 0,0, ctx->mem_pool);


    // context for module publish_timer
    ctx->trigger_context[0].name = "publish_timer";
    ctx->trigger_context[0].mod_id = 5;
    ctx->trigger_context[0].network_write_data = malloc(sizeof(net_data_w));
    ctx->trigger_context[0].network_write_data->module_id = 3;
    ctx->trigger_context[0].network_write_data->msg_id = 100;
    ctx->trigger_context[0].component_name = "compYYYDevice";
    ctx->trigger_context[0].mem_pool = mem_pool;
    ctx->trigger_context[0].state = IDLE;
    ctx->trigger_context[0].msg_buffer_size = YYY_PD_compute_buffer_size();
    ctx->trigger_context[0].msg_buffer = NULL;
    ctx->trigger_context[0].component_ctx = ctx ;
    ctx->trigger_context[0].logger_PF = ctx->logger_PF ;
    ctx->trigger_context[0].priority = 1;// ??
    // CPU mask
    ctx->trigger_context[0].cpu_affinity_mask = ldp_create_cpu_mask_full();
    ctx->trigger_context[0].logger = NULL;
    // Fifo manager
    ctx->trigger_context[0].fifo_manager = malloc(sizeof(ldp_fifo_manager));
    ctx->trigger_context[0].fifo_manager->fifo = malloc(sizeof(ldp_fifo));
    ctx->trigger_context[0].fifo_manager->fifo->size = 2;
    ctx->trigger_context[0].fifo_manager->op_pool_num = 1;
    ctx->trigger_context[0].fifo_manager->op_element_pools = calloc(1, sizeof(ldp_element_pool));
    ctx->trigger_context[0].fifo_manager->op_element_pools[0].element_num = 8; // lifecycle operations
    ctx->trigger_context[0].fifo_manager->op_element_pools[0].parameter_size = 0; // no parameters
    ctx->trigger_context[0].nb_trigger_event = 1;
    ctx->trigger_context[0].trigger_events = calloc(1,sizeof(ldp_trigger_event_context));
    ctx->trigger_context[0].operation_num = 1;
    ctx->trigger_context[0].operation_map = calloc(1, sizeof(ldp_mod_operation_map));
   // event for period 5
    ctx->trigger_context[0].trigger_events[0].period = 5;
    ctx->trigger_context[0].trigger_events[0].nb_operations=1;
    ctx->trigger_context[0].trigger_events[0].operation_indexes = calloc(1, sizeof(int));
    ctx->trigger_context[0].trigger_events[0].operation_indexes[0]=0;

    // operation trigger_publish:
    ctx->trigger_context[0].operation_map[0].op_name = "trigger_publish";
    ctx->trigger_context[0].operation_map[0].nb_module = 1;
    ctx->trigger_context[0].operation_map[0].nb_local_socket = 0;
    ctx->trigger_context[0].operation_map[0].nb_ext_socket = 0;

    ctx->trigger_context[0].operation_map[0].module_operations = calloc(1, sizeof(ldp_mod_operation));
    ctx->trigger_context[0].operation_map[0].local_socket_operations = NULL;
    ctx->trigger_context[0].operation_map[0].external_socket_operations = NULL;
    // op 'trigger_publish' of module 'myYYYDevice_mod_inst' in component 'compYYYDevice'
    ctx->trigger_context[0].operation_map[0].module_operations[0].mod_ctx = &ctx->worker_context[0];
    ctx->trigger_context[0].operation_map[0].module_operations[0].op_id = compYYYDevice__myYYYDevice_mod_inst__trigger_publish; // ID_publish_timer_myYYYDevice_mod_inst_trigger_publish
    ctx->trigger_context[0].operation_map[0].module_operations[0].op_index = 2;
    ctx->trigger_context[0].operation_map[0].module_operations[0].op_activating = true;

// repository readers structures 
//compYYYDevice
    ctx->VD_repo_array[0].readers[0].nature = EXTERN_SOCKET;
    ctx->VD_repo_array[0].readers[0].reader_ptr = &ctx->interface_ctx_array[ctx->nb_client+1];
    ctx->VD_repo_array[0].readers[0].operation_id = compVoiceMgmt_svc_versioned_data__compYYYDevice_svc_versioned_data__versioned_data; //versioned_data

//compYYYDevice
    ctx->VD_repo_array[1].readers[0].nature = MODULE;
    ctx->VD_repo_array[1].readers[0].reader_ptr = &ctx->worker_context[0];
    ctx->VD_repo_array[1].readers[0].operation_id = compYYYDevice__myYYYDevice_mod_inst__event_data_in; //event_data_in
    ctx->VD_repo_array[1].readers[0].mod_op_activating = true;
    ctx->VD_repo_array[1].readers[0].mod_op_index = 1;

    ldp_comp_init_state(ctx);
    ldp_init_VD_repositories(ctx);
    ldp_comp_prepare_module_threads(ctx, mod_attr, NULL, trig_attr);
    ldp_thread_properties prop = {.policy=ctx->sched_policy, .logger=ctx->logger_PF};
    prop.priority = ctx->trigger_context[0].priority;
    prop.thread_name = ctx->trigger_context[0].name;
    prop.cpu_affinity_mask = ctx->trigger_context[0].cpu_affinity_mask;
    ret=ldp_thread_create(&trig_thread[0], trig_attr[0], ldp_start_module_trigger, (void*) &ctx->trigger_context[0], &prop, ctx->mem_pool);
    if (ret != APR_SUCCESS) {
        ldp_send_fault_error_to_father(ctx, ctx->trigger_context[0].mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 2);
    }
    assert(ret==APR_SUCCESS);

    prop.priority = ctx->worker_context[0].priority;
    prop.thread_name = ctx->worker_context[0].name;
    prop.cpu_affinity_mask = ctx->worker_context[0].cpu_affinity_mask;
    ret=ldp_thread_create(&mod_thread[0],mod_attr[0],start_module_compYYYDevice_myYYYDevice_mod_inst, (void*) &ctx->worker_context[0], &prop,ctx->mem_pool);
    if (ret != APR_SUCCESS) {
        ldp_send_fault_error_to_father(ctx, ctx->worker_context[0].mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 4);
    }
    assert(ret==APR_SUCCESS);


    ldp_start_comp_server(ctx);
    ldp_wait_modules(ctx, mod_thread, NULL, trig_thread);
    UNUSED(ret);
    ldp_destroy_component(ctx);
    apr_pool_destroy(mem_pool);
    ldp_log_shutdown();
    apr_terminate();
}

