/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.277110    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _ROUTE_H 
#define _ROUTE_H 

#define ID_INITIALIZE_event "INITIALIZE" 
#define ID_START_event "START" 
#define ID_STOP_event "STOP" 
#define MODULE_BASE_PORT (20000+0)
#define COMPONENT_BASE_PORT (MODULE_BASE_PORT + 10000)

// ELI Platform IDs
#define ELI_PF_Platform_YYY (1)
#define ELI_PF_Platform_EW (2)
#define ELI_PF_Platform_XXX (3)

// Platform links
#define link_EW_to_YYY_read_port (20002)
#define link_EW_to_YYY_read_addr "225.192.1.1"
#define link_EW_to_YYY_sent_port (20001)
#define link_EW_to_YYY_sent_addr "225.192.1.1"
#define link_EW_to_YYY_sent_PF_ID (2)
#define link_EW_to_YYY_read_PF_ID (1)
#define link_XXX_to_EW_read_port (20002)
#define link_XXX_to_EW_read_addr "225.192.1.1"
#define link_XXX_to_EW_sent_port (20003)
#define link_XXX_to_EW_sent_addr "225.192.1.1"
#define link_XXX_to_EW_sent_PF_ID (2)
#define link_XXX_to_EW_read_PF_ID (3)

// local-node IP connections with master process
#define YYY_PD_addr "127.0.0.1" 
#define YYY_PD_port (COMPONENT_BASE_PORT+0) 

#define VoiceMgmt_PD_addr "127.0.0.1" 
#define VoiceMgmt_PD_port (COMPONENT_BASE_PORT+1) 

#define LLMModel_PD_addr "127.0.0.1" 
#define LLMModel_PD_port (COMPONENT_BASE_PORT+2) 

#define XXX_PD_addr "127.0.0.1" 
#define XXX_PD_port (COMPONENT_BASE_PORT+3) 


// local-node IP connections between PD
#define compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd_port (MODULE_BASE_PORT+8)
#define compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd_addr "127.0.0.1"
#define compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query_port (MODULE_BASE_PORT+9)
#define compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query_addr "127.0.0.1"


// wire service IDs

#define compVoiceMgmt_svc_versioned_data__compYYYDevice_svc_versioned_data__versioned_data 1611300215
#define compYYYDevice_svc_event_data__compVoiceMgmt_svc_event_data__event_data 1758054607
#define compXXXDevice_svc_voice_msg__compLLMModel_svc_voice_msg__voice_control 657021877
#define compXXXDevice_svc_voice_msg__compLLMModel_svc_voice_msg__voice_query 1617140922
#define compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd__json_control 1892203028
#define compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query__query_versioned_json 1985629425


// module op ID

 /// YYY_PD
// myYYYDevice_mod_inst compYYYDevice
#define compYYYDevice__myYYYDevice_mod_inst__trigger_publish 200//
#define compYYYDevice__myYYYDevice_mod_inst__event_data_in 201//
// publish_timer compYYYDevice
#define compYYYDevice__publish_timer__5 202//
 /// VoiceMgmt_PD
// myVoiceMgmt_mod_inst compVoiceMgmt
#define compVoiceMgmt__myVoiceMgmt_mod_inst__json_control 203//
#define compVoiceMgmt__myVoiceMgmt_mod_inst__query_versioned_json 204 //
#define compVoiceMgmt__myVoiceMgmt_mod_inst__versioned_data_in 205//
 /// LLMModel_PD
// myLLMModel_mod_inst compLLMModel
#define compLLMModel__myLLMModel_mod_inst__voice_control 206//
#define compLLMModel__myLLMModel_mod_inst__voice_query 207//
#define compLLMModel__myLLMModel_mod_inst__query_versioned_json compVoiceMgmt__myVoiceMgmt_mod_inst__query_versioned_json//
#define compLLMModel__myLLMModel_mod_inst__json_control 208//
 /// XXX_PD
// myXXXDevice_mod_inst compXXXDevice
#define compXXXDevice__myXXXDevice_mod_inst__trigger_voice 209//
#define compXXXDevice__myXXXDevice_mod_inst__voice_control 210//
#define compXXXDevice__myXXXDevice_mod_inst__voice_query 211//
// voice_timer compXXXDevice
#define compXXXDevice__voice_timer__10 212//


#endif /* _ROUTE_H */
