/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.710699    
*
* WARNING: all changes made in this file will be lost
*/

#include "stdbool.h"
#include "ECOA.h"
#include "LDP__ECOA_types_zeroise.h"
#include "Common_lib.h"
#include "LDP__Common_lib_types_zeroise.h"
void LDP_Common_lib__event_data_zeroise(Common_lib__event_data *data){
    LDP_ECOA__uint16_zeroise(&data->topic_id);
    LDP_ECOA__uint16_zeroise(&data->status_word_0);
    LDP_ECOA__uint16_zeroise(&data->status_word_1);
    LDP_ECOA__uint16_zeroise(&data->status_word_2);
    LDP_ECOA__uint16_zeroise(&data->status_word_3);
    LDP_ECOA__uint16_zeroise(&data->status_word_4);
    LDP_ECOA__uint16_zeroise(&data->status_word_5);
    LDP_ECOA__uint16_zeroise(&data->status_word_6);
    LDP_ECOA__uint16_zeroise(&data->status_word_7);
    LDP_ECOA__uint8_zeroise(&data->flag_0);
    LDP_ECOA__uint8_zeroise(&data->flag_1);
    LDP_ECOA__uint8_zeroise(&data->flag_2);
    LDP_ECOA__uint8_zeroise(&data->flag_3);
}
void LDP_Common_lib__versioned_data_zeroise(Common_lib__versioned_data *data){
    LDP_ECOA__uint16_zeroise(&data->version);
    LDP_ECOA__uint16_zeroise(&data->sample_0);
    LDP_ECOA__uint16_zeroise(&data->sample_1);
    LDP_ECOA__uint16_zeroise(&data->sample_2);
    LDP_ECOA__uint16_zeroise(&data->sample_3);
    LDP_ECOA__uint8_zeroise(&data->channel_0);
    LDP_ECOA__uint8_zeroise(&data->channel_1);
    LDP_ECOA__uint8_zeroise(&data->channel_2);
    LDP_ECOA__uint8_zeroise(&data->channel_3);
    LDP_ECOA__uint8_zeroise(&data->channel_4);
    LDP_ECOA__uint8_zeroise(&data->channel_5);
    LDP_ECOA__uint8_zeroise(&data->channel_6);
    LDP_ECOA__uint8_zeroise(&data->channel_7);
    LDP_ECOA__uint8_zeroise(&data->channel_8);
}
void LDP_Common_lib__json_text_zeroise(Common_lib__json_text *data){
    int i;
    data->current_size = 0;
    for(i=0; i<Common_lib__json_text_MAXSIZE; i++){
        LDP_ECOA__char8_zeroise(&data->data[i]);
    }
}
void LDP_Common_lib__voice_msg_zeroise(Common_lib__voice_msg *data){
    int i;
    data->current_size = 0;
    for(i=0; i<Common_lib__voice_msg_MAXSIZE; i++){
        LDP_ECOA__char8_zeroise(&data->data[i]);
    }
}

