/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.585038    
*
* WARNING: all changes made in this file will be lost
*/


/* Module Container Implementation Skeleton for myYYYDevice_mod */

/* @file myYYYDevice_mod_container.c
 * This is the Module Container for Module myYYYDevice_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

#include <assert.h>
#include "route.h"
#include "ldp_network.h"
#include "ldp_time_manager.h"
#include "ldp_VD.h"
#include "ldp_ELI_udp.h"
#include "ldp_mod_container_util.h"
#include "myYYYDevice_mod_container.h"
#include "component_mycompYYYDevice__properties.h"

#include "ECOA.h"
#include "ECOA_simple_types_serialization.h"
#include "Common_lib.h"
#include "Common_lib_serialization.h"

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__get_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_get_written_access(&ctx->VD_writter_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 12);
}

    return ret;
}

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__cancel_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_cancel_written_access(&ctx->VD_writter_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 13);
}

return ret;

}

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__publish_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle)
{
  
ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_publish_written_access(ctx, &ctx->VD_writter_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 14);
}

return ret;

}

ECOA__return_status myYYYDevice_mod_container__event_data_in__get_read_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__event_data_in_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_get_read_access(&ctx->VD_reader_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 15);
}

return ret;
}

ECOA__return_status myYYYDevice_mod_container__event_data_in__release_read_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__event_data_in_handle* data_handle)
{

ldp_module_context* ctx = ((ldp_module_context*) context->platform_hook);

ECOA__return_status ret = ldp_release_read_access(&ctx->VD_reader_managers[0], (ldp_VD_handle*) data_handle);

if (ret != ECOA__return_status_OK){ 
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT,
                                    ECOA__error_type_RESOURCE_NOT_AVAILABLE, 16);
}

return ret;

}

/* Properties API */


/* PINFO API */

/* Logging services API call specifications */
void myYYYDevice_mod_container__log_trace(myYYYDevice_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_TRACE, "TRACE", ctx->logger,  log.data, &timestamp);
}
void myYYYDevice_mod_container__log_debug(myYYYDevice_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_DEBUG, "DEBUG", ctx->logger, log.data, &timestamp);
}
void myYYYDevice_mod_container__log_info(myYYYDevice_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_INFO, "INFO", ctx->logger, log.data, &timestamp);
}
void myYYYDevice_mod_container__log_warning(myYYYDevice_mod__context* context, const ECOA__log log){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_WARN, "WARNING", ctx->logger, log.data, &timestamp);
}
void myYYYDevice_mod_container__raise_error(myYYYDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_ERROR, 1);
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_ERROR, "ERROR", ctx->logger, log.data, &timestamp);
}
void myYYYDevice_mod_container__raise_fatal_error(myYYYDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code){
   ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
   find_dest_mod_by_comp_and_send(ctx->component_ctx, ctx->component_name, LDP_ID_SHUTDOWN_life);
   ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_FATAL_ERROR, 1);
   ldp__timestamp timestamp;
   ldp_get_ecoa_utc_time(&timestamp);
   ldp_log_log(ECOA_LOG_FATAL, "FATAL", ctx->logger, log.data, &timestamp);
}

/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myYYYDevice_mod_container__get_relative_local_time(myYYYDevice_mod__context* context, ECOA__hr_time *relative_local_time){
    ldp_get_ecoa_relative_time(NULL, (ldp__timestamp*) relative_local_time);
    UNUSED(context);
}
ECOA__return_status myYYYDevice_mod_container__get_UTC_time(myYYYDevice_mod__context* context, ECOA__global_time *utc_time){
    ldp_get_ecoa_utc_time((ldp__timestamp *) utc_time);
    UNUSED(context);
    return ECOA__return_status_OK;
}

ECOA__return_status myYYYDevice_mod_container__get_absolute_system_time(myYYYDevice_mod__context* context, ECOA__global_time *absolute_system_time){
    ldp_get_ecoa_absolute_time((ldp__timestamp *) absolute_system_time);
    UNUSED(context);
    return ECOA__return_status_OK;
}


void myYYYDevice_mod_container__get_relative_local_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *relative_local_time_resolution)
{
  ldp_get_ecoa_relative_timeres((ldp__timestamp *)relative_local_time_resolution);

UNUSED(context);
}

void myYYYDevice_mod_container__get_UTC_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *utc_time_resolution)
{
  ldp_get_ecoa_utc_timeres((ldp__timestamp *)utc_time_resolution);

UNUSED(context);
}

void myYYYDevice_mod_container__get_absolute_system_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *absolute_system_time_resolution)
{
  ldp_get_ecoa_absolute_timeres((ldp__timestamp *)absolute_system_time_resolution);

UNUSED(context);
}


