/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.625234    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _ROUTE_H 
#define _ROUTE_H 

#define ID_INITIALIZE_event "INITIALIZE" 
#define ID_START_event "START" 
#define ID_STOP_event "STOP" 
#define MODULE_BASE_PORT (20000+0)
#define COMPONENT_BASE_PORT (MODULE_BASE_PORT + 10000)

// ELI Platform IDs
#define ELI_PF_Platform_XXX (3)

// Platform links

// local-node IP connections with master process
#define XXX_PD_addr "0.0.0.0" 
#define XXX_PD_port (COMPONENT_BASE_PORT+0) 


// local-node IP connections between PD


// wire service IDs



// module op ID

 /// XXX_PD
// myXXXDevice_mod_inst compXXXDevice
#define compXXXDevice__myXXXDevice_mod_inst__trigger_voice 200//
#define compXXXDevice__myXXXDevice_mod_inst__voice_control 201//
#define compXXXDevice__myXXXDevice_mod_inst__voice_query 202//
// voice_timer compXXXDevice
#define compXXXDevice__voice_timer__10 203//


#endif /* _ROUTE_H */
