/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.545220    
*
* WARNING: all changes made in this file will be lost
*/

/* Module Container Implementation Skeleton for myXXXDevice_mod */

/**
*  @file myXXXDevice_mod_container.cpp
*  @brief This is the Module Container for Module  myXXXDevice_mod
*
*/

#include <assert.h>

#include "route.h"

#include "ldp_time_manager.h"
#include "ldp_log.h"
#include "ldp_VD.h"

#include "ldp_mod_container_util.h"
#include "myXXXDevice_mod_container.hpp"
#include "myXXXDevice_mod_container_types.hpp"

#include "component_mycompXXXDevice__properties.h"

#include "ECOA.hpp"
#include "Common_lib.hpp"

namespace myXXXDevice_mod
{

  Container::Container(platform_hook* hook){
    this->hook = hook;
  }


  void Container::voice_control__send(const Common_lib::voice_msg& voice_content){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    uint32_t params_size = 0+sizeof(Common_lib::voice_msg);
    char* param_msg = ctx->msg_buffer;
    if (ctx->operation_map[0].nb_ext_socket > 0){
        //uint32_t added_size = 0;
        uint32_t total_added_size = LDP_HEADER_TCP_SIZE;
        //uint32_t max_size = params_size;
        //serialize_Common_lib__voice_msg(voice_content, &param_msg[total_added_size], max_size ,&added_size);
        //max_size -= added_size;
        //total_added_size += added_size;
        ldp_mod_event_send_external(ctx, param_msg, total_added_size, ctx->operation_map[0]);

    }
    if ((ctx->operation_map[0].nb_module > 0) ||
        (ctx->operation_map[0].nb_local_socket > 0)){
memcpy(&param_msg[LDP_HEADER_TCP_SIZE], &voice_content,sizeof(Common_lib::voice_msg));
       ldp_mod_event_send_local(ctx, param_msg, params_size, ctx->operation_map[0], true);
   }


  }


  void Container::voice_query__send(const Common_lib::voice_msg& voice_content){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    uint32_t params_size = 0+sizeof(Common_lib::voice_msg);
    char* param_msg = ctx->msg_buffer;
    if (ctx->operation_map[1].nb_ext_socket > 0){
        //uint32_t added_size = 0;
        uint32_t total_added_size = LDP_HEADER_TCP_SIZE;
        //uint32_t max_size = params_size;
        //serialize_Common_lib__voice_msg(voice_content, &param_msg[total_added_size], max_size ,&added_size);
        //max_size -= added_size;
        //total_added_size += added_size;
        ldp_mod_event_send_external(ctx, param_msg, total_added_size, ctx->operation_map[1]);

    }
    if ((ctx->operation_map[1].nb_module > 0) ||
        (ctx->operation_map[1].nb_local_socket > 0)){
memcpy(&param_msg[LDP_HEADER_TCP_SIZE], &voice_content,sizeof(Common_lib::voice_msg));
       ldp_mod_event_send_local(ctx, param_msg, params_size, ctx->operation_map[1], true);
   }


  }

  /* Op of unconsidered type (else)*/
  /* Properties API */


  /* PINFO API */

  /* Logging services API call specifications */
  void Container::log_trace(const ECOA::log &log){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    ldp__timestamp timestamp;
    ldp_get_ecoa_utc_time(&timestamp);
    ldp_log_log(ECOA_LOG_TRACE, "TRACE", ctx->logger, log.data, &timestamp);
  }
  void Container::log_debug(const ECOA::log &log){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    ldp__timestamp timestamp;
    ldp_get_ecoa_utc_time(&timestamp);
    ldp_log_log(ECOA_LOG_DEBUG, "DEBUG", ctx->logger, log.data, &timestamp);
  }
  void Container::log_info(const ECOA::log &log){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    ldp__timestamp timestamp;
    ldp_get_ecoa_utc_time(&timestamp);
    ldp_log_log(ECOA_LOG_INFO, "INFO", ctx->logger, log.data, &timestamp);
  }
  void Container::log_warning(const ECOA::log &log){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    ldp__timestamp timestamp;
    ldp_get_ecoa_utc_time(&timestamp);
    ldp_log_log(ECOA_LOG_WARN, "WARNING", ctx->logger, log.data, &timestamp);
  }

  /* Logging services API call specifications */
  void Container::raise_error(const ECOA::log &log, const ECOA::error_code error_code){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_ERROR, 1);
    ldp__timestamp timestamp;
    ldp_get_ecoa_utc_time(&timestamp);
    ldp_log_log(ECOA_LOG_ERROR, "ERROR", ctx->logger, log.data, &timestamp);
  }
  void Container::raise_fatal_error(const ECOA::log &log, const ECOA::error_code error_code){
    ldp_module_context* ctx=(ldp_module_context*) this->hook;
    ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_FATAL_ERROR, 1);
    ldp__timestamp timestamp;
    ldp_get_ecoa_utc_time(&timestamp);
    ldp_log_log(ECOA_LOG_FATAL, "FATAL", ctx->logger, log.data, &timestamp);
  }

  /* Recovery action service API call specification if the module is a Fault Handler */


  /* Time Services API call specifications */

  void Container::get_relative_local_time(ECOA::hr_time& relative_local_time){
    ldp__timestamp relative_local_time_temp;
    ldp_get_ecoa_relative_time(NULL, &relative_local_time_temp);
    relative_local_time.nanoseconds = relative_local_time_temp.nanoseconds;
    relative_local_time.seconds = relative_local_time_temp.seconds;
  }

  ECOA::return_status Container::get_UTC_time(ECOA::global_time& UTC_time){
  	ldp__timestamp UTC_time_temp;
    ldp_get_ecoa_utc_time( &UTC_time_temp);
    UTC_time.nanoseconds = UTC_time_temp.nanoseconds;
    UTC_time.seconds = UTC_time_temp.seconds;

    return ECOA::return_status::OK;
  }

  ECOA::return_status Container::get_absolute_system_time(ECOA::global_time& absolute_system_time){
  	ldp__timestamp absolute_system_time_temp;
    ldp_get_ecoa_absolute_time( &absolute_system_time_temp);

    absolute_system_time.nanoseconds = absolute_system_time_temp.nanoseconds;
    absolute_system_time.seconds = absolute_system_time_temp.seconds;

    return ECOA::return_status::OK;
  }

  void Container::get_relative_local_time_resolution(ECOA::duration& relative_local_time_resolution){
    ldp__timestamp relative_local_time_resolution_temp;
    ldp_get_ecoa_relative_timeres( &relative_local_time_resolution_temp);
    relative_local_time_resolution.nanoseconds = relative_local_time_resolution_temp.nanoseconds;
    relative_local_time_resolution.seconds = relative_local_time_resolution_temp.seconds;
  }

  void Container::get_UTC_time_resolution(ECOA::duration& utc_time_resolution){
    ldp__timestamp utc_time_resolution_temp;
    ldp_get_ecoa_utc_timeres( &utc_time_resolution_temp);
    utc_time_resolution.nanoseconds = utc_time_resolution_temp.nanoseconds;
    utc_time_resolution.seconds = utc_time_resolution_temp.seconds;
  }

  void Container::get_absolute_system_time_resolution(ECOA::duration& absolute_system_time_resolution){
    ldp__timestamp absolute_system_time_resolution_temp;
    ldp_get_ecoa_absolute_timeres( &absolute_system_time_resolution_temp);
    absolute_system_time_resolution.nanoseconds = absolute_system_time_resolution_temp.nanoseconds;
    absolute_system_time_resolution.seconds = absolute_system_time_resolution_temp.seconds;
  }
}
