/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.700147    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef LDP__ECOA_types_compare_H
#define LDP__ECOA_types_compare_H
#include "stdbool.h"
#include "ECOA.h"
#include "ECOA.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

bool LDP_ECOA__boolean8_compare(const ECOA__boolean8 *data1, const ECOA__boolean8 *data2);
bool LDP_ECOA__int8_compare(const ECOA__int8 *data1, const ECOA__int8 *data2);
bool LDP_ECOA__int16_compare(const ECOA__int16 *data1, const ECOA__int16 *data2);
bool LDP_ECOA__int32_compare(const ECOA__int32 *data1, const ECOA__int32 *data2);
#if defined(ECOA_64BIT_SUPPORT)
bool LDP_ECOA__int64_compare(const ECOA__int64 *data1, const ECOA__int64 *data2);
#endif /* ECOA_64BIT_SUPPORT */
bool LDP_ECOA__uint8_compare(const ECOA__uint8 *data1, const ECOA__uint8 *data2);
bool LDP_ECOA__uint16_compare(const ECOA__uint16 *data1, const ECOA__uint16 *data2);
bool LDP_ECOA__uint32_compare(const ECOA__uint32 *data1, const ECOA__uint32 *data2);
#if defined(ECOA_64BIT_SUPPORT)
bool LDP_ECOA__uint64_compare(const ECOA__uint64 *data1, const ECOA__uint64 *data2);
#endif /* ECOA_64BIT_SUPPORT */
bool LDP_ECOA__char8_compare(const ECOA__char8 *data1, const ECOA__char8 *data2);
bool LDP_ECOA__byte_compare(const ECOA__byte *data1, const ECOA__byte *data2);
bool LDP_ECOA__float32_compare(const ECOA__float32 *data1, const ECOA__float32 *data2);
#if defined(ECOA_64BIT_SUPPORT)
bool LDP_ECOA__double64_compare(const ECOA__double64 *data1, const ECOA__double64 *data2);
#endif /* ECOA_64BIT_SUPPORT */
bool LDP_ECOA__duration_compare(const ECOA__duration *data1, const ECOA__duration *data2);
bool LDP_ECOA__global_time_compare(const ECOA__global_time *data1, const ECOA__global_time *data2);
bool LDP_ECOA__hr_time_compare(const ECOA__hr_time *data1, const ECOA__hr_time *data2);
bool LDP_ECOA__pinfo_filename_compare(const ECOA__pinfo_filename *data1, const ECOA__pinfo_filename *data2);
bool LDP_ECOA__log_compare(const ECOA__log *data1, const ECOA__log *data2);

#if defined(__cplusplus)
}
#endif /* __cplusplus */
#endif /*LDP__ECOA_types_compare_H*/

