/**
* @file LDP_myXXXDevice_mod.c
* @brief This is the code of the DA encapsulation library for ECOA
*
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* This file is generated by the DA ECOA tools and shall not be modified
*/
#include <string.h>

#include <ECOA.h>
#include "myXXXDevice_mod_container.h"
#include "LDP_myXXXDevice_mod.h"
static ECOA__log error_log = {
	sizeof("Error in log_warning")+1,
	"Error in log_warning"
};

void LDP_myXXXDevice_mod__concat(myXXXDevice_mod__context *context,
		ECOA__log *log, char *str) {
	char *module_name = "myXXXDevice_mod: ";
	int module_name_length;
        ECOA__error_code error_code = 0;

	module_name_length = strnlen(module_name, ECOA__LOG_MAXSIZE);

#if defined(__STDC_LIB_EXT1__)
	errno_t result;

	result = strncpy_s((char *)log->data, ECOA__LOG_MAXSIZE, module_name, ECOA__LOG_MAXSIZE - 1);
	if (result != 0) {
		myXXXDevice_mod_container__raise_error(context, error_log,error_code);
	}

	result = strncpy_s(((char *)log->data) + module_name_length, ECOA__LOG_MAXSIZE - module_name_length, str, ECOA__LOG_MAXSIZE - module_name_length - 1);
	if (result != 0) {
		myXXXDevice_mod_container__raise_error(context, error_log,error_code);
	}
#else
	char *returned_string;

	returned_string = strncpy((char *) log->data, module_name,
			ECOA__LOG_MAXSIZE);
	if (returned_string != (char *) log->data) {
		myXXXDevice_mod_container__raise_error(context, error_log,error_code);
	}

	returned_string = strncpy(((char *) log->data) + module_name_length, str,
			ECOA__LOG_MAXSIZE - module_name_length);
	if (returned_string != ((char *) log->data) + module_name_length) {
		myXXXDevice_mod_container__raise_error(context, error_log,error_code);
	}
#endif

	log->current_size = strnlen((char *) log->data, ECOA__LOG_MAXSIZE);

}


/*********** Log related API *************/
void LDP_myXXXDevice_mod__log_trace(myXXXDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myXXXDevice_mod__concat(context, &log, str);
    myXXXDevice_mod_container__log_trace(context, log);
}

void LDP_myXXXDevice_mod__log_debug(myXXXDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myXXXDevice_mod__concat(context, &log, str);
    myXXXDevice_mod_container__log_debug(context, log);
}

void LDP_myXXXDevice_mod__log_info(myXXXDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myXXXDevice_mod__concat(context, &log, str);
    myXXXDevice_mod_container__log_info(context, log);
}

void LDP_myXXXDevice_mod__log_warning(myXXXDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myXXXDevice_mod__concat(context, &log, str);
    myXXXDevice_mod_container__log_warning(context, log);
}

void LDP_myXXXDevice_mod__raise_error(myXXXDevice_mod__context* context, char *str, const ECOA__error_code error_code)
{
    ECOA__log log;
    LDP_myXXXDevice_mod__concat(context, &log, str);
    myXXXDevice_mod_container__raise_error(context, log , error_code);
}

void LDP_myXXXDevice_mod__raise_fatal_error(myXXXDevice_mod__context* context, char *str, const ECOA__error_code error_code)
{
    ECOA__log log;
    LDP_myXXXDevice_mod__concat(context, &log, str);
    myXXXDevice_mod_container__raise_fatal_error(context, log, error_code);
}


/********** Time related API *************/
ECOA__return_status LDP_myXXXDevice_mod__get_absolute_system_time(
        myXXXDevice_mod__context *context,
        ECOA__global_time *absolute_system_time) {
    ECOA__return_status return_status;

    return_status = myXXXDevice_mod_container__get_absolute_system_time(context, absolute_system_time);

    if(return_status == ECOA__return_status_CLOCK_UNSYNCHRONIZED) {
        LDP_myXXXDevice_mod__log_warning(context, "Clock Unsynchronized when get_absolute_system_time");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myXXXDevice_mod__log_warning(context, "Unknown error when get_absolute_system_time");
    }
    return return_status;
}

ECOA__return_status LDP_myXXXDevice_mod__get_relative_local_time(
        myXXXDevice_mod__context *context,
        ECOA__hr_time *relative_local_time) {
    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;

    myXXXDevice_mod_container__get_relative_local_time(context, relative_local_time);

    return return_status;
}

ECOA__return_status LDP_myXXXDevice_mod__get_UTC_time(
        myXXXDevice_mod__context *context,
        ECOA__global_time *utc_time) {
    ECOA__return_status return_status;

    return_status = myXXXDevice_mod_container__get_UTC_time(context, utc_time);

    if(return_status == ECOA__return_status_CLOCK_UNSYNCHRONIZED) {
        LDP_myXXXDevice_mod__log_warning(context, "Clock Unsynchronized when get_UTC_time");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myXXXDevice_mod__log_warning(context, "Unknown error when get_UTC_time");
    }
    return return_status;
}

ECOA__return_status LDP_myXXXDevice_mod__get_relative_local_time_resolution(
        myXXXDevice_mod__context *context,
        ECOA__duration *relative_local_time_resolution){

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myXXXDevice_mod_container__get_relative_local_time_resolution(context, relative_local_time_resolution);

    return return_status;
}

ECOA__return_status LDP_myXXXDevice_mod__get_UTC_time_resolution(
        myXXXDevice_mod__context *context,
        ECOA__duration *utc_time_resolution) {

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myXXXDevice_mod_container__get_UTC_time_resolution(context, utc_time_resolution);

    return return_status;
}

ECOA__return_status LDP_myXXXDevice_mod__get_absolute_system_time_resolution(
        myXXXDevice_mod__context *context,
        ECOA__duration *absolute_system_time_resolution) {

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myXXXDevice_mod_container__get_absolute_system_time_resolution(context, absolute_system_time_resolution);

    return return_status;
}

/************* EVENT SEND ****************/
void LDP_myXXXDevice_mod__send__voice_control(myXXXDevice_mod__context *context
    , const Common_lib__voice_msg* voice_content) {
    
    myXXXDevice_mod_container__voice_control__send(context ,voice_content);
}
void LDP_myXXXDevice_mod__send__voice_query(myXXXDevice_mod__context *context
    , const Common_lib__voice_msg* voice_content) {
    
    myXXXDevice_mod_container__voice_query__send(context ,voice_content);
}


/************ DATA WRITTEN ***************/


/************* DATA READ *****************/


/************ RESPONSE SEND **************/


/************ REQUEST SYNC **************/


/*********** REQUEST ASYNC **************/


