/**
* @file LDP_myLLMModel_mod.h
* @brief This is the header of the DA encapsulation library for ECOA
*\n\
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* This file is generated by the DA ECOA tools and shall not be modified
*/

#if !defined(_LDP_myLLMModel_mod_H)
#define _LDP_myLLMModel_mod_H
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include "myLLMModel_mod_container.h"


/* User tool functions */
/******************************************************************************/
void LDP_myLLMModel_mod__concat(myLLMModel_mod__context *context,ECOA__log *log, char *str);

/******************************************************************************/

/* Request/Response API */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/
ECOA__return_status LDP_myLLMModel_mod__request_async__query_versioned_json(
        myLLMModel_mod__context *context,
        ECOA__uint32 *ID );

/******************************************************************************/

/* Versioned data */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/* Event */
/******************************************************************************/
void LDP_myLLMModel_mod__send__json_control(
        myLLMModel_mod__context *context , const ECOA__uint16 topic_id, const Common_lib__json_text* payload);

/******************************************************************************/

/* Property */
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/
/* log API */
void LDP_myLLMModel_mod__log_trace(
      myLLMModel_mod__context *context,
      char *log);
void LDP_myLLMModel_mod__log_debug(
      myLLMModel_mod__context *context,
      char *log);
void LDP_myLLMModel_mod__log_info(
      myLLMModel_mod__context *context,
      char *log);
void LDP_myLLMModel_mod__log_warning(
      myLLMModel_mod__context *context,
      char *log);
void LDP_myLLMModel_mod__raise_error(
      myLLMModel_mod__context *context,
      char *log,
      const ECOA__error_code error_code);
void LDP_myLLMModel_mod__raise_fatal_error(
      myLLMModel_mod__context *context,
      char *log,
      const ECOA__error_code error_code);

/* Time API */
ECOA__return_status LDP_myLLMModel_mod__get_relative_local_time(
        myLLMModel_mod__context *context,
        ECOA__hr_time *relative_local_time);
ECOA__return_status LDP_myLLMModel_mod__get_UTC_time(
        myLLMModel_mod__context *context,
        ECOA__global_time *utc_time);
ECOA__return_status LDP_myLLMModel_mod__get_absolute_system_time(
        myLLMModel_mod__context *context,
        ECOA__global_time *absolute_system_time);
ECOA__return_status LDP_myLLMModel_mod__get_relative_local_time_resolution(
        myLLMModel_mod__context *context,
        ECOA__duration *relative_local_time_resolution);
ECOA__return_status LDP_myLLMModel_mod__get_UTC_time_resolution(
        myLLMModel_mod__context *context,
        ECOA__duration *utc_time_resolution);
ECOA__return_status LDP_myLLMModel_mod__get_absolute_system_time_resolution(
        myLLMModel_mod__context *context,
        ECOA__duration *absolute_system_time_resolution);
/******************************************************************************/

/* PINFO API */
/******************************************************************************/

/******************************************************************************/


#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _LDP_myLLMModel_mod_H */

