/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:21.938830    
*
* WARNING: all changes made in this file will be lost
*/

/**
* @file myLLMModel_mod_container.hpp
* @brief This is the Module Container header for Module / Container Interface Class Header
*
*/

#if !defined(_MYLLMMODEL_MOD_CONTAINER_HPP)
#define _MYLLMMODEL_MOD_CONTAINER_HPP

 /* Standard types */
#include <ECOA.hpp>


/*Additionnaly created types*/
#include "ECOA.hpp"
#include "Common_lib.hpp"

/*Container types*/
#include "myLLMModel_mod_container_types.hpp"

/* User context */
#include "myLLMModel_mod_user_context.hpp"
namespace myLLMModel_mod
{

class Container
{
	public:

		/* Logging and fault management API */
        void  log_trace (const ECOA::log &log);
        void  log_debug (const ECOA::log &log);
        void  log_info (const ECOA::log &log);
        void  log_warning (const ECOA::log &log);
        void  raise_error (const ECOA::log &log, const ECOA::error_code error_code);
        void  raise_fatal_error (const ECOA::log &log, const ECOA::error_code error_code);

    	/*Time services API */
        void get_relative_local_time(ECOA::hr_time& relative_local_time);

        ECOA::return_status get_UTC_time(ECOA::global_time& utc_time);
        ECOA::return_status get_absolute_system_time(ECOA::global_time& absolute_system_time);

    	/* Time resolution services API */
        void get_relative_local_time_resolution(ECOA::duration& relative_local_time_resolution);
        void get_UTC_time_resolution(ECOA::duration& utc_time_resolution);
        void get_absolute_system_time_resolution(ECOA::duration& absolute_system_time_resolution);

    	/* Optional API for saving the warm start context */
    	void save_warm_start_context();

    	/* APIs generated */

        void json_control__send(const ECOA::uint16 topic_id, const Common_lib::json_text& payload);


        ECOA::return_status query_versioned_json__request_async(ECOA::uint32& ID);    	/* Properties API */

        /* PINFO API */

        // If this is a Fault Handler module, then an additional API is declared: Recovery Action API
        ECOA::return_status recovery_action(ECOA::recovery_action_type recovery_action, ECOA::asset_id asset_id, ECOA::asset_type asset_type);

        // Other container technical data will accessible through the incomplete structured defined here
        struct platform_hook;

        // The constructor of the Container shall have the following signature
        Container(platform_hook* hook);

    private:

        // private data for this container implementation is declared as a private struct within the implementation
        platform_hook* hook;

}; /* Class Container */

} /* namespace myLLMModel_mod*/

#endif /* MYLLMMODEL_MOD_CONTAINER_HPP */