/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:21.943812    
*
* WARNING: all changes made in this file will be lost
*/

/*
* Container Types for Module myLLMModel_mod
* Generated automatically from specification;
*/

#if !defined(_MYLLMMODEL_MOD_CONTAINER_TYPES_HPP)
#define _MYLLMMODEL_MOD_CONTAINER_TYPES_HPP

#define ECOA_VERSIONED_DATA_HANDLE_PRIVATE_SIZE 32

#include <ECOA.hpp>
namespace myLLMModel_mod {
    
}
#endif /* _MYLLMMODEL_MOD_CONTAINER_TYPES_HPP */