/* Generated by LDP */
/* Helpers for the Module Implementation myLLMModel_mod */

#if !defined(MYLLMMODEL_MOD_HELPERS)
#define MYLLMMODEL_MOD_HELPERS
#include "ECOA.h"
#include "myLLMModel_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYLLMMODEL_MOD;

void myLLMModel_mod_log_info(myLLMModel_mod__context* context, char *msg, ...);
void myLLMModel_mod_log(myLLMModel_mod__context* context, char *msg, ...);


void myLLMModel_mod__async_request_query_versioned_json(myLLMModel_mod__context* context, const ECOA__uint32 ID);


#if defined(__cplusplus)
}
#endif
#endif /* MYLLMMODEL_MOD_HELPERS */
