/* Generated by LDP */
/* Helpers for the Module Implementation myLLMModel_mod */

#include "ECOA.h"
#include "myLLMModel_mod.h"
#include "myLLMModel_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myLLMModel_mod__context context;

    return 0;
}
