/**
* @file LDP_myYYYDevice_mod.c
* @brief This is the code of the DA encapsulation library for ECOA
*
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* This file is generated by the DA ECOA tools and shall not be modified
*/
#include <string.h>

#include <ECOA.h>
#include "myYYYDevice_mod_container.h"
#include "LDP_myYYYDevice_mod.h"
static ECOA__log error_log = {
	sizeof("Error in log_warning")+1,
	"Error in log_warning"
};

void LDP_myYYYDevice_mod__concat(myYYYDevice_mod__context *context,
		ECOA__log *log, char *str) {
	char *module_name = "myYYYDevice_mod: ";
	int module_name_length;
        ECOA__error_code error_code = 0;

	module_name_length = strnlen(module_name, ECOA__LOG_MAXSIZE);

#if defined(__STDC_LIB_EXT1__)
	errno_t result;

	result = strncpy_s((char *)log->data, ECOA__LOG_MAXSIZE, module_name, ECOA__LOG_MAXSIZE - 1);
	if (result != 0) {
		myYYYDevice_mod_container__raise_error(context, error_log,error_code);
	}

	result = strncpy_s(((char *)log->data) + module_name_length, ECOA__LOG_MAXSIZE - module_name_length, str, ECOA__LOG_MAXSIZE - module_name_length - 1);
	if (result != 0) {
		myYYYDevice_mod_container__raise_error(context, error_log,error_code);
	}
#else
	char *returned_string;

	returned_string = strncpy((char *) log->data, module_name,
			ECOA__LOG_MAXSIZE);
	if (returned_string != (char *) log->data) {
		myYYYDevice_mod_container__raise_error(context, error_log,error_code);
	}

	returned_string = strncpy(((char *) log->data) + module_name_length, str,
			ECOA__LOG_MAXSIZE - module_name_length);
	if (returned_string != ((char *) log->data) + module_name_length) {
		myYYYDevice_mod_container__raise_error(context, error_log,error_code);
	}
#endif

	log->current_size = strnlen((char *) log->data, ECOA__LOG_MAXSIZE);

}


/*********** Log related API *************/
void LDP_myYYYDevice_mod__log_trace(myYYYDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myYYYDevice_mod__concat(context, &log, str);
    myYYYDevice_mod_container__log_trace(context, log);
}

void LDP_myYYYDevice_mod__log_debug(myYYYDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myYYYDevice_mod__concat(context, &log, str);
    myYYYDevice_mod_container__log_debug(context, log);
}

void LDP_myYYYDevice_mod__log_info(myYYYDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myYYYDevice_mod__concat(context, &log, str);
    myYYYDevice_mod_container__log_info(context, log);
}

void LDP_myYYYDevice_mod__log_warning(myYYYDevice_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myYYYDevice_mod__concat(context, &log, str);
    myYYYDevice_mod_container__log_warning(context, log);
}

void LDP_myYYYDevice_mod__raise_error(myYYYDevice_mod__context* context, char *str, const ECOA__error_code error_code)
{
    ECOA__log log;
    LDP_myYYYDevice_mod__concat(context, &log, str);
    myYYYDevice_mod_container__raise_error(context, log , error_code);
}

void LDP_myYYYDevice_mod__raise_fatal_error(myYYYDevice_mod__context* context, char *str, const ECOA__error_code error_code)
{
    ECOA__log log;
    LDP_myYYYDevice_mod__concat(context, &log, str);
    myYYYDevice_mod_container__raise_fatal_error(context, log, error_code);
}


/********** Time related API *************/
ECOA__return_status LDP_myYYYDevice_mod__get_absolute_system_time(
        myYYYDevice_mod__context *context,
        ECOA__global_time *absolute_system_time) {
    ECOA__return_status return_status;

    return_status = myYYYDevice_mod_container__get_absolute_system_time(context, absolute_system_time);

    if(return_status == ECOA__return_status_CLOCK_UNSYNCHRONIZED) {
        LDP_myYYYDevice_mod__log_warning(context, "Clock Unsynchronized when get_absolute_system_time");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when get_absolute_system_time");
    }
    return return_status;
}

ECOA__return_status LDP_myYYYDevice_mod__get_relative_local_time(
        myYYYDevice_mod__context *context,
        ECOA__hr_time *relative_local_time) {
    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;

    myYYYDevice_mod_container__get_relative_local_time(context, relative_local_time);

    return return_status;
}

ECOA__return_status LDP_myYYYDevice_mod__get_UTC_time(
        myYYYDevice_mod__context *context,
        ECOA__global_time *utc_time) {
    ECOA__return_status return_status;

    return_status = myYYYDevice_mod_container__get_UTC_time(context, utc_time);

    if(return_status == ECOA__return_status_CLOCK_UNSYNCHRONIZED) {
        LDP_myYYYDevice_mod__log_warning(context, "Clock Unsynchronized when get_UTC_time");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when get_UTC_time");
    }
    return return_status;
}

ECOA__return_status LDP_myYYYDevice_mod__get_relative_local_time_resolution(
        myYYYDevice_mod__context *context,
        ECOA__duration *relative_local_time_resolution){

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myYYYDevice_mod_container__get_relative_local_time_resolution(context, relative_local_time_resolution);

    return return_status;
}

ECOA__return_status LDP_myYYYDevice_mod__get_UTC_time_resolution(
        myYYYDevice_mod__context *context,
        ECOA__duration *utc_time_resolution) {

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myYYYDevice_mod_container__get_UTC_time_resolution(context, utc_time_resolution);

    return return_status;
}

ECOA__return_status LDP_myYYYDevice_mod__get_absolute_system_time_resolution(
        myYYYDevice_mod__context *context,
        ECOA__duration *absolute_system_time_resolution) {

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myYYYDevice_mod_container__get_absolute_system_time_resolution(context, absolute_system_time_resolution);

    return return_status;
}

/************* EVENT SEND ****************/


/************ DATA WRITTEN ***************/
ECOA__return_status LDP_myYYYDevice_mod__get_write_access__versioned_data_out(
        myYYYDevice_mod__context *context,
        myYYYDevice_mod_container__versioned_data_out_handle *data_handle) {

    ECOA__return_status return_status;

    return_status = myYYYDevice_mod_container__versioned_data_out__get_write_access(context, data_handle);

    if(return_status == ECOA__return_status_DATA_NOT_INITIALIZED) {
        LDP_myYYYDevice_mod__log_info(context, "Data not initialized when get_write_access__versioned_data_out");
    } else if(return_status == ECOA__return_status_INVALID_HANDLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Invalid handle when get_write_access__versioned_data_out");
    } else if(return_status == ECOA__return_status_RESOURCE_NOT_AVAILABLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Resource not available when get_write_access__versioned_data_out");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when get_write_access__versioned_data_out");
    }

    return return_status;
}
ECOA__return_status LDP_myYYYDevice_mod__publish_write_access__versioned_data_out(
        myYYYDevice_mod__context *context,
        myYYYDevice_mod_container__versioned_data_out_handle *data_handle) {

    ECOA__return_status return_status;
    return_status = myYYYDevice_mod_container__versioned_data_out__publish_write_access(context, data_handle);

    if(return_status == ECOA__return_status_INVALID_HANDLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Invalid handle when publish_write_access__versioned_data_out");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when publish_write_access__versioned_data_out");
    }

    return return_status;
}
ECOA__return_status LDP_myYYYDevice_mod__cancel_write_access__versioned_data_out(
        myYYYDevice_mod__context *context,
        myYYYDevice_mod_container__versioned_data_out_handle *data_handle) {

    ECOA__return_status return_status;

    return_status = myYYYDevice_mod_container__versioned_data_out__cancel_write_access(
context, data_handle);

    if(return_status == ECOA__return_status_INVALID_HANDLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Invalid handle when cancel_write_access__versioned_data_out");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when cancel_write_access__versioned_data_out");
    }

    return return_status;
}
ECOA__return_status LDP_myYYYDevice_mod__write__versioned_data_out(
        myYYYDevice_mod__context *context,
        Common_lib__versioned_data *data) {

    ECOA__return_status return_status;
    myYYYDevice_mod_container__versioned_data_out_handle data_handle;

    return_status = LDP_myYYYDevice_mod__get_write_access__versioned_data_out(context, &data_handle);

    if(return_status ==  ECOA__return_status_OK ||
       return_status ==  ECOA__return_status_DATA_NOT_INITIALIZED) {
        memcpy(data_handle.data, data, sizeof(Common_lib__versioned_data));
        return_status= LDP_myYYYDevice_mod__publish_write_access__versioned_data_out(
context, &data_handle);
    }
    return return_status;
}


/************* DATA READ *****************/
ECOA__return_status LDP_myYYYDevice_mod__release_read_access__event_data_in(
        myYYYDevice_mod__context *context, 
        myYYYDevice_mod_container__event_data_in_handle *data_handle) {

    ECOA__return_status return_status;

    return_status = myYYYDevice_mod_container__event_data_in__release_read_access(context, data_handle);

    if(return_status == ECOA__return_status_RESOURCE_NOT_AVAILABLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Resource not available when release_read_access__event_data_in");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when release_read_access__event_data_in");
    }

    return return_status;
}
ECOA__return_status LDP_myYYYDevice_mod__read__event_data_in(
myYYYDevice_mod__context *context, Common_lib__event_data *data) {

    ECOA__return_status return_status;
    myYYYDevice_mod_container__event_data_in_handle data_handle;

    return_status = LDP_myYYYDevice_mod__get_read_access__event_data_in(context, &data_handle);

    if(return_status ==  ECOA__return_status_OK) {
        memcpy(data, data_handle.data, sizeof(Common_lib__event_data));
        return_status = LDP_myYYYDevice_mod__release_read_access__event_data_in(context, &data_handle);
    }
    return return_status;
}
ECOA__return_status LDP_myYYYDevice_mod__get_read_access__event_data_in(
        myYYYDevice_mod__context *context,
        myYYYDevice_mod_container__event_data_in_handle *data_handle) {

    ECOA__return_status return_status;

    return_status = myYYYDevice_mod_container__event_data_in__get_read_access(context, data_handle);

    if(return_status == ECOA__return_status_NO_DATA) {
        LDP_myYYYDevice_mod__log_warning(context, "No data when get_read_access__event_data_in");
    } else if(return_status == ECOA__return_status_INVALID_HANDLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Invalid handle when get_read_access__event_data_in");
    } else if(return_status == ECOA__return_status_RESOURCE_NOT_AVAILABLE) {
        LDP_myYYYDevice_mod__log_warning(context, "Resource not available when get_read_access__event_data_in");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myYYYDevice_mod__log_warning(context, "Unknown error when get_read_access__event_data_in");
    }

    return return_status;
}


/************ RESPONSE SEND **************/


/************ REQUEST SYNC **************/


/*********** REQUEST ASYNC **************/


