/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.597068    
*/


/* Fault Handler Implementation for Platform_YYY */
#include "ldp_network.h"
#include "Platform_YYY_fault_handler.h"

void Platform_YYY__initialize_user_context(Platform_YYY_user_context * context) {
  /* @TODO TODO - To be implemented */
}

void Platform_YYY__error_notification (
  ldp_fault_handler_context* context, 
  ECOA__error_id error_id,
  ECOA__global_time timestamp,
  ECOA__asset_id asset_id,
  ECOA__asset_type asset_type,
  ECOA__error_type error_type,
  ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}
