/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.587625    
*
* WARNING: all changes made in this file will be lost
*/


/*
 * @file Common_lib_serialization.h
 * This is data-type declaration file
 */

#if !defined(_Common_lib_SERIALIZATION_H)
#define _Common_lib_SERIALIZATION_H
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

#include <stdint.h>
#include "ECOA.h"
#include "Common_lib.h"

/* Type Common_lib__event_data */
void serialize_Common_lib__event_data(const Common_lib__event_data* data, void *buffer, uint32_t max_size, uint32_t *added_size);
void deserialize_Common_lib__event_data(Common_lib__event_data *data, void *buffer, uint32_t length);
uint32_t size_of_Common_lib__event_data(void);

/* Type Common_lib__versioned_data */
void serialize_Common_lib__versioned_data(const Common_lib__versioned_data* data, void *buffer, uint32_t max_size, uint32_t *added_size);
void deserialize_Common_lib__versioned_data(Common_lib__versioned_data *data, void *buffer, uint32_t length);
uint32_t size_of_Common_lib__versioned_data(void);

/* Type Common_lib__json_text */
void serialize_Common_lib__json_text(const Common_lib__json_text* data, void *buffer, uint32_t max_size, uint32_t *added_size);
void deserialize_Common_lib__json_text(Common_lib__json_text *data, void *buffer, uint32_t length);
uint32_t max_size_of_Common_lib__json_text(void);
uint32_t current_size_of_Common_lib__json_text(const Common_lib__json_text *data);

/* Type Common_lib__voice_msg */
void serialize_Common_lib__voice_msg(const Common_lib__voice_msg* data, void *buffer, uint32_t max_size, uint32_t *added_size);
void deserialize_Common_lib__voice_msg(Common_lib__voice_msg *data, void *buffer, uint32_t length);
uint32_t max_size_of_Common_lib__voice_msg(void);
uint32_t current_size_of_Common_lib__voice_msg(const Common_lib__voice_msg *data);



#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _Common_lib_H */
