/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.662645    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef LDP__Common_lib_types_compare_H
#define LDP__Common_lib_types_compare_H
#include "stdbool.h"
#include "ECOA.h"
#include "Common_lib.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

bool LDP_Common_lib__event_data_compare(const Common_lib__event_data *data1, const Common_lib__event_data *data2);
bool LDP_Common_lib__versioned_data_compare(const Common_lib__versioned_data *data1, const Common_lib__versioned_data *data2);
bool LDP_Common_lib__json_text_compare(const Common_lib__json_text *data1, const Common_lib__json_text *data2);
bool LDP_Common_lib__voice_msg_compare(const Common_lib__voice_msg *data1, const Common_lib__voice_msg *data2);

#if defined(__cplusplus)
}
#endif /* __cplusplus */
#endif /*LDP__Common_lib_types_compare_H*/

