/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.663609    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef LDP__Common_lib_types_zeroise_H
#define LDP__Common_lib_types_zeroise_H
#include "stdbool.h"
#include "ECOA.h"
#include "Common_lib.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */
void LDP_Common_lib__event_data_zeroise(Common_lib__event_data *data);
void LDP_Common_lib__versioned_data_zeroise(Common_lib__versioned_data *data);
void LDP_Common_lib__json_text_zeroise(Common_lib__json_text *data);
void LDP_Common_lib__voice_msg_zeroise(Common_lib__voice_msg *data);

#if defined(__cplusplus)
}
#endif /* __cplusplus */
#endif /*LDP__Common_lib_types_zeroise_H*/

