/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:21.926501    
*/

#if !defined(MYLLMMODEL_MOD_USER_CONTEXT_HPP)
#define MYLLMMODEL_MOD_USER_CONTEXT_HPP

/*Standaard types*/
#include <ECOA.hpp>

/*Additionnaly created types*/
#include "ECOA.hpp"
#include "Common_lib.hpp"

/*Container types*/
#include "myLLMModel_mod_container_types.hpp"

namespace myLLMModel_mod
{

	typedef struct
	{

	} user_context;

	//Warm start Module Context structure example
	typedef struct
	{
		/* declare the Warm Start Module Context data here */

	} warm_start_context;

} /* myLLMModel_mod */

#endif /* MYLLMMODEL_MOD_USER_CONTEXT_HPP */