/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:34.152871    
*
* WARNING: all changes made in this file will be lost
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <inttypes.h>

#include <apr.h>
#include <apr_network_io.h>
#include <apr_errno.h>
#include <apr_strings.h>
#include <apr_poll.h>
#include <apr_thread_proc.h>

#include "ldp_network.h"
#include "route.h"
#include "ldp_time_manager.h"
#include "ldp_log_platform.h"
#include "ldp_fine_grain_deployment.h"
#include "main_tools.h"
#include "Platform_XXX_fault_handler.h"

static apr_pool_t* mem_pool = NULL;
static ldp_logger_platform platform_logger;
static ldp_fault_handler_context fault_handler_context;
static ldp_Main_ctx* Main_ctx = NULL;

int main(void){
    supervision_struct superv_tools = supervision_tools_h;
   ldp_status_t ret;
   // logger
   platform_logger.config_filename = "log_main_PF.properties";
   ldp_log_init((ldp_logger*)(&platform_logger));
   ldp_log_PF_initialize(&platform_logger, "main_PF");
   platform_logger.pd_name = "main_PD";
   platform_logger.node_name = "main_node";
   platform_logger.level_mask=0xffff;
   char log_msg[1024];
   snprintf(log_msg, 1024,"=== main started");
   ldp_log_PF_log(ECOA_LOG_INFO_PF,"INFO", &platform_logger,log_msg);

    /* chose every cores on the node */
    /* No need tyo set affinity: every cores are enable by default */
    cpu_mask ldp_create_cpu_mask_full(void);
    log_thread_deployment_properties(&platform_logger);

	ret=apr_initialize();
	assert(ret==APR_SUCCESS);
	apr_pool_create(&mem_pool,NULL);

    ldp_Main_ctx ctx = {.mem_pool = mem_pool,
                      .PD_number = 1,
                      .logger_PF = &platform_logger,
                      .fault_handler_context = &fault_handler_context,
                      .fault_handler_function_ptr = &Platform_XXX__error_notification,
                      .fault_handler_error_id = 0,
                      .superv_tools = & superv_tools,
                      .nb_init_clients = 0,
                      .nb_ready_clients = 0,
                      .ELI_platform_ID = ELI_PF_Platform_XXX
                     };
    Main_ctx = &ctx;

    Platform_XXX__initialize_user_context(&(ctx.fault_handler_context)->user);
    ctx.fault_handler_context->platform_hook = (struct Platform_XXX__platform_hook *)&ctx;
    ctx.interface_ctx_array = calloc(3, sizeof(ldp_interface_ctx));
    ctx.interface_ctx_array[0].info_r= (ldp_tcp_info){XXX_PD_port,XXX_PD_addr, 1, false};
    ctx.mcast_reader_interface_num = 0; 
    ctx.mcast_sender_interface_num = 1;
    ctx.mcast_sender_interface = calloc(1, sizeof(ldp_interface_ctx));
    ctx.mcast_sender_interface[0].type = LDP_ELI_MCAST;
    ctx.mcast_sender_interface[0].inter.mcast.UDP_current_PF_ID = link_XXX_to_EW_sent_PF_ID;
    ctx.mcast_sender_interface[0].info_r = (ldp_tcp_info) {link_XXX_to_EW_sent_port,
                                            link_XXX_to_EW_sent_addr,
                                            0, false};
    // connected platform information
    ctx.connected_platform_num = 1;
    ctx.connected_platforms = calloc(1, sizeof(ldp_platform_info));
    ctx.connected_platforms[0].ELI_platform_ID = ELI_PF_Platform_EW;
    ctx.connected_platforms[0].state = ELI_PF_DOWN;
    ctx.connected_platforms[0].sending_interface = &ctx.mcast_sender_interface[0];


    ldp_start_father_server(&ctx, ctx.interface_ctx_array, 0);
    int ret_status=0;
    // clean
    ldp_log_PF_deinitialize(&platform_logger);
    free(ctx.interface_ctx_array);
    apr_terminate();
    UNUSED(ret);
    return ret_status;
}

