/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.724300    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef LDP__ECOA_types_zeroise_H
#define LDP__ECOA_types_zeroise_H
#include "stdbool.h"
#include "ECOA.h"
#include "ECOA.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */
void LDP_ECOA__boolean8_zeroise(ECOA__boolean8 *data);
void LDP_ECOA__int8_zeroise(ECOA__int8 *data);
void LDP_ECOA__int16_zeroise(ECOA__int16 *data);
void LDP_ECOA__int32_zeroise(ECOA__int32 *data);
#if defined(ECOA_64BIT_SUPPORT)
void LDP_ECOA__int64_zeroise(ECOA__int64 *data);
#endif /* ECOA_64BIT_SUPPORT */
void LDP_ECOA__uint8_zeroise(ECOA__uint8 *data);
void LDP_ECOA__uint16_zeroise(ECOA__uint16 *data);
void LDP_ECOA__uint32_zeroise(ECOA__uint32 *data);
#if defined(ECOA_64BIT_SUPPORT)
void LDP_ECOA__uint64_zeroise(ECOA__uint64 *data);
#endif /* ECOA_64BIT_SUPPORT */
void LDP_ECOA__char8_zeroise(ECOA__char8 *data);
void LDP_ECOA__byte_zeroise(ECOA__byte *data);
void LDP_ECOA__float32_zeroise(ECOA__float32 *data);
#if defined(ECOA_64BIT_SUPPORT)
void LDP_ECOA__double64_zeroise(ECOA__double64 *data);
#endif /* ECOA_64BIT_SUPPORT */
void LDP_ECOA__duration_zeroise(ECOA__duration *data);
void LDP_ECOA__global_time_zeroise(ECOA__global_time *data);
void LDP_ECOA__hr_time_zeroise(ECOA__hr_time *data);
void LDP_ECOA__pinfo_filename_zeroise(ECOA__pinfo_filename *data);
void LDP_ECOA__log_zeroise(ECOA__log *data);

#if defined(__cplusplus)
}
#endif /* __cplusplus */
#endif /*LDP__ECOA_types_zeroise_H*/

