/* Generated by LDP */
/* Helpers for the Module Implementation myYYYDevice_mod */

#if !defined(MYYYYDEVICE_MOD_HELPERS)
#define MYYYYDEVICE_MOD_HELPERS
#include "ECOA.h"
#include "myYYYDevice_mod.h"

#include "ECOA.h"
#include "Common_lib.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYYYYDEVICE_MOD;

void myYYYDevice_mod_log_info(myYYYDevice_mod__context* context, char *msg, ...);
void myYYYDevice_mod_log(myYYYDevice_mod__context* context, char *msg, ...);


void myYYYDevice_mod__set_versioned_data_out(myYYYDevice_mod__context* context, Common_lib__versioned_data* data);
void myYYYDevice_mod__get_event_data_in(myYYYDevice_mod__context* context, Common_lib__event_data* data);

#if defined(__cplusplus)
}
#endif
#endif /* MYYYYDEVICE_MOD_HELPERS */
