/* Generated by LDP */
/* Helpers for the Module Implementation myYYYDevice_mod */

#include "ECOA.h"
#include "myYYYDevice_mod.h"
#include "myYYYDevice_mod_helpers.h"

#include "ECOA.h"
#include "Common_lib.h"

int main(int argc, char *argv[])
{
	myYYYDevice_mod__context context;

Common_lib__versioned_data Common_lib__versioned_data_data;
myYYYDevice_mod__set_versioned_data_out(&context, &Common_lib__versioned_data_data);

    return 0;
}
