/* Module Test Container Implementation Skeleton for myYYYDevice_mod */

/* @file myYYYDevice_mod_test_container.c
 * This is the Module Test Container for Module myYYYDevice_mod
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by LDP */

#include <stdlib.h>

#include "ECOA.h"
#include "myYYYDevice_mod_container.h"

#include "ECOA.h"
#include "Common_lib.h"

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__get_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  data_handle->data = malloc(sizeof(Common_lib__versioned_data));
  return return_status;
}

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__cancel_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myYYYDevice_mod_container__versioned_data_out__publish_write_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__versioned_data_out_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  free(data_handle->data);
  return return_status;
}


ECOA__return_status myYYYDevice_mod_container__event_data_in__get_read_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__event_data_in_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_INVALID_HANDLE;
  return return_status;
}

ECOA__return_status myYYYDevice_mod_container__event_data_in__release_read_access(myYYYDevice_mod__context* context, myYYYDevice_mod_container__event_data_in_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_INVALID_HANDLE;
  return return_status;
}


/* Properties API */

/* Logging services API call specifications */
void myYYYDevice_mod_container__log_trace(myYYYDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__log_debug(myYYYDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__log_info(myYYYDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__log_warning(myYYYDevice_mod__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__raise_error(myYYYDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__raise_fatal_error(myYYYDevice_mod__context* context, const ECOA__log log, const ECOA__error_code error_code)
{
  /* @TODO TODO - To be implemented */
}


/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myYYYDevice_mod_container__get_relative_local_time(myYYYDevice_mod__context* context, ECOA__hr_time *relative_local_time)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myYYYDevice_mod_container__get_UTC_time(myYYYDevice_mod__context* context, ECOA__global_time *utc_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myYYYDevice_mod_container__get_absolute_system_time(myYYYDevice_mod__context* context, ECOA__global_time *absolute_system_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

void myYYYDevice_mod_container__get_relative_local_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *relative_local_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__get_UTC_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *utc_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myYYYDevice_mod_container__get_absolute_system_time_resolution(myYYYDevice_mod__context* context, ECOA__duration *absolute_system_time_resolution)
{
  /* @TODO TODO - To be implemented */
}


