/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.673844    
*
* WARNING: all changes made in this file will be lost
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include <apr.h>
#include <apr_thread_cond.h>
#include <apr_network_io.h>
#include <apr_time.h>
#include <apr_thread_proc.h>

#include "ldp_thread.h"
#include "ldp_structures.h"
#include "route.h"
#include "ldp_network.h"
#include "ldp_comp_util.h"
#include "ldp_trigger.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_log.h"
#include "ldp_log_platform.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_mod_container_util.h"
#include "ldp_mod_lifecycle.h"
#include "ldp_fifo_manager.h"
#include "ldp_VD.h"

#include "component_mycompXXXDevice.hpp"
#include "component_mycompXXXDevice__properties.h"

#include "myXXXDevice_mod_container.hpp"
#include "myXXXDevice_mod.hpp"

#include "ECOA.hpp"
#include "ECOA.h"
#include "Common_lib.hpp"
#include "Common_lib.h"


void* start_module_compXXXDevice_myXXXDevice_mod_inst(apr_thread_t* t, void* args){

    ldp_module_context* ctx = (ldp_module_context*) args;
    myXXXDevice_mod::Container* mod_c = new myXXXDevice_mod::Container((myXXXDevice_mod::Container::platform_hook*)ctx);
    myXXXDevice_mod::Module* module_impl = new myXXXDevice_mod::Module();
    module_impl->container = mod_c;

    ctx->mem_pool = apr_thread_pool_get(t);
    ldp_init_pinfo_manager(&ctx->pinfo_manager, ctx->logger_PF);
    //init_mod_VD_manager(ctx->VD_manager);
    ldp_element* elt;

    bool is_running = true;
    while(is_running){
        ldp_fifo_manager_pop_elt(ctx->fifo_manager, &elt);

        switch (elt->op_ID){
            case LDP_ID_INITIALIZE_life:
                if(ctx->state == IDLE){
                    module_impl->myXXXDevice_mod::Module::INITIALIZE__received();
                    ldp_mod_lifecycle_initialize(ctx);
                }
                else{
                    ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myXXXDevice_mod_inst]: received INIT. Invalid state");
                }
                break;
            case LDP_ID_START_life:
                if(ctx->state == READY){
                   ldp_mod_lifecycle_start(ctx);
                    module_impl->myXXXDevice_mod::Module::START__received();
                }
                else{
                   ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myXXXDevice_mod_inst]: received START. Invalid state");
                }
                break;
            case LDP_ID_STOP_life:
               if(ctx->state == RUNNING){
                    module_impl->myXXXDevice_mod::Module::STOP__received();
                   ldp_mod_lifecycle_stop(ctx);
                }
                else{
                   ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myXXXDevice_mod_inst]: received STOP. Invalid state");
                }
                break;
            case LDP_ID_SHUTDOWN_life:
                if (ctx->state == RUNNING || ctx->state == READY){
                    module_impl->myXXXDevice_mod::Module::SHUTDOWN__received();
                    ldp_mod_lifecycle_shutdown(ctx, NULL);
                }
                else{
                    ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[myXXXDevice_mod_inst]: received SHUTDOWN. Invalid state");
                }
                break;
            case LDP_ID_KILL_life:
                module_impl->myXXXDevice_mod::Module::SHUTDOWN__received();
                ldp_mod_lifecycle_kill(ctx, NULL);
                is_running = false;
                break;
            default:
                if(ctx->state != RUNNING){
                    ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 2);
                    ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[myXXXDevice_mod_inst] Module is not in RUNNING state. Erase msg %u",elt->op_ID);
                }

                else if( elt->op_ID == compXXXDevice__myXXXDevice_mod_inst__trigger_voice){
                                        module_impl->myXXXDevice_mod::Module::trigger_voice__received();
                }

                else{
                    ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 3);
                    ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[myXXXDevice_mod_inst] unknow msg %u",elt->op_ID);
                }
        }
        ldp_fifo_manager_release_elt(ctx->fifo_manager, elt);
    }

    ldp_destroy_pinfo_manager(&ctx->pinfo_manager);
    //destroy_mod_VD_manager(&ctx->VD_manager);
    delete module_impl;
    delete mod_c;
    return NULL;

}
 
  extern "C" 

{
}
