/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.529770    
*
* WARNING: all changes made in this file will be lost
*/


/*
 * @file Common_lib.h
 * This is data-type declaration file
 * Generated by the function generate_C_types
 */

#if !defined(_Common_lib_H)
#define _Common_lib_H
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */


/* Type Common_lib__event_data */
typedef struct
{
  ECOA__uint16 topic_id; 
  ECOA__uint16 status_word_0; 
  ECOA__uint16 status_word_1; 
  ECOA__uint16 status_word_2; 
  ECOA__uint16 status_word_3; 
  ECOA__uint16 status_word_4; 
  ECOA__uint16 status_word_5; 
  ECOA__uint16 status_word_6; 
  ECOA__uint16 status_word_7; 
  ECOA__uint8 flag_0; 
  ECOA__uint8 flag_1; 
  ECOA__uint8 flag_2; 
  ECOA__uint8 flag_3; 
} Common_lib__event_data;

/* Type Common_lib__versioned_data */
typedef struct
{
  ECOA__uint16 version; 
  ECOA__uint16 sample_0; 
  ECOA__uint16 sample_1; 
  ECOA__uint16 sample_2; 
  ECOA__uint16 sample_3; 
  ECOA__uint8 channel_0; 
  ECOA__uint8 channel_1; 
  ECOA__uint8 channel_2; 
  ECOA__uint8 channel_3; 
  ECOA__uint8 channel_4; 
  ECOA__uint8 channel_5; 
  ECOA__uint8 channel_6; 
  ECOA__uint8 channel_7; 
  ECOA__uint8 channel_8; 
} Common_lib__versioned_data;

/* Type Common_lib__json_text */
#define Common_lib__json_text_MAXSIZE (1024)
typedef struct {
  ECOA__uint32 current_size;
  ECOA__char8 data[Common_lib__json_text_MAXSIZE];
} Common_lib__json_text;

/* Type Common_lib__voice_msg */
#define Common_lib__voice_msg_MAXSIZE (512)
typedef struct {
  ECOA__uint32 current_size;
  ECOA__char8 data[Common_lib__voice_msg_MAXSIZE];
} Common_lib__voice_msg;

#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _Common_lib_H */
