/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 02:31:45.533667    
*
* WARNING: all changes made in this file will be lost
*/


/*
 * @file Common_lib.hpp
 * This is data-type declaration file
 */


#include "ECOA.hpp"

#if !defined(_Common_lib_HPP)
#define _Common_lib_HPP
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

namespace Common_lib{


/* Type event_data */
typedef struct
{
  ECOA::uint16 topic_id;
  ECOA::uint16 status_word_0;
  ECOA::uint16 status_word_1;
  ECOA::uint16 status_word_2;
  ECOA::uint16 status_word_3;
  ECOA::uint16 status_word_4;
  ECOA::uint16 status_word_5;
  ECOA::uint16 status_word_6;
  ECOA::uint16 status_word_7;
  ECOA::uint8 flag_0;
  ECOA::uint8 flag_1;
  ECOA::uint8 flag_2;
  ECOA::uint8 flag_3;
} event_data;

/* Type versioned_data */
typedef struct
{
  ECOA::uint16 version;
  ECOA::uint16 sample_0;
  ECOA::uint16 sample_1;
  ECOA::uint16 sample_2;
  ECOA::uint16 sample_3;
  ECOA::uint8 channel_0;
  ECOA::uint8 channel_1;
  ECOA::uint8 channel_2;
  ECOA::uint8 channel_3;
  ECOA::uint8 channel_4;
  ECOA::uint8 channel_5;
  ECOA::uint8 channel_6;
  ECOA::uint8 channel_7;
  ECOA::uint8 channel_8;
} versioned_data;

/* Type json_text */
static const ECOA::uint32 json_text_MAXSIZE=1024;
typedef struct {
  ECOA::uint32 current_size;
  ECOA::char8 data[1024];
} json_text;

/* Type voice_msg */
static const ECOA::uint32 voice_msg_MAXSIZE=512;
typedef struct {
  ECOA::uint32 current_size;
  ECOA::char8 data[512];
} voice_msg;

} /* Common_lib */ 
#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _Common_lib_HPP */
