/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.310688    
*
* WARNING: all changes made in this file will be lost
*/

#include <stdio.h> 
#include <stdlib.h>  
#include <string.h> 
#include <assert.h> 

#include <apr.h>
#include <apr_thread_cond.h>
#include <apr_network_io.h>
#include <apr_time.h>
#include <apr_thread_proc.h>

#include "ldp_thread.h"
#include "ldp_structures.h"
#include "route.h"
#include "ldp_network.h"
#include "ldp_comp_util.h"
#include "ldp_trigger.h"
#include "ldp_dynamic_trigger.h"

#include "ldp_log.h"
#include "ldp_log_platform.h"
#include "ldp_dynamic_trigger.h"
#include "ldp_mod_container_util.h"
#include "ldp_mod_lifecycle.h"
#include "ldp_fifo_manager.h"
#include "ldp_VD.h"
#include "component_mycompVoiceMgmt.h"
#include "component_mycompVoiceMgmt__properties.h"
#include "myVoiceMgmt_mod_container.h" 
#include "myVoiceMgmt_mod.h" 



 void * start_module_compVoiceMgmt_myVoiceMgmt_mod_inst(apr_thread_t* t, void* args){
   ldp_module_context* ctx = (ldp_module_context*) args;
   myVoiceMgmt_mod__context module_impl;
   module_impl.platform_hook = (struct myVoiceMgmt_mod__platform_hook*)ctx;

   ctx->mem_pool = apr_thread_pool_get(t);
   ldp_init_pinfo_manager(&ctx->pinfo_manager, ctx->logger_PF);
   ldp_init_mod_VD_managers(ctx);
   ldp_element* elt;
    bool is_running = true;
    while(is_running){
       ldp_fifo_manager_pop_elt(ctx->fifo_manager, &elt);
       switch (elt->op_ID){
       case LDP_ID_INITIALIZE_life:
           if(ctx->state == IDLE){
               myVoiceMgmt_mod__INITIALIZE__received(&module_impl);
                ldp_mod_lifecycle_initialize(ctx);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myVoiceMgmt_mod_inst]: received INIT. Invalid state");
               ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 5);
           }
           break;
       case LDP_ID_START_life:
           if(ctx->state == READY){
               ldp_mod_lifecycle_start(ctx);
               myVoiceMgmt_mod__START__received(&module_impl);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myVoiceMgmt_mod_inst]: received START. Invalid state");
               ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id,ECOA__asset_type_COMPONENT, ECOA__error_type_INITIALISATION_PROBLEM, 6);
           }
           break;
       case LDP_ID_STOP_life:
           if(ctx->state == RUNNING){
               myVoiceMgmt_mod__STOP__received(&module_impl);
               ldp_mod_lifecycle_stop(ctx);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myVoiceMgmt_mod_inst]: received STOP. Invalid state");
           }
           break;
       case LDP_ID_SHUTDOWN_life:
           if (ctx->state == RUNNING || ctx->state == READY){
               myVoiceMgmt_mod__SHUTDOWN__received(&module_impl);
                ldp_mod_lifecycle_shutdown(ctx, NULL);
           }else{
               ldp_log_PF_log(ECOA_LOG_WARN_PF,"WARNING", ctx->logger_PF,"[               myVoiceMgmt_mod_inst]: received SHUTDOWN. Invalid state");
           }
           break;
       case LDP_ID_KILL_life:
           myVoiceMgmt_mod__SHUTDOWN__received(&module_impl);
           ldp_mod_lifecycle_kill(ctx, NULL);
           is_running = false;
           break;
       default:
            if(ctx->state != RUNNING){
                ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[                myVoiceMgmt_mod_inst] Module is not in RUNNING state. Erase msg %u",elt->op_ID);
                ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id, ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 2);
            }else if( elt->op_ID == compVoiceMgmt__myVoiceMgmt_mod_inst__json_control){ //event_json_control:svc_json_cmd_myVoiceMgmt_mod_inst_json_control
                ECOA__uint16 topic_id;
                memcpy(&topic_id, &elt->parameters[0], sizeof(ECOA__uint16));
                const Common_lib__json_text* payload = ((const Common_lib__json_text*) &elt->parameters[0+sizeof(ECOA__uint16)]);
                myVoiceMgmt_mod__json_control__received(&module_impl,topic_id,payload);
            }else if( elt->op_ID == compVoiceMgmt__myVoiceMgmt_mod_inst__query_versioned_json){ //RR_query_versioned_json:svc_vd_query_myVoiceMgmt_mod_inst_query_versioned_json
                ECOA__uint32 ID;
                memcpy(&ID, &elt->parameters[0],sizeof(ECOA__uint32));
                if(ldp_check_concurrent_RR_num(ctx,0, 10) == MOD_CONTAINER_OK){
                    ctx->req_resp.current_RR_number[0]++;
                myVoiceMgmt_mod__query_versioned_json__request_received(&module_impl, ID );
}
            }else if( elt->op_ID == compVoiceMgmt__myVoiceMgmt_mod_inst__versioned_data_in){ //data_versioned_data:svc_versioned_data_myVoiceMgmt_mod_inst_versioned_data_in
                // notification
                myVoiceMgmt_mod__versioned_data_in__updated(&module_impl);
            }else{
               ldp_log_PF_log_var(ECOA_LOG_WARN_PF,"WARN", ctx->logger_PF,"[myVoiceMgmt_mod_inst] unknow msg %u",elt->op_ID);assert(0);
               ldp_send_fault_error_to_father(ctx->component_ctx, ctx->mod_id,ECOA__asset_type_COMPONENT, ECOA__error_type_UNAVAILABLE, 3);
           }
		}
           ldp_fifo_manager_release_elt(ctx->fifo_manager, elt);
	}
   ldp_destroy_pinfo_manager(&ctx->pinfo_manager);
return NULL;
}


