/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-06 00:25:58.303306    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _COMPONENT_MYCOMPVOICEMGMT_H 
#define _COMPONENT_MYCOMPVOICEMGMT_H 

#include <apr_thread_proc.h>
#include "ldp_structures.h"

void* start_module_compVoiceMgmt_myVoiceMgmt_mod_inst(apr_thread_t* t, void* args);
 extern ldp_PDomain_ctx* compVoiceMgmt_ctx;
ldp_PDomain_ctx* init_comp_compVoiceMgmt(void);

#endif  /* _COMPONENT_MYCOMPVOICEMGMT_H */
