/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.024525    
*
* WARNING: all changes made in this file will be lost
*/

#ifndef _ROUTE_H 
#define _ROUTE_H 

#define ID_INITIALIZE_event "INITIALIZE" 
#define ID_START_event "START" 
#define ID_STOP_event "STOP" 
#define MODULE_BASE_PORT (20000+0)
#define COMPONENT_BASE_PORT (MODULE_BASE_PORT + 10000)

// ELI Platform IDs
#define ELI_PF_Platform_EW (2)

// Platform links

// local-node IP connections with master process
#define VoiceMgmt_PD_addr "0.0.0.0" 
#define VoiceMgmt_PD_port (COMPONENT_BASE_PORT+0) 

#define LLMModel_PD_addr "0.0.0.0" 
#define LLMModel_PD_port (COMPONENT_BASE_PORT+1) 


// local-node IP connections between PD
#define compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd_port (MODULE_BASE_PORT+2)
#define compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd_addr "0.0.0.0"
#define compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query_port (MODULE_BASE_PORT+3)
#define compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query_addr "0.0.0.0"


// wire service IDs

#define compLLMModel_svc_json_cmd__compVoiceMgmt_svc_json_cmd__json_control 1892203028
#define compLLMModel_svc_vd_query__compVoiceMgmt_svc_vd_query__query_versioned_json 1985629425


// module op ID

 /// VoiceMgmt_PD
// myVoiceMgmt_mod_inst compVoiceMgmt
#define compVoiceMgmt__myVoiceMgmt_mod_inst__json_control 200//
#define compVoiceMgmt__myVoiceMgmt_mod_inst__query_versioned_json 201 //
#define compVoiceMgmt__myVoiceMgmt_mod_inst__versioned_data_in 202//
 /// LLMModel_PD
// myLLMModel_mod_inst compLLMModel
#define compLLMModel__myLLMModel_mod_inst__voice_control 203//
#define compLLMModel__myLLMModel_mod_inst__voice_query 204//
#define compLLMModel__myLLMModel_mod_inst__query_versioned_json compVoiceMgmt__myVoiceMgmt_mod_inst__query_versioned_json//
#define compLLMModel__myLLMModel_mod_inst__json_control 205//


#endif /* _ROUTE_H */
