/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:08.593962    
*/


/* Module User Context Header for module myYYYDevice_mod */
#if !defined(MYYYYDEVICE_MOD_USER_CONTEXT_H)
#define MYYYYDEVICE_MOD_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/*
 * @file myYYYDevice_mod_user_context.h
 */

#include "ECOA.h"
#include "Common_lib.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** END USER-WRITTEN USER ***********/
} myYYYDevice_mod_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myYYYDevice_mod_warm_start_context;

#if defined(__cplusplus)
} 
#endif /* __cplusplus */

#endif  /* MYYYYDEVICE_MOD_USER_CONTEXT_H */
