/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.1.0    
*                date: 2026-08-05 23:50:22.048531    
*
* WARNING: all changes made in this file will be lost
*/


#include "ECOA.h"
#include "Common_lib.h"
// property struct
typedef struct myVoiceMgmt_mod_t__properties {
} myVoiceMgmt_mod_t__properties;

// component properties
typedef struct VoiceManagement__properties{
} VoiceManagement__properties;

