/**
* @file LDP_myLLMModel_mod.c
* @brief This is the code of the DA encapsulation library for ECOA
*
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* This file is generated by the DA ECOA tools and shall not be modified
*/
#include <string.h>

#include <ECOA.h>
#include "myLLMModel_mod_container.h"
#include "LDP_myLLMModel_mod.h"
static ECOA__log error_log = {
	sizeof("Error in log_warning")+1,
	"Error in log_warning"
};

void LDP_myLLMModel_mod__concat(myLLMModel_mod__context *context,
		ECOA__log *log, char *str) {
	char *module_name = "myLLMModel_mod: ";
	int module_name_length;
        ECOA__error_code error_code = 0;

	module_name_length = strnlen(module_name, ECOA__LOG_MAXSIZE);

#if defined(__STDC_LIB_EXT1__)
	errno_t result;

	result = strncpy_s((char *)log->data, ECOA__LOG_MAXSIZE, module_name, ECOA__LOG_MAXSIZE - 1);
	if (result != 0) {
		myLLMModel_mod_container__raise_error(context, error_log,error_code);
	}

	result = strncpy_s(((char *)log->data) + module_name_length, ECOA__LOG_MAXSIZE - module_name_length, str, ECOA__LOG_MAXSIZE - module_name_length - 1);
	if (result != 0) {
		myLLMModel_mod_container__raise_error(context, error_log,error_code);
	}
#else
	char *returned_string;

	returned_string = strncpy((char *) log->data, module_name,
			ECOA__LOG_MAXSIZE);
	if (returned_string != (char *) log->data) {
		myLLMModel_mod_container__raise_error(context, error_log,error_code);
	}

	returned_string = strncpy(((char *) log->data) + module_name_length, str,
			ECOA__LOG_MAXSIZE - module_name_length);
	if (returned_string != ((char *) log->data) + module_name_length) {
		myLLMModel_mod_container__raise_error(context, error_log,error_code);
	}
#endif

	log->current_size = strnlen((char *) log->data, ECOA__LOG_MAXSIZE);

}


/*********** Log related API *************/
void LDP_myLLMModel_mod__log_trace(myLLMModel_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myLLMModel_mod__concat(context, &log, str);
    myLLMModel_mod_container__log_trace(context, log);
}

void LDP_myLLMModel_mod__log_debug(myLLMModel_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myLLMModel_mod__concat(context, &log, str);
    myLLMModel_mod_container__log_debug(context, log);
}

void LDP_myLLMModel_mod__log_info(myLLMModel_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myLLMModel_mod__concat(context, &log, str);
    myLLMModel_mod_container__log_info(context, log);
}

void LDP_myLLMModel_mod__log_warning(myLLMModel_mod__context *context, char *str)
{
    ECOA__log log;
    LDP_myLLMModel_mod__concat(context, &log, str);
    myLLMModel_mod_container__log_warning(context, log);
}

void LDP_myLLMModel_mod__raise_error(myLLMModel_mod__context* context, char *str, const ECOA__error_code error_code)
{
    ECOA__log log;
    LDP_myLLMModel_mod__concat(context, &log, str);
    myLLMModel_mod_container__raise_error(context, log , error_code);
}

void LDP_myLLMModel_mod__raise_fatal_error(myLLMModel_mod__context* context, char *str, const ECOA__error_code error_code)
{
    ECOA__log log;
    LDP_myLLMModel_mod__concat(context, &log, str);
    myLLMModel_mod_container__raise_fatal_error(context, log, error_code);
}


/********** Time related API *************/
ECOA__return_status LDP_myLLMModel_mod__get_absolute_system_time(
        myLLMModel_mod__context *context,
        ECOA__global_time *absolute_system_time) {
    ECOA__return_status return_status;

    return_status = myLLMModel_mod_container__get_absolute_system_time(context, absolute_system_time);

    if(return_status == ECOA__return_status_CLOCK_UNSYNCHRONIZED) {
        LDP_myLLMModel_mod__log_warning(context, "Clock Unsynchronized when get_absolute_system_time");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myLLMModel_mod__log_warning(context, "Unknown error when get_absolute_system_time");
    }
    return return_status;
}

ECOA__return_status LDP_myLLMModel_mod__get_relative_local_time(
        myLLMModel_mod__context *context,
        ECOA__hr_time *relative_local_time) {
    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;

    myLLMModel_mod_container__get_relative_local_time(context, relative_local_time);

    return return_status;
}

ECOA__return_status LDP_myLLMModel_mod__get_UTC_time(
        myLLMModel_mod__context *context,
        ECOA__global_time *utc_time) {
    ECOA__return_status return_status;

    return_status = myLLMModel_mod_container__get_UTC_time(context, utc_time);

    if(return_status == ECOA__return_status_CLOCK_UNSYNCHRONIZED) {
        LDP_myLLMModel_mod__log_warning(context, "Clock Unsynchronized when get_UTC_time");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myLLMModel_mod__log_warning(context, "Unknown error when get_UTC_time");
    }
    return return_status;
}

ECOA__return_status LDP_myLLMModel_mod__get_relative_local_time_resolution(
        myLLMModel_mod__context *context,
        ECOA__duration *relative_local_time_resolution){

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myLLMModel_mod_container__get_relative_local_time_resolution(context, relative_local_time_resolution);

    return return_status;
}

ECOA__return_status LDP_myLLMModel_mod__get_UTC_time_resolution(
        myLLMModel_mod__context *context,
        ECOA__duration *utc_time_resolution) {

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myLLMModel_mod_container__get_UTC_time_resolution(context, utc_time_resolution);

    return return_status;
}

ECOA__return_status LDP_myLLMModel_mod__get_absolute_system_time_resolution(
        myLLMModel_mod__context *context,
        ECOA__duration *absolute_system_time_resolution) {

    ECOA__return_status return_status;
    return_status = ECOA__return_status_OK;
    myLLMModel_mod_container__get_absolute_system_time_resolution(context, absolute_system_time_resolution);

    return return_status;
}

/************* EVENT SEND ****************/
void LDP_myLLMModel_mod__send__json_control(myLLMModel_mod__context *context
    , const ECOA__uint16 topic_id, const Common_lib__json_text* payload) {
    
    myLLMModel_mod_container__json_control__send(context ,topic_id,payload);
}


/************ DATA WRITTEN ***************/


/************* DATA READ *****************/


/************ RESPONSE SEND **************/


/************ REQUEST SYNC **************/


/*********** REQUEST ASYNC **************/
ECOA__return_status LDP_myLLMModel_mod__request_async__query_versioned_json(
        myLLMModel_mod__context *context,
        ECOA__uint32 *ID ) {
    ECOA__return_status return_status;

    return_status = myLLMModel_mod_container__query_versioned_json__request_async(
        context,
        ID );

    if(return_status == ECOA__return_status_RESOURCE_NOT_AVAILABLE) {
        LDP_myLLMModel_mod__log_warning(context, "Resource not available when request_async__query_versioned_json");
    } else if(return_status != ECOA__return_status_OK) {
        LDP_myLLMModel_mod__log_warning(context, "Unknown error when request_async__query_versioned_json");
    }

    return return_status;
}


